# Support for SQL server via PyODBC package

## Adventure Works database

In [2]:
import pyodbc

# the parameter you need to manually input
config = dict(server=   'localhost', # change this to your SQL Server hostname or IP address
               port=      1433,       # change this to your SQL Server port number [1433 is the default]
               database= 'AdventureWorks', 
               username= 'tanya',     # set up the username and password for connection by using Microsoft SQL Server Managerment Studio
               password= 'Tanya1234') 

# connection boiler plate
conn_str = ('SERVER={server},{port};'   +
             'DATABASE={database};'     +
             'UID={username};'          +
             'PWD={password}')
conn = pyodbc.connect(
     r'DRIVER={ODBC Driver 13 for SQL Server};' + #this is the only item you may change
     conn_str.format(**config)
     )

# initiate the connection to SQL database
cursor = conn.cursor()
cursor.execute('SELECT * FROM dbo.AWBuildVersion;')

# list all the data 
for entry in cursor:
    print(entry)
    
conn.close

(1, '14.0.1000.169', datetime.datetime(2017, 8, 22, 19, 39, 35, 643000), datetime.datetime(2017, 10, 27, 14, 33, 2, 347000))

## Northwind databas

In [4]:
 import pyodbc
 config = dict(server=   'localhost', # change this to your SQL Server hostname or IP address
               port=      1433,       # change this to your SQL Server port number [1433 is the default]
               database= 'NorthWind',
               username= 'sa',         # use administor's default username: sa
               password= '1234')       # use administor's password. Set it in Microsoft SSMS.
 conn_str = ('SERVER={server},{port};'   +
             'DATABASE={database};'     +
             'UID={username};'          +
             'PWD={password}')
 conn = pyodbc.connect(
     r'DRIVER={ODBC Driver 13 for SQL Server};' +
     conn_str.format(**config)
     )
 cursor = conn.cursor()
 cursor.execute('SELECT * FROM dbo.Orders;')
 for entry in cursor:
     pass
     # print(entry) # Comment out for saving space in Jupyter notebook
 conn.close

# Connect SQL Server 2017 via its ODBC drivers

Method 1. use SQLAlchemy package

In [47]:
engine = create_engine("mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server")

Method 2. use SQL magic function

In [9]:
## if you have not loaded sql, type "load_ext sql"

# %reload_ext sql 
# %sql mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server
# %sql select * from orders

# Preliminary
- Show all the tables in our database
- Show all the columns in a table
- Show all the levels/categories in a column (a.k.a. field)

## P1. Show all the tables our db contains

### Method 1.

In [43]:
import pandas as pd
from pandas import Series
from sqlalchemy import create_engine
# engine = create_engine('sqlite:///Northwind.sqlite')
engine = create_engine('mssql+pyodbc://sa:isyegatech@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server')
Series(engine.table_names())

0               Categories
1     CustomerCustomerDemo
2     CustomerDemographics
3                Customers
4                Employees
5      EmployeeTerritories
6            Order Details
7                   Orders
8                 Products
9                   Region
10                Shippers
11               Suppliers
12             sysdiagrams
13             Territories
dtype: object

### Method 2. Use SQL with the connection string suggested by SQLALchemy (Better)

In [64]:
%load_ext sql 
%sql mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server
result = %sql SELECT * FROM NorthWind.INFORMATION_SCHEMA.TABLES --we can assign the result to a temp variable
print(result)

The sql extension is already loaded. To reload it, use:
  %reload_ext sql
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.
+---------------+--------------+--------------------------------+------------+
| TABLE_CATALOG | TABLE_SCHEMA |           TABLE_NAME           | TABLE_TYPE |
+---------------+--------------+--------------------------------+------------+
|   NorthWind   |     dbo      |             Orders             | BASE TABLE |
|   NorthWind   |     dbo      |            Products            | BASE TABLE |
|   NorthWind   |     dbo      |         Order Details          | BASE TABLE |
|   NorthWind   |     dbo      | Customer and Suppliers by City |    VIEW    |
|   NorthWind   |     dbo      | Alphabetical list of products  |    VIEW    |
|   NorthWind   |     dbo      |      Current Product List      |    VIEW    |
|   NorthWind   |     dbo      |           Orders Qry           |    VIEW    |
|   NorthWind   |     dbo      |  Products Above Average Price  |    VIEW    |
|   NorthWind   |     dbo      |      Products by Category      |    VIEW    |
|   NorthWind   |     dbo      |        Quarterly Orders        |    VIEW    |
|   NorthWind   |     dbo      |            Invoices            |    VIEW    |
|   NorthWind   |     dbo      |     Order Details Extended     |    VIEW    |
|   NorthWind   |     dbo      |        Order Subtotals         |    VIEW    |
|   NorthWind   |     dbo      |     Product Sales for 1997     |    VIEW    |
|   NorthWind   |     dbo      |    Category Sales for 1997     |    VIEW    |
|   NorthWind   |     dbo      |       Sales by Category        |    VIEW    |
|   NorthWind   |     dbo      |     Sales Totals by Amount     |    VIEW    |
|   NorthWind   |     dbo      |  Summary of Sales by Quarter   |    VIEW    |
|   NorthWind   |     dbo      |    Summary of Sales by Year    |    VIEW    |
|   NorthWind   |     dbo      |      CustomerCustomerDemo      | BASE TABLE |
|   NorthWind   |     dbo      |      CustomerDemographics      | BASE TABLE |
|   NorthWind   |     dbo      |             Region             | BASE TABLE |
|   NorthWind   |     dbo      |          Territories           | BASE TABLE |
|   NorthWind   |     dbo      |      EmployeeTerritories       | BASE TABLE |
|   NorthWind   |     dbo      |          sysdiagrams           | BASE TABLE |
|   NorthWind   |     dbo      |           Employees            | BASE TABLE |
|   NorthWind   |     dbo      |           Categories           | BASE TABLE |
|   NorthWind   |     dbo      |           Customers            | BASE TABLE |
|   NorthWind   |     dbo      |            Shippers            | BASE TABLE |
|   NorthWind   |     dbo      |           Suppliers            | BASE TABLE |
+---------------+--------------+--------------------------------+------------+

In [65]:
# Otherwise, let the result shown directly after the magic function
%sql SELECT * FROM NorthWind.INFORMATION_SCHEMA.TABLES --we can assign the result to a temp variable

   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('NorthWind', 'dbo', 'Orders', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Products', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Order Details', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Customer and Suppliers by City', 'VIEW'),
 ('NorthWind', 'dbo', 'Alphabetical list of products', 'VIEW'),
 ('NorthWind', 'dbo', 'Current Product List', 'VIEW'),
 ('NorthWind', 'dbo', 'Orders Qry', 'VIEW'),
 ('NorthWind', 'dbo', 'Products Above Average Price', 'VIEW'),
 ('NorthWind', 'dbo', 'Products by Category', 'VIEW'),
 ('NorthWind', 'dbo', 'Quarterly Orders', 'VIEW'),
 ('NorthWind', 'dbo', 'Invoices', 'VIEW'),
 ('NorthWind', 'dbo', 'Order Details Extended', 'VIEW'),
 ('NorthWind', 'dbo', 'Order Subtotals', 'VIEW'),
 ('NorthWind', 'dbo', 'Product Sales for 1997', 'VIEW'),
 ('NorthWind', 'dbo', 'Category Sales for 1997', 'VIEW'),
 ('NorthWind', 'dbo', 'Sales by Category', 'VIEW'),
 ('NorthWind', 'dbo', 'Sales Totals by Amount', 'VIEW'),
 ('NorthWind', 'dbo', 'Summary of Sales by Quarter', 'VIEW'),
 ('NorthWind', 'dbo', 'Summary of Sales by Year', 'VIEW'),
 ('NorthWind', 'dbo', 'CustomerCustomerDemo', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'CustomerDemographics', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Region', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Territories', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'EmployeeTerritories', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'sysdiagrams', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Employees', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Categories', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Customers', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Shippers', 'BASE TABLE'),
 ('NorthWind', 'dbo', 'Suppliers', 'BASE TABLE')]

## P2. Show all the column names of our table

In [72]:
# use either load_ext sql or reload_ext sql
# %sql sqlite:///Northwind_small.sqlite

In [56]:
%reload_ext sql 
%sql mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server
%sql SELECT * FROM NorthWind.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Order Details'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('NorthWind', 'dbo', 'Order Details', 'OrderID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'ProductID', 2, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'UnitPrice', 3, '(0)', 'NO', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'Quantity', 4, '(1)', 'NO', 'smallint', None, None, 5, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'Discount', 5, '(0)', 'NO', 'real', None, None, 24, 2, None, None, None, None, None, None, None, None, None, None, None)]

## P3. Show all the values in a column

In [8]:
import sqlite3
conn = sqlite3.connect('')
cursor = sqlite3.connect('Northwind_small.sqlite').cursor()
# cursor = sqlite3.connect("mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server").cursor()
jobs = [job[0] for job in cursor.execute("SELECT Country FROM Employee")]
print(set(jobs))
cursor.close()

{'UK', 'USA'}

# Questions

In [2]:
# Be sure to use it under TensorFlow-GPU 
# Otherwise, you need to install ipython-sql
%load_ext sql

In [3]:
%sql mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC+Driver+13+for+SQL+Server

'Connected: sa@NorthWind'

## M01. What shippers do we have?

From P1, we konw we have 14 tables in the Northwind_small database. <br> 
Now the first question is "Show all the columns in the Shippers table."

In [10]:
%%sql
SELECT * FROM Shippers;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 'Speedy Express', '(503) 555-9831'),
 (2, 'United Package', '(503) 555-3199'),
 (3, 'Federal Shipping', '(503) 555-9931')]

## M02. Show only two columns, CategoryName and Description, in the Categories table.

In [33]:
%%sql
SELECT * FROM INFORMATION_SCHEMA.Columns WHERE TABLE_NAME='Categories'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('NorthWind', 'dbo', 'Categories', 'CategoryID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Categories', 'CategoryName', 2, None, 'NO', 'nvarchar', 15, 30, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Categories', 'Description', 3, None, 'YES', 'ntext', 1073741823, 2147483646, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Categories', 'Picture', 4, None, 'YES', 'image', 2147483647, 2147483647, None, None, None, None, None, None, None, None, None, None, None, None, None)]

In [32]:
%%sql
SELECT CategoryID, CategoryName, Description FROM Categories;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 'lol', 'Soft drinks, coffees, teas, beers, and ales'),
 (2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (3, 'Confections', 'Desserts, candies, and sweet breads'),
 (4, 'Dairy Products', 'Cheeses'),
 (5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (6, 'Meat/Poultry', 'Prepared meats'),
 (7, 'Produce', 'Dried fruit and bean curd'),
 (8, 'Seafood', 'Seaweed and fish')]

## M03. Show the sales representatives roster in the Employee table.

Show full names and hire dates for every sales representative.

In [23]:
%%sql
SELECT FirstName, LastName, Title, HireDate FROM Employees;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Nancy', 'Davolio', 'Sales Representative', datetime.datetime(1992, 5, 1, 0, 0)),
 ('Andrew', 'Fuller', 'Vice President, Sales', datetime.datetime(1992, 8, 14, 0, 0)),
 ('Janet', 'Leverling', 'Sales Representative', datetime.datetime(1992, 4, 1, 0, 0)),
 ('Margaret', 'Peacock', 'Sales Representative', datetime.datetime(1993, 5, 3, 0, 0)),
 ('Steven', 'Buchanan', 'Sales Manager', datetime.datetime(1993, 10, 17, 0, 0)),
 ('Michael', 'Suyama', 'Sales Representative', datetime.datetime(1993, 10, 17, 0, 0)),
 ('Robert', 'King', 'Sales Representative', datetime.datetime(1994, 1, 2, 0, 0)),
 ('Laura', 'Callahan', 'Inside Sales Coordinator', datetime.datetime(1994, 3, 5, 0, 0)),
 ('Anne', 'Dodsworth', 'Sales Representative', datetime.datetime(1994, 11, 15, 0, 0))]

**Don't** use double quotation!

In [39]:
%%sql
SELECT FirstName, LastName, Title, HireDate, Country FROM Employees WHERE Title='Sales Representative';

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Nancy', 'Davolio', 'Sales Representative', datetime.datetime(1992, 5, 1, 0, 0), 'USA'),
 ('Janet', 'Leverling', 'Sales Representative', datetime.datetime(1992, 4, 1, 0, 0), 'USA'),
 ('Margaret', 'Peacock', 'Sales Representative', datetime.datetime(1993, 5, 3, 0, 0), 'USA'),
 ('Michael', 'Suyama', 'Sales Representative', datetime.datetime(1993, 10, 17, 0, 0), 'UK'),
 ('Robert', 'King', 'Sales Representative', datetime.datetime(1994, 1, 2, 0, 0), 'UK'),
 ('Anne', 'Dodsworth', 'Sales Representative', datetime.datetime(1994, 11, 15, 0, 0), 'UK')]

## M04. (from M03) Sales representatives in the US

In [40]:
%%sql 
SELECT FirstName, LastName, HireDate, Country
FROM Employees
WHERE Title='Sales Representative' and Country='USA';

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Nancy', 'Davolio', datetime.datetime(1992, 5, 1, 0, 0), 'USA'),
 ('Janet', 'Leverling', datetime.datetime(1992, 4, 1, 0, 0), 'USA'),
 ('Margaret', 'Peacock', datetime.datetime(1993, 5, 3, 0, 0), 'USA')]

## M05. Show orders placed by someone

In [43]:
%%sql 
SELECT *
FROM Northwind.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Orders'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('NorthWind', 'dbo', 'Orders', 'OrderID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'CustomerID', 2, None, 'YES', 'nchar', 5, 10, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'EmployeeID', 3, None, 'YES', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'OrderDate', 4, None, 'YES', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'RequiredDate', 5, None, 'YES', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShippedDate', 6, None, 'YES', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipVia', 7, None, 'YES', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'Freight', 8, '(0)', 'YES', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipName', 9, None, 'YES', 'nvarchar', 40, 80, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipAddress', 10, None, 'YES', 'nvarchar', 60, 120, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipCity', 11, None, 'YES', 'nvarchar', 15, 30, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipRegion', 12, None, 'YES', 'nvarchar', 15, 30, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipPostalCode', 13, None, 'YES', 'nvarchar', 10, 20, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Orders', 'ShipCountry', 14, None, 'YES', 'nvarchar', 15, 30, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None)]

In [58]:
%%sql
SELECT OrderID, OrderDate FROM Orders
WHERE EmployeeID=5

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
   sqlite:///Northwind_small.sqlite
Done.

[(10248, datetime.datetime(1996, 7, 4, 0, 0)),
 (10254, datetime.datetime(1996, 7, 11, 0, 0)),
 (10269, datetime.datetime(1996, 7, 31, 0, 0)),
 (10297, datetime.datetime(1996, 9, 4, 0, 0)),
 (10320, datetime.datetime(1996, 10, 3, 0, 0)),
 (10333, datetime.datetime(1996, 10, 18, 0, 0)),
 (10358, datetime.datetime(1996, 11, 20, 0, 0)),
 (10359, datetime.datetime(1996, 11, 21, 0, 0)),
 (10372, datetime.datetime(1996, 12, 4, 0, 0)),
 (10378, datetime.datetime(1996, 12, 10, 0, 0)),
 (10397, datetime.datetime(1996, 12, 27, 0, 0)),
 (10463, datetime.datetime(1997, 3, 4, 0, 0)),
 (10474, datetime.datetime(1997, 3, 13, 0, 0)),
 (10477, datetime.datetime(1997, 3, 17, 0, 0)),
 (10529, datetime.datetime(1997, 5, 7, 0, 0)),
 (10549, datetime.datetime(1997, 5, 27, 0, 0)),
 (10569, datetime.datetime(1997, 6, 16, 0, 0)),
 (10575, datetime.datetime(1997, 6, 20, 0, 0)),
 (10607, datetime.datetime(1997, 7, 22, 0, 0)),
 (10648, datetime.datetime(1997, 8, 28, 0, 0)),
 (10649, datetime.datetime(1997, 8, 28, 0, 0)),
 (10650, datetime.datetime(1997, 8, 29, 0, 0)),
 (10654, datetime.datetime(1997, 9, 2, 0, 0)),
 (10675, datetime.datetime(1997, 9, 19, 0, 0)),
 (10711, datetime.datetime(1997, 10, 21, 0, 0)),
 (10714, datetime.datetime(1997, 10, 22, 0, 0)),
 (10721, datetime.datetime(1997, 10, 29, 0, 0)),
 (10730, datetime.datetime(1997, 11, 5, 0, 0)),
 (10761, datetime.datetime(1997, 12, 2, 0, 0)),
 (10812, datetime.datetime(1998, 1, 2, 0, 0)),
 (10823, datetime.datetime(1998, 1, 9, 0, 0)),
 (10841, datetime.datetime(1998, 1, 20, 0, 0)),
 (10851, datetime.datetime(1998, 1, 26, 0, 0)),
 (10866, datetime.datetime(1998, 2, 3, 0, 0)),
 (10869, datetime.datetime(1998, 2, 4, 0, 0)),
 (10870, datetime.datetime(1998, 2, 4, 0, 0)),
 (10872, datetime.datetime(1998, 2, 5, 0, 0)),
 (10874, datetime.datetime(1998, 2, 6, 0, 0)),
 (10899, datetime.datetime(1998, 2, 20, 0, 0)),
 (10922, datetime.datetime(1998, 3, 3, 0, 0)),
 (10954, datetime.datetime(1998, 3, 17, 0, 0)),
 (11043, datetime.datetime(1998, 4, 22, 0, 0))]

## M06. Logic Operators
In Table Suppliers, show the attribute list of people not Marketing Manager. The attributes include the SupplierID, ContacName, and ContactTitle.

In [46]:
%%sql
SELECT SupplierID, ContactName, ContactTitle
FROM Suppliers
WHERE ContactTitle <> 'Marketing Manager'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 'Charlotte Cooper', 'Purchasing Manager'),
 (2, 'Shelley Burke', 'Order Administrator'),
 (3, 'Regina Murphy', 'Sales Representative'),
 (5, 'Antonio del Valle Saavedra', 'Export Administrator'),
 (6, 'Mayumi Ohno', 'Marketing Representative'),
 (8, 'Peter Wilson', 'Sales Representative'),
 (9, 'Lars Peterson', 'Sales Agent'),
 (11, 'Petra Winkler', 'Sales Manager'),
 (12, 'Martin Bein', 'International Marketing Mgr.'),
 (13, 'Sven Petersen', 'Coordinator Foreign Markets'),
 (14, 'Elio Rossi', 'Sales Representative'),
 (16, 'Cheryl Saylor', 'Regional Account Rep.'),
 (17, 'Michael Björn', 'Sales Representative'),
 (18, 'Guylène Nodier', 'Sales Manager'),
 (19, 'Robb Merchant', 'Wholesale Account Agent'),
 (20, 'Chandra Leka', 'Owner'),
 (21, 'Niels Petersen', 'Sales Manager'),
 (22, 'Dirk Luchte', 'Accounting Manager'),
 (23, 'Anne Heikkonen', 'Product Manager'),
 (24, 'Wendy Mackenzie', 'Sales Representative'),
 (26, 'Giovanni Giudici', 'Order Administrator'),
 (27, 'Marie Delamare', 'Sales Manager'),
 (28, 'Eliane Noz', 'Sales Representative'),
 (29, 'Chantal Goulet', 'Accounting Manager')]

In [8]:
%%sql
SELECT SupplierID, ContactName, ContactTitle
FROM Suppliers
WHERE ContactTitle != 'Marketing Manager'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 'Charlotte Cooper', 'Purchasing Manager'),
 (2, 'Shelley Burke', 'Order Administrator'),
 (3, 'Regina Murphy', 'Sales Representative'),
 (5, 'Antonio del Valle Saavedra', 'Export Administrator'),
 (6, 'Mayumi Ohno', 'Marketing Representative'),
 (8, 'Peter Wilson', 'Sales Representative'),
 (9, 'Lars Peterson', 'Sales Agent'),
 (11, 'Petra Winkler', 'Sales Manager'),
 (12, 'Martin Bein', 'International Marketing Mgr.'),
 (13, 'Sven Petersen', 'Coordinator Foreign Markets'),
 (14, 'Elio Rossi', 'Sales Representative'),
 (16, 'Cheryl Saylor', 'Regional Account Rep.'),
 (17, 'Michael Björn', 'Sales Representative'),
 (18, 'Guylène Nodier', 'Sales Manager'),
 (19, 'Robb Merchant', 'Wholesale Account Agent'),
 (20, 'Chandra Leka', 'Owner'),
 (21, 'Niels Petersen', 'Sales Manager'),
 (22, 'Dirk Luchte', 'Accounting Manager'),
 (23, 'Anne Heikkonen', 'Product Manager'),
 (24, 'Wendy Mackenzie', 'Sales Representative'),
 (26, 'Giovanni Giudici', 'Order Administrator'),
 (27, 'Marie Delamare', 'Sales Manager'),
 (28, 'Eliane Noz', 'Sales Representative'),
 (29, 'Chantal Goulet', 'Accounting Manager')]

## M07. String Matching
In Table Products, show the attributes of products whose name includes the string "queso". The attributes include their IDs and Names.

In [45]:
%%sql
SELECT ProductID, ProductName
FROM Products
WHERE ProductName LIKE '%queso%'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(11, 'Queso Cabrales'), (12, 'Queso Manchego La Pastora')]

## M08. Logical Operators
In Table Orders, show the attribute of orders which come from either France or Belgium (@ShipCountry). The attributes include the OrderID, CustomerID, and ShipCountry.

In [44]:
%%sql
SELECT OrderID, CustomerID, ShipCountry
FROM Orders
WHERE ShipCountry='France' or ShipCountry='Belgium'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10248, 'VINET', 'France'),
 (10251, 'VICTE', 'France'),
 (10252, 'SUPRD', 'Belgium'),
 (10265, 'BLONP', 'France'),
 (10274, 'VINET', 'France'),
 (10295, 'VINET', 'France'),
 (10297, 'BLONP', 'France'),
 (10302, 'SUPRD', 'Belgium'),
 (10311, 'DUMON', 'France'),
 (10331, 'BONAP', 'France'),
 (10334, 'VICTE', 'France'),
 (10340, 'BONAP', 'France'),
 (10350, 'LAMAI', 'France'),
 (10358, 'LAMAI', 'France'),
 (10360, 'BLONP', 'France'),
 (10362, 'BONAP', 'France'),
 (10371, 'LAMAI', 'France'),
 (10408, 'FOLIG', 'France'),
 (10413, 'LAMAI', 'France'),
 (10425, 'LAMAI', 'France'),
 (10436, 'BLONP', 'France'),
 (10449, 'BLONP', 'France'),
 (10450, 'VICTE', 'France'),
 (10454, 'LAMAI', 'France'),
 (10458, 'SUPRD', 'Belgium'),
 (10459, 'VICTE', 'France'),
 (10463, 'SUPRD', 'Belgium'),
 (10470, 'BONAP', 'France'),
 (10475, 'SUPRD', 'Belgium'),
 (10478, 'VICTE', 'France'),
 (10480, 'FOLIG', 'France'),
 (10493, 'LAMAI', 'France'),
 (10500, 'LAMAI', 'France'),
 (10511, 'BONAP', 'France'),
 (10525, 'BONAP', 'France'),
 (10529, 'MAISD', 'Belgium'),
 (10546, 'VICTE', 'France'),
 (10559, 'BLONP', 'France'),
 (10566, 'BLONP', 'France'),
 (10584, 'BLONP', 'France'),
 (10609, 'DUMON', 'France'),
 (10610, 'LAMAI', 'France'),
 (10628, 'BLONP', 'France'),
 (10631, 'LAMAI', 'France'),
 (10634, 'FOLIG', 'France'),
 (10649, 'MAISD', 'Belgium'),
 (10663, 'BONAP', 'France'),
 (10671, 'FRANR', 'France'),
 (10679, 'BLONP', 'France'),
 (10683, 'DUMON', 'France'),
 (10715, 'BONAP', 'France'),
 (10730, 'BONAP', 'France'),
 (10732, 'BONAP', 'France'),
 (10737, 'VINET', 'France'),
 (10738, 'SPECD', 'France'),
 (10739, 'VINET', 'France'),
 (10755, 'BONAP', 'France'),
 (10760, 'MAISD', 'Belgium'),
 (10763, 'FOLIG', 'France'),
 (10767, 'SUPRD', 'Belgium'),
 (10787, 'LAMAI', 'France'),
 (10789, 'FOLIG', 'France'),
 (10806, 'VICTE', 'France'),
 (10814, 'VICTE', 'France'),
 (10826, 'BLONP', 'France'),
 (10827, 'BONAP', 'France'),
 (10832, 'LAMAI', 'France'),
 (10841, 'SUPRD', 'Belgium'),
 (10843, 'VICTE', 'France'),
 (10846, 'SUPRD', 'Belgium'),
 (10850, 'VICTE', 'France'),
 (10858, 'LACOR', 'France'),
 (10860, 'FRANR', 'France'),
 (10871, 'BONAP', 'France'),
 (10876, 'BONAP', 'France'),
 (10885, 'SUPRD', 'Belgium'),
 (10890, 'DUMON', 'France'),
 (10892, 'MAISD', 'Belgium'),
 (10896, 'MAISD', 'Belgium'),
 (10907, 'SPECD', 'France'),
 (10923, 'LAMAI', 'France'),
 (10927, 'LACOR', 'France'),
 (10930, 'SUPRD', 'Belgium'),
 (10932, 'BONAP', 'France'),
 (10940, 'BONAP', 'France'),
 (10964, 'SPECD', 'France'),
 (10971, 'FRANR', 'France'),
 (10972, 'LACOR', 'France'),
 (10973, 'LACOR', 'France'),
 (10978, 'MAISD', 'Belgium'),
 (11004, 'MAISD', 'Belgium'),
 (11035, 'SUPRD', 'Belgium'),
 (11038, 'SUPRD', 'Belgium'),
 (11043, 'SPECD', 'France'),
 (11051, 'LAMAI', 'France'),
 (11076, 'BONAP', 'France')]

## M09. True if in a set

In [6]:
%%sql
SELECT TOP 10 OrderID, CustomerID, ShipCountry
FROM Orders
WHERE ShipCountry IN ('Brazil', 'Mexico', 'Argentina', 'Venezuela')

UsageError: Cell magic `%%sql` not found.

## M10. Sorting

SQL is case insensitive.

In [48]:
%%sql 
SELECT FirstName, LastName, Title, BirthDate
FROM Employees
ORDER BY BirthDate

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Margaret', 'Peacock', 'Sales Representative', datetime.datetime(1937, 9, 19, 0, 0)),
 ('Nancy', 'Davolio', 'Sales Representative', datetime.datetime(1948, 12, 8, 0, 0)),
 ('Andrew', 'Fuller', 'Vice President, Sales', datetime.datetime(1952, 2, 19, 0, 0)),
 ('Steven', 'Buchanan', 'Sales Manager', datetime.datetime(1955, 3, 4, 0, 0)),
 ('Laura', 'Callahan', 'Inside Sales Coordinator', datetime.datetime(1958, 1, 9, 0, 0)),
 ('Robert', 'King', 'Sales Representative', datetime.datetime(1960, 5, 29, 0, 0)),
 ('Michael', 'Suyama', 'Sales Representative', datetime.datetime(1963, 7, 2, 0, 0)),
 ('Janet', 'Leverling', 'Sales Representative', datetime.datetime(1963, 8, 30, 0, 0)),
 ('Anne', 'Dodsworth', 'Sales Representative', datetime.datetime(1966, 1, 27, 0, 0))]

## M11. Datetime conversion

In [49]:
%%sql
SELECT FirstName, LastName, Title, DateOnlyBirthDate=CONVERT(DATE,BirthDate)
FROM Employees
ORDER BY BirthDate

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Margaret', 'Peacock', 'Sales Representative', datetime.date(1937, 9, 19)),
 ('Nancy', 'Davolio', 'Sales Representative', datetime.date(1948, 12, 8)),
 ('Andrew', 'Fuller', 'Vice President, Sales', datetime.date(1952, 2, 19)),
 ('Steven', 'Buchanan', 'Sales Manager', datetime.date(1955, 3, 4)),
 ('Laura', 'Callahan', 'Inside Sales Coordinator', datetime.date(1958, 1, 9)),
 ('Robert', 'King', 'Sales Representative', datetime.date(1960, 5, 29)),
 ('Michael', 'Suyama', 'Sales Representative', datetime.date(1963, 7, 2)),
 ('Janet', 'Leverling', 'Sales Representative', datetime.date(1963, 8, 30)),
 ('Anne', 'Dodsworth', 'Sales Representative', datetime.date(1966, 1, 27))]

## M12. String concatenation

In [52]:
%%sql
SELECT FirstName, LastName, FullName= FirstName + ' ' + LastName
FROM Employees

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Nancy', 'Davolio', 'Nancy Davolio'),
 ('Andrew', 'Fuller', 'Andrew Fuller'),
 ('Janet', 'Leverling', 'Janet Leverling'),
 ('Margaret', 'Peacock', 'Margaret Peacock'),
 ('Steven', 'Buchanan', 'Steven Buchanan'),
 ('Michael', 'Suyama', 'Michael Suyama'),
 ('Robert', 'King', 'Robert King'),
 ('Laura', 'Callahan', 'Laura Callahan'),
 ('Anne', 'Dodsworth', 'Anne Dodsworth')]

In [9]:
%%sql
SELECT FirstName, LastName, FullName= CONCAT(FirstName, ' ', LastName)
FROM Employees

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Nancy', 'Davolio', 'Nancy Davolio'),
 ('Andrew', 'Fuller', 'Andrew Fuller'),
 ('Janet', 'Leverling', 'Janet Leverling'),
 ('Margaret', 'Peacock', 'Margaret Peacock'),
 ('Steven', 'Buchanan', 'Steven Buchanan'),
 ('Michael', 'Suyama', 'Michael Suyama'),
 ('Robert', 'King', 'Robert King'),
 ('Laura', 'Callahan', 'Laura Callahan'),
 ('Anne', 'Dodsworth', 'Anne Dodsworth')]

## M13. Arithmetic Operators

In [60]:
%%sql
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='Order' + ' ' + 'Details'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('NorthWind', 'dbo', 'Order Details', 'OrderID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'ProductID', 2, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'UnitPrice', 3, '(0)', 'NO', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'Quantity', 4, '(1)', 'NO', 'smallint', None, None, 5, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Order Details', 'Discount', 5, '(0)', 'NO', 'real', None, None, 24, 2, None, None, None, None, None, None, None, None, None, None, None)]

In [62]:
%%sql
SELECT OrderID, ProductID, UnitPrice, Quantity, TotalPrice = UnitPrice * Quantity
FROM "Order Details"
ORDER BY OrderID, ProductID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10248, 11, Decimal('14.0000'), 12, Decimal('168.0000')),
 (10248, 42, Decimal('9.8000'), 10, Decimal('98.0000')),
 (10248, 72, Decimal('34.8000'), 5, Decimal('174.0000')),
 (10249, 14, Decimal('18.6000'), 9, Decimal('167.4000')),
 (10249, 51, Decimal('42.4000'), 40, Decimal('1696.0000')),
 (10250, 41, Decimal('7.7000'), 10, Decimal('77.0000')),
 (10250, 51, Decimal('42.4000'), 35, Decimal('1484.0000')),
 (10250, 65, Decimal('16.8000'), 15, Decimal('252.0000')),
 (10251, 22, Decimal('16.8000'), 6, Decimal('100.8000')),
 (10251, 57, Decimal('15.6000'), 15, Decimal('234.0000')),
 (10251, 65, Decimal('16.8000'), 20, Decimal('336.0000')),
 (10252, 20, Decimal('64.8000'), 40, Decimal('2592.0000')),
 (10252, 33, Decimal('2.0000'), 25, Decimal('50.0000')),
 (10252, 60, Decimal('27.2000'), 40, Decimal('1088.0000')),
 (10253, 31, Decimal('10.0000'), 20, Decimal('200.0000')),
 (10253, 39, Decimal('14.4000'), 42, Decimal('604.8000')),
 (10253, 49, Decimal('16.0000'), 40, Decimal('640.0000')),
 (10254, 24, Decimal('3.6000'), 15, Decimal('54.0000')),
 (10254, 55, Decimal('19.2000'), 21, Decimal('403.2000')),
 (10254, 74, Decimal('8.0000'), 21, Decimal('168.0000')),
 (10255, 2, Decimal('15.2000'), 20, Decimal('304.0000')),
 (10255, 16, Decimal('13.9000'), 35, Decimal('486.5000')),
 (10255, 36, Decimal('15.2000'), 25, Decimal('380.0000')),
 (10255, 59, Decimal('44.0000'), 30, Decimal('1320.0000')),
 (10256, 53, Decimal('26.2000'), 15, Decimal('393.0000')),
 (10256, 77, Decimal('10.4000'), 12, Decimal('124.8000')),
 (10257, 27, Decimal('35.1000'), 25, Decimal('877.5000')),
 (10257, 39, Decimal('14.4000'), 6, Decimal('86.4000')),
 (10257, 77, Decimal('10.4000'), 15, Decimal('156.0000')),
 (10258, 2, Decimal('15.2000'), 50, Decimal('760.0000')),
 (10258, 5, Decimal('17.0000'), 65, Decimal('1105.0000')),
 (10258, 32, Decimal('25.6000'), 6, Decimal('153.6000')),
 (10259, 21, Decimal('8.0000'), 10, Decimal('80.0000')),
 (10259, 37, Decimal('20.8000'), 1, Decimal('20.8000')),
 (10260, 41, Decimal('7.7000'), 16, Decimal('123.2000')),
 (10260, 57, Decimal('15.6000'), 50, Decimal('780.0000')),
 (10260, 62, Decimal('39.4000'), 15, Decimal('591.0000')),
 (10260, 70, Decimal('12.0000'), 21, Decimal('252.0000')),
 (10261, 21, Decimal('8.0000'), 20, Decimal('160.0000')),
 (10261, 35, Decimal('14.4000'), 20, Decimal('288.0000')),
 (10262, 5, Decimal('17.0000'), 12, Decimal('204.0000')),
 (10262, 7, Decimal('24.0000'), 15, Decimal('360.0000')),
 (10262, 56, Decimal('30.4000'), 2, Decimal('60.8000')),
 (10263, 16, Decimal('13.9000'), 60, Decimal('834.0000')),
 (10263, 24, Decimal('3.6000'), 28, Decimal('100.8000')),
 (10263, 30, Decimal('20.7000'), 60, Decimal('1242.0000')),
 (10263, 74, Decimal('8.0000'), 36, Decimal('288.0000')),
 (10264, 2, Decimal('15.2000'), 35, Decimal('532.0000')),
 (10264, 41, Decimal('7.7000'), 25, Decimal('192.5000')),
 (10265, 17, Decimal('31.2000'), 30, Decimal('936.0000')),
 (10265, 70, Decimal('12.0000'), 20, Decimal('240.0000')),
 (10266, 12, Decimal('30.4000'), 12, Decimal('364.8000')),
 (10267, 40, Decimal('14.7000'), 50, Decimal('735.0000')),
 (10267, 59, Decimal('44.0000'), 70, Decimal('3080.0000')),
 (10267, 76, Decimal('14.4000'), 15, Decimal('216.0000')),
 (10268, 29, Decimal('99.0000'), 10, Decimal('990.0000')),
 (10268, 72, Decimal('27.8000'), 4, Decimal('111.2000')),
 (10269, 33, Decimal('2.0000'), 60, Decimal('120.0000')),
 (10269, 72, Decimal('27.8000'), 20, Decimal('556.0000')),
 (10270, 36, Decimal('15.2000'), 30, Decimal('456.0000')),
 (10270, 43, Decimal('36.8000'), 25, Decimal('920.0000')),
 (10271, 33, Decimal('2.0000'), 24, Decimal('48.0000')),
 (10272, 20, Decimal('64.8000'), 6, Decimal('388.8000')),
 (10272, 31, Decimal('10.0000'), 40, Decimal('400.0000')),
 (10272, 72, Decimal('27.8000'), 24, Decimal('667.2000')),
 (10273, 10, Decimal('24.8000'), 24, Decimal('595.2000')),
 (10273, 31, Decimal('10.0000'), 15, Decimal('150.0000')),
 (10273, 33, Decimal('2.0000'), 20, Decimal('40.0000')),
 (10273, 40, Decimal('14.7000'), 60, Decimal('882.0000')),
 (10273, 76, Decimal('14.4000'), 33, Decimal('475.2000')),
 (10274, 71, Decimal('17.2000'), 20, Decimal('344.0000')),
 (10274, 72, Decimal('27.8000'), 7, Decimal('194.6000')),
 (10275, 24, Decimal('3.6000'), 12, Decimal('43.2000')),
 (10275, 59, Decimal('44.0000'), 6, Decimal('264.0000')),
 (10276, 10, Decimal('24.8000'), 15, Decimal('372.0000')),
 (10276, 13, Decimal('4.8000'), 10, Decimal('48.0000')),
 (10277, 28, Decimal('36.4000'), 20, Decimal('728.0000')),
 (10277, 62, Decimal('39.4000'), 12, Decimal('472.8000')),
 (10278, 44, Decimal('15.5000'), 16, Decimal('248.0000')),
 (10278, 59, Decimal('44.0000'), 15, Decimal('660.0000')),
 (10278, 63, Decimal('35.1000'), 8, Decimal('280.8000')),
 (10278, 73, Decimal('12.0000'), 25, Decimal('300.0000')),
 (10279, 17, Decimal('31.2000'), 15, Decimal('468.0000')),
 (10280, 24, Decimal('3.6000'), 12, Decimal('43.2000')),
 (10280, 55, Decimal('19.2000'), 20, Decimal('384.0000')),
 (10280, 75, Decimal('6.2000'), 30, Decimal('186.0000')),
 (10281, 19, Decimal('7.3000'), 1, Decimal('7.3000')),
 (10281, 24, Decimal('3.6000'), 6, Decimal('21.6000')),
 (10281, 35, Decimal('14.4000'), 4, Decimal('57.6000')),
 (10282, 30, Decimal('20.7000'), 6, Decimal('124.2000')),
 (10282, 57, Decimal('15.6000'), 2, Decimal('31.2000')),
 (10283, 15, Decimal('12.4000'), 20, Decimal('248.0000')),
 (10283, 19, Decimal('7.3000'), 18, Decimal('131.4000')),
 (10283, 60, Decimal('27.2000'), 35, Decimal('952.0000')),
 (10283, 72, Decimal('27.8000'), 3, Decimal('83.4000')),
 (10284, 27, Decimal('35.1000'), 15, Decimal('526.5000')),
 (10284, 44, Decimal('15.5000'), 21, Decimal('325.5000')),
 (10284, 60, Decimal('27.2000'), 20, Decimal('544.0000')),
 (10284, 67, Decimal('11.2000'), 5, Decimal('56.0000')),
 (10285, 1, Decimal('14.4000'), 45, Decimal('648.0000')),
 (10285, 40, Decimal('14.7000'), 40, Decimal('588.0000')),
 (10285, 53, Decimal('26.2000'), 36, Decimal('943.2000')),
 (10286, 35, Decimal('14.4000'), 100, Decimal('1440.0000')),
 (10286, 62, Decimal('39.4000'), 40, Decimal('1576.0000')),
 (10287, 16, Decimal('13.9000'), 40, Decimal('556.0000')),
 (10287, 34, Decimal('11.2000'), 20, Decimal('224.0000')),
 (10287, 46, Decimal('9.6000'), 15, Decimal('144.0000')),
 (10288, 54, Decimal('5.9000'), 10, Decimal('59.0000')),
 (10288, 68, Decimal('10.0000'), 3, Decimal('30.0000')),
 (10289, 3, Decimal('8.0000'), 30, Decimal('240.0000')),
 (10289, 64, Decimal('26.6000'), 9, Decimal('239.4000')),
 (10290, 5, Decimal('17.0000'), 20, Decimal('340.0000')),
 (10290, 29, Decimal('99.0000'), 15, Decimal('1485.0000')),
 (10290, 49, Decimal('16.0000'), 15, Decimal('240.0000')),
 (10290, 77, Decimal('10.4000'), 10, Decimal('104.0000')),
 (10291, 13, Decimal('4.8000'), 20, Decimal('96.0000')),
 (10291, 44, Decimal('15.5000'), 24, Decimal('372.0000')),
 (10291, 51, Decimal('42.4000'), 2, Decimal('84.8000')),
 (10292, 20, Decimal('64.8000'), 20, Decimal('1296.0000')),
 (10293, 18, Decimal('50.0000'), 12, Decimal('600.0000')),
 (10293, 24, Decimal('3.6000'), 10, Decimal('36.0000')),
 (10293, 63, Decimal('35.1000'), 5, Decimal('175.5000')),
 (10293, 75, Decimal('6.2000'), 6, Decimal('37.2000')),
 (10294, 1, Decimal('14.4000'), 18, Decimal('259.2000')),
 (10294, 17, Decimal('31.2000'), 15, Decimal('468.0000')),
 (10294, 43, Decimal('36.8000'), 15, Decimal('552.0000')),
 (10294, 60, Decimal('27.2000'), 21, Decimal('571.2000')),
 (10294, 75, Decimal('6.2000'), 6, Decimal('37.2000')),
 (10295, 56, Decimal('30.4000'), 4, Decimal('121.6000')),
 (10296, 11, Decimal('16.8000'), 12, Decimal('201.6000')),
 (10296, 16, Decimal('13.9000'), 30, Decimal('417.0000')),
 (10296, 69, Decimal('28.8000'), 15, Decimal('432.0000')),
 (10297, 39, Decimal('14.4000'), 60, Decimal('864.0000')),
 (10297, 72, Decimal('27.8000'), 20, Decimal('556.0000')),
 (10298, 2, Decimal('15.2000'), 40, Decimal('608.0000')),
 (10298, 36, Decimal('15.2000'), 40, Decimal('608.0000')),
 (10298, 59, Decimal('44.0000'), 30, Decimal('1320.0000')),
 (10298, 62, Decimal('39.4000'), 15, Decimal('591.0000')),
 (10299, 19, Decimal('7.3000'), 15, Decimal('109.5000')),
 (10299, 70, Decimal('12.0000'), 20, Decimal('240.0000')),
 (10300, 66, Decimal('13.6000'), 30, Decimal('408.0000')),
 (10300, 68, Decimal('10.0000'), 20, Decimal('200.0000')),
 (10301, 40, Decimal('14.7000'), 10, Decimal('147.0000')),
 (10301, 56, Decimal('30.4000'), 20, Decimal('608.0000')),
 (10302, 17, Decimal('31.2000'), 40, Decimal('1248.0000')),
 (10302, 28, Decimal('36.4000'), 28, Decimal('1019.2000')),
 (10302, 43, Decimal('36.8000'), 12, Decimal('441.6000')),
 (10303, 40, Decimal('14.7000'), 40, Decimal('588.0000')),
 (10303, 65, Decimal('16.8000'), 30, Decimal('504.0000')),
 (10303, 68, Decimal('10.0000'), 15, Decimal('150.0000')),
 (10304, 49, Decimal('16.0000'), 30, Decimal('480.0000')),
 (10304, 59, Decimal('44.0000'), 10, Decimal('440.0000')),
 (10304, 71, Decimal('17.2000'), 2, Decimal('34.4000')),
 (10305, 18, Decimal('50.0000'), 25, Decimal('1250.0000')),
 (10305, 29, Decimal('99.0000'), 25, Decimal('2475.0000')),
 (10305, 39, Decimal('14.4000'), 30, Decimal('432.0000')),
 (10306, 30, Decimal('20.7000'), 10, Decimal('207.0000')),
 (10306, 53, Decimal('26.2000'), 10, Decimal('262.0000')),
 (10306, 54, Decimal('5.9000'), 5, Decimal('29.5000')),
 (10307, 62, Decimal('39.4000'), 10, Decimal('394.0000')),
 (10307, 68, Decimal('10.0000'), 3, Decimal('30.0000')),
 (10308, 69, Decimal('28.8000'), 1, Decimal('28.8000')),
 (10308, 70, Decimal('12.0000'), 5, Decimal('60.0000')),
 (10309, 4, Decimal('17.6000'), 20, Decimal('352.0000')),
 (10309, 6, Decimal('20.0000'), 30, Decimal('600.0000')),
 (10309, 42, Decimal('11.2000'), 2, Decimal('22.4000')),
 (10309, 43, Decimal('36.8000'), 20, Decimal('736.0000')),
 (10309, 71, Decimal('17.2000'), 3, Decimal('51.6000')),
 (10310, 16, Decimal('13.9000'), 10, Decimal('139.0000')),
 (10310, 62, Decimal('39.4000'), 5, Decimal('197.0000')),
 (10311, 42, Decimal('11.2000'), 6, Decimal('67.2000')),
 (10311, 69, Decimal('28.8000'), 7, Decimal('201.6000')),
 (10312, 28, Decimal('36.4000'), 4, Decimal('145.6000')),
 (10312, 43, Decimal('36.8000'), 24, Decimal('883.2000')),
 (10312, 53, Decimal('26.2000'), 20, Decimal('524.0000')),
 (10312, 75, Decimal('6.2000'), 10, Decimal('62.0000')),
 (10313, 36, Decimal('15.2000'), 12, Decimal('182.4000')),
 (10314, 32, Decimal('25.6000'), 40, Decimal('1024.0000')),
 (10314, 58, Decimal('10.6000'), 30, Decimal('318.0000')),
 (10314, 62, Decimal('39.4000'), 25, Decimal('985.0000')),
 (10315, 34, Decimal('11.2000'), 14, Decimal('156.8000')),
 (10315, 70, Decimal('12.0000'), 30, Decimal('360.0000')),
 (10316, 41, Decimal('7.7000'), 10, Decimal('77.0000')),
 (10316, 62, Decimal('39.4000'), 70, Decimal('2758.0000')),
 (10317, 1, Decimal('14.4000'), 20, Decimal('288.0000')),
 (10318, 41, Decimal('7.7000'), 20, Decimal('154.0000')),
 (10318, 76, Decimal('14.4000'), 6, Decimal('86.4000')),
 (10319, 17, Decimal('31.2000'), 8, Decimal('249.6000')),
 (10319, 28, Decimal('36.4000'), 14, Decimal('509.6000')),
 (10319, 76, Decimal('14.4000'), 30, Decimal('432.0000')),
 (10320, 71, Decimal('17.2000'), 30, Decimal('516.0000')),
 (10321, 35, Decimal('14.4000'), 10, Decimal('144.0000')),
 (10322, 52, Decimal('5.6000'), 20, Decimal('112.0000')),
 (10323, 15, Decimal('12.4000'), 5, Decimal('62.0000')),
 (10323, 25, Decimal('11.2000'), 4, Decimal('44.8000')),
 (10323, 39, Decimal('14.4000'), 4, Decimal('57.6000')),
 (10324, 16, Decimal('13.9000'), 21, Decimal('291.9000')),
 (10324, 35, Decimal('14.4000'), 70, Decimal('1008.0000')),
 (10324, 46, Decimal('9.6000'), 30, Decimal('288.0000')),
 (10324, 59, Decimal('44.0000'), 40, Decimal('1760.0000')),
 (10324, 63, Decimal('35.1000'), 80, Decimal('2808.0000')),
 (10325, 6, Decimal('20.0000'), 6, Decimal('120.0000')),
 (10325, 13, Decimal('4.8000'), 12, Decimal('57.6000')),
 (10325, 14, Decimal('18.6000'), 9, Decimal('167.4000')),
 (10325, 31, Decimal('10.0000'), 4, Decimal('40.0000')),
 (10325, 72, Decimal('27.8000'), 40, Decimal('1112.0000')),
 (10326, 4, Decimal('17.6000'), 24, Decimal('422.4000')),
 (10326, 57, Decimal('15.6000'), 16, Decimal('249.6000')),
 (10326, 75, Decimal('6.2000'), 50, Decimal('310.0000')),
 (10327, 2, Decimal('15.2000'), 25, Decimal('380.0000')),
 (10327, 11, Decimal('16.8000'), 50, Decimal('840.0000')),
 (10327, 30, Decimal('20.7000'), 35, Decimal('724.5000')),
 (10327, 58, Decimal('10.6000'), 30, Decimal('318.0000')),
 (10328, 59, Decimal('44.0000'), 9, Decimal('396.0000')),
 (10328, 65, Decimal('16.8000'), 40, Decimal('672.0000')),
 (10328, 68, Decimal('10.0000'), 10, Decimal('100.0000')),
 (10329, 19, Decimal('7.3000'), 10, Decimal('73.0000')),
 (10329, 30, Decimal('20.7000'), 8, Decimal('165.6000')),
 (10329, 38, Decimal('210.8000'), 20, Decimal('4216.0000')),
 (10329, 56, Decimal('30.4000'), 12, Decimal('364.8000')),
 (10330, 26, Decimal('24.9000'), 50, Decimal('1245.0000')),
 (10330, 72, Decimal('27.8000'), 25, Decimal('695.0000')),
 (10331, 54, Decimal('5.9000'), 15, Decimal('88.5000')),
 (10332, 18, Decimal('50.0000'), 40, Decimal('2000.0000')),
 (10332, 42, Decimal('11.2000'), 10, Decimal('112.0000')),
 (10332, 47, Decimal('7.6000'), 16, Decimal('121.6000')),
 (10333, 14, Decimal('18.6000'), 10, Decimal('186.0000')),
 (10333, 21, Decimal('8.0000'), 10, Decimal('80.0000')),
 (10333, 71, Decimal('17.2000'), 40, Decimal('688.0000')),
 (10334, 52, Decimal('5.6000'), 8, Decimal('44.8000')),
 (10334, 68, Decimal('10.0000'), 10, Decimal('100.0000')),
 (10335, 2, Decimal('15.2000'), 7, Decimal('106.4000')),
 (10335, 31, Decimal('10.0000'), 25, Decimal('250.0000')),
 (10335, 32, Decimal('25.6000'), 6, Decimal('153.6000')),
 (10335, 51, Decimal('42.4000'), 48, Decimal('2035.2000')),
 (10336, 4, Decimal('17.6000'), 18, Decimal('316.8000')),
 (10337, 23, Decimal('7.2000'), 40, Decimal('288.0000')),
 (10337, 26, Decimal('24.9000'), 24, Decimal('597.6000')),
 (10337, 36, Decimal('15.2000'), 20, Decimal('304.0000')),
 (10337, 37, Decimal('20.8000'), 28, Decimal('582.4000')),
 (10337, 72, Decimal('27.8000'), 25, Decimal('695.0000')),
 (10338, 17, Decimal('31.2000'), 20, Decimal('624.0000')),
 (10338, 30, Decimal('20.7000'), 15, Decimal('310.5000')),
 (10339, 4, Decimal('17.6000'), 10, Decimal('176.0000')),
 (10339, 17, Decimal('31.2000'), 70, Decimal('2184.0000')),
 (10339, 62, Decimal('39.4000'), 28, Decimal('1103.2000')),
 (10340, 18, Decimal('50.0000'), 20, Decimal('1000.0000')),
 (10340, 41, Decimal('7.7000'), 12, Decimal('92.4000')),
 (10340, 43, Decimal('36.8000'), 40, Decimal('1472.0000')),
 (10341, 33, Decimal('2.0000'), 8, Decimal('16.0000')),
 (10341, 59, Decimal('44.0000'), 9, Decimal('396.0000')),
 (10342, 2, Decimal('15.2000'), 24, Decimal('364.8000')),
 (10342, 31, Decimal('10.0000'), 56, Decimal('560.0000')),
 (10342, 36, Decimal('15.2000'), 40, Decimal('608.0000')),
 (10342, 55, Decimal('19.2000'), 40, Decimal('768.0000')),
 (10343, 64, Decimal('26.6000'), 50, Decimal('1330.0000')),
 (10343, 68, Decimal('10.0000'), 4, Decimal('40.0000')),
 (10343, 76, Decimal('14.4000'), 15, Decimal('216.0000')),
 (10344, 4, Decimal('17.6000'), 35, Decimal('616.0000')),
 (10344, 8, Decimal('32.0000'), 70, Decimal('2240.0000')),
 (10345, 8, Decimal('32.0000'), 70, Decimal('2240.0000')),
 (10345, 19, Decimal('7.3000'), 80, Decimal('584.0000')),
 (10345, 42, Decimal('11.2000'), 9, Decimal('100.8000')),
 (10346, 17, Decimal('31.2000'), 36, Decimal('1123.2000')),
 (10346, 56, Decimal('30.4000'), 20, Decimal('608.0000')),
 (10347, 25, Decimal('11.2000'), 10, Decimal('112.0000')),
 (10347, 39, Decimal('14.4000'), 50, Decimal('720.0000')),
 (10347, 40, Decimal('14.7000'), 4, Decimal('58.8000')),
 (10347, 75, Decimal('6.2000'), 6, Decimal('37.2000')),
 (10348, 1, Decimal('14.4000'), 15, Decimal('216.0000')),
 (10348, 23, Decimal('7.2000'), 25, Decimal('180.0000')),
 (10349, 54, Decimal('5.9000'), 24, Decimal('141.6000')),
 (10350, 50, Decimal('13.0000'), 15, Decimal('195.0000')),
 (10350, 69, Decimal('28.8000'), 18, Decimal('518.4000')),
 (10351, 38, Decimal('210.8000'), 20, Decimal('4216.0000')),
 (10351, 41, Decimal('7.7000'), 13, Decimal('100.1000')),
 (10351, 44, Decimal('15.5000'), 77, Decimal('1193.5000')),
 (10351, 65, Decimal('16.8000'), 10, Decimal('168.0000')),
 (10352, 24, Decimal('3.6000'), 10, Decimal('36.0000')),
 (10352, 54, Decimal('5.9000'), 20, Decimal('118.0000')),
 (10353, 11, Decimal('16.8000'), 12, Decimal('201.6000')),
 (10353, 38, Decimal('210.8000'), 50, Decimal('10540.0000')),
 (10354, 1, Decimal('14.4000'), 12, Decimal('172.8000')),
 (10354, 29, Decimal('99.0000'), 4, Decimal('396.0000')),
 (10355, 24, Decimal('3.6000'), 25, Decimal('90.0000')),
 (10355, 57, Decimal('15.6000'), 25, Decimal('390.0000')),
 (10356, 31, Decimal('10.0000'), 30, Decimal('300.0000')),
 (10356, 55, Decimal('19.2000'), 12, Decimal('230.4000')),
 (10356, 69, Decimal('28.8000'), 20, Decimal('576.0000')),
 (10357, 10, Decimal('24.8000'), 30, Decimal('744.0000')),
 (10357, 26, Decimal('24.9000'), 16, Decimal('398.4000')),
 (10357, 60, Decimal('27.2000'), 8, Decimal('217.6000')),
 (10358, 24, Decimal('3.6000'), 10, Decimal('36.0000')),
 (10358, 34, Decimal('11.2000'), 10, Decimal('112.0000')),
 (10358, 36, Decimal('15.2000'), 20, Decimal('304.0000')),
 (10359, 16, Decimal('13.9000'), 56, Decimal('778.4000')),
 (10359, 31, Decimal('10.0000'), 70, Decimal('700.0000')),
 (10359, 60, Decimal('27.2000'), 80, Decimal('2176.0000')),
 (10360, 28, Decimal('36.4000'), 30, Decimal('1092.0000')),
 (10360, 29, Decimal('99.0000'), 35, Decimal('3465.0000')),
 (10360, 38, Decimal('210.8000'), 10, Decimal('2108.0000')),
 (10360, 49, Decimal('16.0000'), 35, Decimal('560.0000')),
 (10360, 54, Decimal('5.9000'), 28, Decimal('165.2000')),
 (10361, 39, Decimal('14.4000'), 54, Decimal('777.6000')),
 (10361, 60, Decimal('27.2000'), 55, Decimal('1496.0000')),
 (10362, 25, Decimal('11.2000'), 50, Decimal('560.0000')),
 (10362, 51, Decimal('42.4000'), 20, Decimal('848.0000')),
 (10362, 54, Decimal('5.9000'), 24, Decimal('141.6000')),
 (10363, 31, Decimal('10.0000'), 20, Decimal('200.0000')),
 (10363, 75, Decimal('6.2000'), 12, Decimal('74.4000')),
 (10363, 76, Decimal('14.4000'), 12, Decimal('172.8000')),
 (10364, 69, Decimal('28.8000'), 30, Decimal('864.0000')),
 (10364, 71, Decimal('17.2000'), 5, Decimal('86.0000')),
 (10365, 11, Decimal('16.8000'), 24, Decimal('403.2000')),
 (10366, 65, Decimal('16.8000'), 5, Decimal('84.0000')),
 (10366, 77, Decimal('10.4000'), 5, Decimal('52.0000')),
 (10367, 34, Decimal('11.2000'), 36, Decimal('403.2000')),
 (10367, 54, Decimal('5.9000'), 18, Decimal('106.2000')),
 (10367, 65, Decimal('16.8000'), 15, Decimal('252.0000')),
 (10367, 77, Decimal('10.4000'), 7, Decimal('72.8000')),
 (10368, 21, Decimal('8.0000'), 5, Decimal('40.0000')),
 (10368, 28, Decimal('36.4000'), 13, Decimal('473.2000')),
 (10368, 57, Decimal('15.6000'), 25, Decimal('390.0000')),
 (10368, 64, Decimal('26.6000'), 35, Decimal('931.0000')),
 (10369, 29, Decimal('99.0000'), 20, Decimal('1980.0000')),
 (10369, 56, Decimal('30.4000'), 18, Decimal('547.2000')),
 (10370, 1, Decimal('14.4000'), 15, Decimal('216.0000')),
 (10370, 64, Decimal('26.6000'), 30, Decimal('798.0000')),
 (10370, 74, Decimal('8.0000'), 20, Decimal('160.0000')),
 (10371, 36, Decimal('15.2000'), 6, Decimal('91.2000')),
 (10372, 20, Decimal('64.8000'), 12, Decimal('777.6000')),
 (10372, 38, Decimal('210.8000'), 40, Decimal('8432.0000')),
 (10372, 60, Decimal('27.2000'), 70, Decimal('1904.0000')),
 (10372, 72, Decimal('27.8000'), 42, Decimal('1167.6000')),
 (10373, 58, Decimal('10.6000'), 80, Decimal('848.0000')),
 (10373, 71, Decimal('17.2000'), 50, Decimal('860.0000')),
 (10374, 31, Decimal('10.0000'), 30, Decimal('300.0000')),
 (10374, 58, Decimal('10.6000'), 15, Decimal('159.0000')),
 (10375, 14, Decimal('18.6000'), 15, Decimal('279.0000')),
 (10375, 54, Decimal('5.9000'), 10, Decimal('59.0000')),
 (10376, 31, Decimal('10.0000'), 42, Decimal('420.0000')),

## M14. Sample counting

In [63]:
%%sql
SELECT TotalCustomers = COUNT(*)
FROM Customers

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(91,)]

## M15. Find the first event

In [64]:
%%sql
SELECT FirstOrder = MIN(OrderDate)
FROM Orders

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(datetime.datetime(1996, 7, 4, 0, 0),)]

## M16. Subsetting
Show the list of countries where there are customers

In [65]:
%%sql 
SELECT Country
FROM Customers
GROUP BY Country

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Argentina',),
 ('Austria',),
 ('Belgium',),
 ('Brazil',),
 ('Canada',),
 ('Denmark',),
 ('Finland',),
 ('France',),
 ('Germany',),
 ('Ireland',),
 ('Italy',),
 ('Mexico',),
 ('Norway',),
 ('Poland',),
 ('Portugal',),
 ('Spain',),
 ('Sweden',),
 ('Switzerland',),
 ('UK',),
 ('USA',),
 ('Venezuela',)]

## M17. Counting by group

In [66]:
%%sql
SELECT ContactTitle, TotalContactTitle = COUNT(*)
FROM Customers
GROUP BY ContactTitle
ORDER BY COUNT(*) DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Owner', 17),
 ('Sales Representative', 17),
 ('Marketing Manager', 12),
 ('Sales Manager', 11),
 ('Accounting Manager', 10),
 ('Sales Associate', 7),
 ('Marketing Assistant', 6),
 ('Sales Agent', 5),
 ('Assistant Sales Agent', 2),
 ('Order Administrator', 2),
 ('Assistant Sales Representative', 1),
 ('Owner/Marketing Assistant', 1)]

## M18. Data merging with aliased tables

In [11]:
%%sql
SELECT ProductID, ProductName, Supplier = CompanyName
FROM Products P -- Aliased table
JOIN Suppliers S -- Aliased table
ON P.SupplierID = S.SupplierID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 'Chai', 'Exotic Liquids'),
 (2, 'Chang', 'Exotic Liquids'),
 (3, 'Aniseed Syrup', 'Exotic Liquids'),
 (4, "Chef Anton's Cajun Seasoning", 'New Orleans Cajun Delights'),
 (5, "Chef Anton's Gumbo Mix", 'New Orleans Cajun Delights'),
 (6, "Grandma's Boysenberry Spread", "Grandma Kelly's Homestead"),
 (7, "Uncle Bob's Organic Dried Pears", "Grandma Kelly's Homestead"),
 (8, 'Northwoods Cranberry Sauce', "Grandma Kelly's Homestead"),
 (9, 'Mishi Kobe Niku', 'Tokyo Traders'),
 (10, 'Ikura', 'Tokyo Traders'),
 (11, 'Queso Cabrales', "Cooperativa de Quesos 'Las Cabras'"),
 (12, 'Queso Manchego La Pastora', "Cooperativa de Quesos 'Las Cabras'"),
 (13, 'Konbu', "Mayumi's"),
 (14, 'Tofu', "Mayumi's"),
 (15, 'Genen Shouyu', "Mayumi's"),
 (16, 'Pavlova', 'Pavlova, Ltd.'),
 (17, 'Alice Mutton', 'Pavlova, Ltd.'),
 (18, 'Carnarvon Tigers', 'Pavlova, Ltd.'),
 (19, 'Teatime Chocolate Biscuits', 'Specialty Biscuits, Ltd.'),
 (20, "Sir Rodney's Marmalade", 'Specialty Biscuits, Ltd.'),
 (21, "Sir Rodney's Scones", 'Specialty Biscuits, Ltd.'),
 (22, "Gustaf's Knäckebröd", 'PB Knäckebröd AB'),
 (23, 'Tunnbröd', 'PB Knäckebröd AB'),
 (24, 'Guaraná Fantástica', 'Refrescos Americanas LTDA'),
 (25, 'NuNuCa Nuß-Nougat-Creme', 'Heli Süßwaren GmbH & Co. KG'),
 (26, 'Gumbär Gummibärchen', 'Heli Süßwaren GmbH & Co. KG'),
 (27, 'Schoggi Schokolade', 'Heli Süßwaren GmbH & Co. KG'),
 (28, 'Rössle Sauerkraut', 'Plutzer Lebensmittelgroßmärkte AG'),
 (29, 'Thüringer Rostbratwurst', 'Plutzer Lebensmittelgroßmärkte AG'),
 (30, 'Nord-Ost Matjeshering', 'Nord-Ost-Fisch Handelsgesellschaft mbH'),
 (31, 'Gorgonzola Telino', 'Formaggi Fortini s.r.l.'),
 (32, 'Mascarpone Fabioli', 'Formaggi Fortini s.r.l.'),
 (33, 'Geitost', 'Norske Meierier'),
 (34, 'Sasquatch Ale', 'Bigfoot Breweries'),
 (35, 'Steeleye Stout', 'Bigfoot Breweries'),
 (36, 'Inlagd Sill', 'Svensk Sjöföda AB'),
 (37, 'Gravad lax', 'Svensk Sjöföda AB'),
 (38, 'Côte de Blaye', 'Aux joyeux ecclésiastiques'),
 (39, 'Chartreuse verte', 'Aux joyeux ecclésiastiques'),
 (40, 'Boston Crab Meat', 'New England Seafood Cannery'),
 (41, "Jack's New England Clam Chowder", 'New England Seafood Cannery'),
 (42, 'Singaporean Hokkien Fried Mee', 'Leka Trading'),
 (43, 'Ipoh Coffee', 'Leka Trading'),
 (44, 'Gula Malacca', 'Leka Trading'),
 (45, 'Rogede sild', 'Lyngbysild'),
 (46, 'Spegesild', 'Lyngbysild'),
 (47, 'Zaanse koeken', 'Zaanse Snoepfabriek'),
 (48, 'Chocolade', 'Zaanse Snoepfabriek'),
 (49, 'Maxilaku', 'Karkki Oy'),
 (50, 'Valkoinen suklaa', 'Karkki Oy'),
 (51, 'Manjimup Dried Apples', "G'day, Mate"),
 (52, 'Filo Mix', "G'day, Mate"),
 (53, 'Perth Pasties', "G'day, Mate"),
 (54, 'Tourtière', 'Ma Maison'),
 (55, 'Pâté chinois', 'Ma Maison'),
 (56, 'Gnocchi di nonna Alice', 'Pasta Buttini s.r.l.'),
 (57, 'Ravioli Angelo', 'Pasta Buttini s.r.l.'),
 (58, 'Escargots de Bourgogne', 'Escargots Nouveaux'),
 (59, 'Raclette Courdavault', 'Gai pâturage'),
 (60, 'Camembert Pierrot', 'Gai pâturage'),
 (61, "Sirop d'érable", "Forêts d'érables"),
 (62, 'Tarte au sucre', "Forêts d'érables"),
 (63, 'Vegie-spread', 'Pavlova, Ltd.'),
 (64, 'Wimmers gute Semmelknödel', 'Plutzer Lebensmittelgroßmärkte AG'),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 'New Orleans Cajun Delights'),
 (66, 'Louisiana Hot Spiced Okra', 'New Orleans Cajun Delights'),
 (67, 'Laughing Lumberjack Lager', 'Bigfoot Breweries'),
 (68, 'Scottish Longbreads', 'Specialty Biscuits, Ltd.'),
 (69, 'Gudbrandsdalsost', 'Norske Meierier'),
 (70, 'Outback Lager', 'Pavlova, Ltd.'),
 (71, 'Flotemysost', 'Norske Meierier'),
 (72, 'Mozzarella di Giovanni', 'Formaggi Fortini s.r.l.'),
 (73, 'Röd Kaviar', 'Svensk Sjöföda AB'),
 (74, 'Longlife Tofu', 'Tokyo Traders'),
 (75, 'Rhönbräu Klosterbier', 'Plutzer Lebensmittelgroßmärkte AG'),
 (76, 'Lakkalikööri', 'Karkki Oy'),
 (77, 'Original Frankfurter grüne Soße', 'Plutzer Lebensmittelgroßmärkte AG')]

## M19. Data chopping, Table targeting

In [71]:
%%sql
SELECT OrderID, OrderDate = CONVERT(DATE, OrderDate), Shipper = CompanyName
FROM Orders
JOIN Shippers
ON Shippers.ShipperID = Orders.ShipVia
WHERE OrderID < 10300
ORDER BY OrderID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10248, datetime.date(1996, 7, 4), 'Federal Shipping'),
 (10249, datetime.date(1996, 7, 5), 'Speedy Express'),
 (10250, datetime.date(1996, 7, 8), 'United Package'),
 (10251, datetime.date(1996, 7, 8), 'Speedy Express'),
 (10252, datetime.date(1996, 7, 9), 'United Package'),
 (10253, datetime.date(1996, 7, 10), 'United Package'),
 (10254, datetime.date(1996, 7, 11), 'United Package'),
 (10255, datetime.date(1996, 7, 12), 'Federal Shipping'),
 (10256, datetime.date(1996, 7, 15), 'United Package'),
 (10257, datetime.date(1996, 7, 16), 'Federal Shipping'),
 (10258, datetime.date(1996, 7, 17), 'Speedy Express'),
 (10259, datetime.date(1996, 7, 18), 'Federal Shipping'),
 (10260, datetime.date(1996, 7, 19), 'Speedy Express'),
 (10261, datetime.date(1996, 7, 19), 'United Package'),
 (10262, datetime.date(1996, 7, 22), 'Federal Shipping'),
 (10263, datetime.date(1996, 7, 23), 'Federal Shipping'),
 (10264, datetime.date(1996, 7, 24), 'Federal Shipping'),
 (10265, datetime.date(1996, 7, 25), 'Speedy Express'),
 (10266, datetime.date(1996, 7, 26), 'Federal Shipping'),
 (10267, datetime.date(1996, 7, 29), 'Speedy Express'),
 (10268, datetime.date(1996, 7, 30), 'Federal Shipping'),
 (10269, datetime.date(1996, 7, 31), 'Speedy Express'),
 (10270, datetime.date(1996, 8, 1), 'Speedy Express'),
 (10271, datetime.date(1996, 8, 1), 'United Package'),
 (10272, datetime.date(1996, 8, 2), 'United Package'),
 (10273, datetime.date(1996, 8, 5), 'Federal Shipping'),
 (10274, datetime.date(1996, 8, 6), 'Speedy Express'),
 (10275, datetime.date(1996, 8, 7), 'Speedy Express'),
 (10276, datetime.date(1996, 8, 8), 'Federal Shipping'),
 (10277, datetime.date(1996, 8, 9), 'Federal Shipping'),
 (10278, datetime.date(1996, 8, 12), 'United Package'),
 (10279, datetime.date(1996, 8, 13), 'United Package'),
 (10280, datetime.date(1996, 8, 14), 'Speedy Express'),
 (10281, datetime.date(1996, 8, 14), 'Speedy Express'),
 (10282, datetime.date(1996, 8, 15), 'Speedy Express'),
 (10283, datetime.date(1996, 8, 16), 'Federal Shipping'),
 (10284, datetime.date(1996, 8, 19), 'Speedy Express'),
 (10285, datetime.date(1996, 8, 20), 'United Package'),
 (10286, datetime.date(1996, 8, 21), 'Federal Shipping'),
 (10287, datetime.date(1996, 8, 22), 'Federal Shipping'),
 (10288, datetime.date(1996, 8, 23), 'Speedy Express'),
 (10289, datetime.date(1996, 8, 26), 'Federal Shipping'),
 (10290, datetime.date(1996, 8, 27), 'Speedy Express'),
 (10291, datetime.date(1996, 8, 27), 'United Package'),
 (10292, datetime.date(1996, 8, 28), 'United Package'),
 (10293, datetime.date(1996, 8, 29), 'Federal Shipping'),
 (10294, datetime.date(1996, 8, 30), 'United Package'),
 (10295, datetime.date(1996, 9, 2), 'United Package'),
 (10296, datetime.date(1996, 9, 3), 'Speedy Express'),
 (10297, datetime.date(1996, 9, 4), 'United Package'),
 (10298, datetime.date(1996, 9, 5), 'United Package'),
 (10299, datetime.date(1996, 9, 6), 'United Package')]

In [12]:
%%sql
SELECT OrderID, OrderDate = CONVERT(DATE, OrderDate), Shipper = S.CompanyName
FROM Orders O
JOIN Shippers S
ON S.ShipperID = O.ShipVia
WHERE O.OrderID < 10300
ORDER BY O.OrderID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10248, datetime.date(1996, 7, 4), 'Federal Shipping'),
 (10249, datetime.date(1996, 7, 5), 'Speedy Express'),
 (10250, datetime.date(1996, 7, 8), 'United Package'),
 (10251, datetime.date(1996, 7, 8), 'Speedy Express'),
 (10252, datetime.date(1996, 7, 9), 'United Package'),
 (10253, datetime.date(1996, 7, 10), 'United Package'),
 (10254, datetime.date(1996, 7, 11), 'United Package'),
 (10255, datetime.date(1996, 7, 12), 'Federal Shipping'),
 (10256, datetime.date(1996, 7, 15), 'United Package'),
 (10257, datetime.date(1996, 7, 16), 'Federal Shipping'),
 (10258, datetime.date(1996, 7, 17), 'Speedy Express'),
 (10259, datetime.date(1996, 7, 18), 'Federal Shipping'),
 (10260, datetime.date(1996, 7, 19), 'Speedy Express'),
 (10261, datetime.date(1996, 7, 19), 'United Package'),
 (10262, datetime.date(1996, 7, 22), 'Federal Shipping'),
 (10263, datetime.date(1996, 7, 23), 'Federal Shipping'),
 (10264, datetime.date(1996, 7, 24), 'Federal Shipping'),
 (10265, datetime.date(1996, 7, 25), 'Speedy Express'),
 (10266, datetime.date(1996, 7, 26), 'Federal Shipping'),
 (10267, datetime.date(1996, 7, 29), 'Speedy Express'),
 (10268, datetime.date(1996, 7, 30), 'Federal Shipping'),
 (10269, datetime.date(1996, 7, 31), 'Speedy Express'),
 (10270, datetime.date(1996, 8, 1), 'Speedy Express'),
 (10271, datetime.date(1996, 8, 1), 'United Package'),
 (10272, datetime.date(1996, 8, 2), 'United Package'),
 (10273, datetime.date(1996, 8, 5), 'Federal Shipping'),
 (10274, datetime.date(1996, 8, 6), 'Speedy Express'),
 (10275, datetime.date(1996, 8, 7), 'Speedy Express'),
 (10276, datetime.date(1996, 8, 8), 'Federal Shipping'),
 (10277, datetime.date(1996, 8, 9), 'Federal Shipping'),
 (10278, datetime.date(1996, 8, 12), 'United Package'),
 (10279, datetime.date(1996, 8, 13), 'United Package'),
 (10280, datetime.date(1996, 8, 14), 'Speedy Express'),
 (10281, datetime.date(1996, 8, 14), 'Speedy Express'),
 (10282, datetime.date(1996, 8, 15), 'Speedy Express'),
 (10283, datetime.date(1996, 8, 16), 'Federal Shipping'),
 (10284, datetime.date(1996, 8, 19), 'Speedy Express'),
 (10285, datetime.date(1996, 8, 20), 'United Package'),
 (10286, datetime.date(1996, 8, 21), 'Federal Shipping'),
 (10287, datetime.date(1996, 8, 22), 'Federal Shipping'),
 (10288, datetime.date(1996, 8, 23), 'Speedy Express'),
 (10289, datetime.date(1996, 8, 26), 'Federal Shipping'),
 (10290, datetime.date(1996, 8, 27), 'Speedy Express'),
 (10291, datetime.date(1996, 8, 27), 'United Package'),
 (10292, datetime.date(1996, 8, 28), 'United Package'),
 (10293, datetime.date(1996, 8, 29), 'Federal Shipping'),
 (10294, datetime.date(1996, 8, 30), 'United Package'),
 (10295, datetime.date(1996, 9, 2), 'United Package'),
 (10296, datetime.date(1996, 9, 3), 'Speedy Express'),
 (10297, datetime.date(1996, 9, 4), 'United Package'),
 (10298, datetime.date(1996, 9, 5), 'United Package'),
 (10299, datetime.date(1996, 9, 6), 'United Package')]

A case where table aliasing is a necessity.Otherwise, the system fails to identify from which table Column SupplierID comes.

In [13]:
%%sql 
SELECT ProductID, ProductName, Supplier = CompanyName, Suppliers.SupplierID 
FROM Products
JOIN Suppliers
ON Products.SupplierID = Suppliers.SupplierID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 'Chai', 'Exotic Liquids', 1),
 (2, 'Chang', 'Exotic Liquids', 1),
 (3, 'Aniseed Syrup', 'Exotic Liquids', 1),
 (4, "Chef Anton's Cajun Seasoning", 'New Orleans Cajun Delights', 2),
 (5, "Chef Anton's Gumbo Mix", 'New Orleans Cajun Delights', 2),
 (6, "Grandma's Boysenberry Spread", "Grandma Kelly's Homestead", 3),
 (7, "Uncle Bob's Organic Dried Pears", "Grandma Kelly's Homestead", 3),
 (8, 'Northwoods Cranberry Sauce', "Grandma Kelly's Homestead", 3),
 (9, 'Mishi Kobe Niku', 'Tokyo Traders', 4),
 (10, 'Ikura', 'Tokyo Traders', 4),
 (11, 'Queso Cabrales', "Cooperativa de Quesos 'Las Cabras'", 5),
 (12, 'Queso Manchego La Pastora', "Cooperativa de Quesos 'Las Cabras'", 5),
 (13, 'Konbu', "Mayumi's", 6),
 (14, 'Tofu', "Mayumi's", 6),
 (15, 'Genen Shouyu', "Mayumi's", 6),
 (16, 'Pavlova', 'Pavlova, Ltd.', 7),
 (17, 'Alice Mutton', 'Pavlova, Ltd.', 7),
 (18, 'Carnarvon Tigers', 'Pavlova, Ltd.', 7),
 (19, 'Teatime Chocolate Biscuits', 'Specialty Biscuits, Ltd.', 8),
 (20, "Sir Rodney's Marmalade", 'Specialty Biscuits, Ltd.', 8),
 (21, "Sir Rodney's Scones", 'Specialty Biscuits, Ltd.', 8),
 (22, "Gustaf's Knäckebröd", 'PB Knäckebröd AB', 9),
 (23, 'Tunnbröd', 'PB Knäckebröd AB', 9),
 (24, 'Guaraná Fantástica', 'Refrescos Americanas LTDA', 10),
 (25, 'NuNuCa Nuß-Nougat-Creme', 'Heli Süßwaren GmbH & Co. KG', 11),
 (26, 'Gumbär Gummibärchen', 'Heli Süßwaren GmbH & Co. KG', 11),
 (27, 'Schoggi Schokolade', 'Heli Süßwaren GmbH & Co. KG', 11),
 (28, 'Rössle Sauerkraut', 'Plutzer Lebensmittelgroßmärkte AG', 12),
 (29, 'Thüringer Rostbratwurst', 'Plutzer Lebensmittelgroßmärkte AG', 12),
 (30, 'Nord-Ost Matjeshering', 'Nord-Ost-Fisch Handelsgesellschaft mbH', 13),
 (31, 'Gorgonzola Telino', 'Formaggi Fortini s.r.l.', 14),
 (32, 'Mascarpone Fabioli', 'Formaggi Fortini s.r.l.', 14),
 (33, 'Geitost', 'Norske Meierier', 15),
 (34, 'Sasquatch Ale', 'Bigfoot Breweries', 16),
 (35, 'Steeleye Stout', 'Bigfoot Breweries', 16),
 (36, 'Inlagd Sill', 'Svensk Sjöföda AB', 17),
 (37, 'Gravad lax', 'Svensk Sjöföda AB', 17),
 (38, 'Côte de Blaye', 'Aux joyeux ecclésiastiques', 18),
 (39, 'Chartreuse verte', 'Aux joyeux ecclésiastiques', 18),
 (40, 'Boston Crab Meat', 'New England Seafood Cannery', 19),
 (41, "Jack's New England Clam Chowder", 'New England Seafood Cannery', 19),
 (42, 'Singaporean Hokkien Fried Mee', 'Leka Trading', 20),
 (43, 'Ipoh Coffee', 'Leka Trading', 20),
 (44, 'Gula Malacca', 'Leka Trading', 20),
 (45, 'Rogede sild', 'Lyngbysild', 21),
 (46, 'Spegesild', 'Lyngbysild', 21),
 (47, 'Zaanse koeken', 'Zaanse Snoepfabriek', 22),
 (48, 'Chocolade', 'Zaanse Snoepfabriek', 22),
 (49, 'Maxilaku', 'Karkki Oy', 23),
 (50, 'Valkoinen suklaa', 'Karkki Oy', 23),
 (51, 'Manjimup Dried Apples', "G'day, Mate", 24),
 (52, 'Filo Mix', "G'day, Mate", 24),
 (53, 'Perth Pasties', "G'day, Mate", 24),
 (54, 'Tourtière', 'Ma Maison', 25),
 (55, 'Pâté chinois', 'Ma Maison', 25),
 (56, 'Gnocchi di nonna Alice', 'Pasta Buttini s.r.l.', 26),
 (57, 'Ravioli Angelo', 'Pasta Buttini s.r.l.', 26),
 (58, 'Escargots de Bourgogne', 'Escargots Nouveaux', 27),
 (59, 'Raclette Courdavault', 'Gai pâturage', 28),
 (60, 'Camembert Pierrot', 'Gai pâturage', 28),
 (61, "Sirop d'érable", "Forêts d'érables", 29),
 (62, 'Tarte au sucre', "Forêts d'érables", 29),
 (63, 'Vegie-spread', 'Pavlova, Ltd.', 7),
 (64, 'Wimmers gute Semmelknödel', 'Plutzer Lebensmittelgroßmärkte AG', 12),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 'New Orleans Cajun Delights', 2),
 (66, 'Louisiana Hot Spiced Okra', 'New Orleans Cajun Delights', 2),
 (67, 'Laughing Lumberjack Lager', 'Bigfoot Breweries', 16),
 (68, 'Scottish Longbreads', 'Specialty Biscuits, Ltd.', 8),
 (69, 'Gudbrandsdalsost', 'Norske Meierier', 15),
 (70, 'Outback Lager', 'Pavlova, Ltd.', 7),
 (71, 'Flotemysost', 'Norske Meierier', 15),
 (72, 'Mozzarella di Giovanni', 'Formaggi Fortini s.r.l.', 14),
 (73, 'Röd Kaviar', 'Svensk Sjöföda AB', 17),
 (74, 'Longlife Tofu', 'Tokyo Traders', 4),
 (75, 'Rhönbräu Klosterbier', 'Plutzer Lebensmittelgroßmärkte AG', 12),
 (76, 'Lakkalikööri', 'Karkki Oy', 23),
 (77, 'Original Frankfurter grüne Soße', 'Plutzer Lebensmittelgroßmärkte AG', 12)]

## M20. Aggregate functions

In [73]:
%%sql
SELECT CategoryName, TotalProducts = COUNT(*)
FROM Products
JOIN Categories
ON Products.CategoryID = Categories.CategoryID
GROUP BY CategoryName
ORDER BY COUNT(*) DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Confections', 13),
 ('lol', 12),
 ('Condiments', 12),
 ('Seafood', 12),
 ('Dairy Products', 10),
 ('Grains/Cereals', 7),
 ('Meat/Poultry', 6),
 ('Produce', 5)]

## M21. Groupping

In [74]:
%%sql
SELECT Country, City, TotalCustomer = COUNT(*)
FROM Customers
GROUP BY Country, City
ORDER BY COUNT(*) DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('UK', 'London', 6),
 ('Mexico', 'México D.F.', 5),
 ('Brazil', 'Sao Paulo', 4),
 ('Brazil', 'Rio de Janeiro', 3),
 ('Spain', 'Madrid', 3),
 ('Argentina', 'Buenos Aires', 3),
 ('France', 'Paris', 2),
 ('USA', 'Portland', 2),
 ('France', 'Nantes', 2),
 ('Portugal', 'Lisboa', 2),
 ('Finland', 'Oulu', 1),
 ('Italy', 'Reggio Emilia', 1),
 ('France', 'Reims', 1),
 ('Brazil', 'Resende', 1),
 ('Austria', 'Salzburg', 1),
 ('Venezuela', 'San Cristóbal', 1),
 ('USA', 'San Francisco', 1),
 ('USA', 'Seattle', 1),
 ('Spain', 'Sevilla', 1),
 ('Norway', 'Stavern', 1),
 ('France', 'Strasbourg', 1),
 ('Germany', 'Stuttgart', 1),
 ('Italy', 'Torino', 1),
 ('France', 'Toulouse', 1),
 ('Canada', 'Tsawassen', 1),
 ('Canada', 'Vancouver', 1),
 ('France', 'Versailles', 1),
 ('USA', 'Walla Walla', 1),
 ('Poland', 'Warszawa', 1),
 ('USA', 'Butte', 1),
 ('Brazil', 'Campinas', 1),
 ('Venezuela', 'Caracas', 1),
 ('Belgium', 'Charleroi', 1),
 ('Ireland', 'Cork', 1),
 ('UK', 'Cowes', 1),
 ('Germany', 'Cunewalde', 1),
 ('USA', 'Elgin', 1),
 ('USA', 'Eugene', 1),
 ('Germany', 'Frankfurt a.M.', 1),
 ('Switzerland', 'Genève', 1),
 ('Austria', 'Graz', 1),
 ('Finland', 'Helsinki', 1),
 ('Venezuela', 'I. de Margarita', 1),
 ('USA', 'Kirkland', 1),
 ('Denmark', 'Kobenhavn', 1),
 ('Germany', 'Köln', 1),
 ('USA', 'Lander', 1),
 ('Germany', 'Leipzig', 1),
 ('France', 'Lille', 1),
 ('Germany', 'Mannheim', 1),
 ('France', 'Marseille', 1),
 ('Sweden', 'Luleå', 1),
 ('France', 'Lyon', 1),
 ('Canada', 'Montréal', 1),
 ('Germany', 'München', 1),
 ('Germany', 'Münster', 1),
 ('Germany', 'Aachen', 1),
 ('USA', 'Albuquerque', 1),
 ('USA', 'Anchorage', 1),
 ('Denmark', 'Århus', 1),
 ('Spain', 'Barcelona', 1),
 ('Venezuela', 'Barquisimeto', 1),
 ('Italy', 'Bergamo', 1),
 ('Germany', 'Berlin', 1),
 ('Switzerland', 'Bern', 1),
 ('USA', 'Boise', 1),
 ('Sweden', 'Bräcke', 1),
 ('Germany', 'Brandenburg', 1),
 ('Belgium', 'Bruxelles', 1)]

## M22. Subsetting

In [75]:
%%sql
SELECT ProductID, ProductName, UnitsInStock, ReorderLevel
FROM Products
WHERE UnitsInStock <= ReorderLevel
ORDER BY ProductID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(2, 'Chang', 17, 25),
 (3, 'Aniseed Syrup', 13, 25),
 (5, "Chef Anton's Gumbo Mix", 0, 0),
 (11, 'Queso Cabrales', 22, 30),
 (17, 'Alice Mutton', 0, 0),
 (21, "Sir Rodney's Scones", 3, 5),
 (29, 'Thüringer Rostbratwurst', 0, 0),
 (30, 'Nord-Ost Matjeshering', 10, 15),
 (31, 'Gorgonzola Telino', 0, 20),
 (32, 'Mascarpone Fabioli', 9, 25),
 (37, 'Gravad lax', 11, 25),
 (43, 'Ipoh Coffee', 17, 25),
 (45, 'Rogede sild', 5, 15),
 (48, 'Chocolade', 15, 25),
 (49, 'Maxilaku', 10, 15),
 (53, 'Perth Pasties', 0, 0),
 (56, 'Gnocchi di nonna Alice', 21, 30),
 (64, 'Wimmers gute Semmelknödel', 22, 30),
 (66, 'Louisiana Hot Spiced Okra', 4, 20),
 (68, 'Scottish Longbreads', 6, 15),
 (70, 'Outback Lager', 15, 30),
 (74, 'Longlife Tofu', 4, 5)]

## M23. Subsetting (continued)

In [77]:
%%sql
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Products'

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('NorthWind', 'dbo', 'Products', 'ProductID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'ProductName', 2, None, 'NO', 'nvarchar', 40, 80, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Products', 'SupplierID', 3, None, 'YES', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'CategoryID', 4, None, 'YES', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'QuantityPerUnit', 5, None, 'YES', 'nvarchar', 20, 40, None, None, None, None, None, None, 'UNICODE', None, None, 'SQL_Latin1_General_CP1_CI_AS', None, None, None),
 ('NorthWind', 'dbo', 'Products', 'UnitPrice', 6, '(0)', 'YES', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'UnitsInStock', 7, '(0)', 'YES', 'smallint', None, None, 5, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'UnitsOnOrder', 8, '(0)', 'YES', 'smallint', None, None, 5, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'ReorderLevel', 9, '(0)', 'YES', 'smallint', None, None, 5, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('NorthWind', 'dbo', 'Products', 'Discontinued', 10, '(0)', 'NO', 'bit', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)]

In [79]:
%%sql
SELECT ProductID, ProductName, UnitsInStock, UnitsOnOrder, ReorderLevel, Discontinued
FROM Products
WHERE UnitsInStock + UnitsOnOrder <= ReorderLevel AND Discontinued = 0
ORDER BY ProductID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(30, 'Nord-Ost Matjeshering', 10, 0, 15, False),
 (70, 'Outback Lager', 15, 10, 30, False)]

## M24. Hierachical sorting

In [82]:
%%sql
SELECT CustomerID, CompanyName, Region
FROM Customers
ORDER BY CASE WHEN Region IS NULL THEN 1 ELSE 0 END, Region, CustomerID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('OLDWO', 'Old World Delicatessen', 'AK'),
 ('BOTTM', 'Bottom-Dollar Markets', 'BC'),
 ('LAUGB', 'Laughing Bacchus Wine Cellars', 'BC'),
 ('LETSS', "Let's Stop N Shop", 'CA'),
 ('HUNGO', 'Hungry Owl All-Night Grocers', 'Co. Cork'),
 ('GROSR', 'GROSELLA-Restaurante', 'DF'),
 ('SAVEA', 'Save-a-lot Markets', 'ID'),
 ('ISLAT', 'Island Trading', 'Isle of Wight'),
 ('LILAS', 'LILA-Supermercado', 'Lara'),
 ('THECR', 'The Cracker Box', 'MT'),
 ('RATTC', 'Rattlesnake Canyon Grocery', 'NM'),
 ('LINOD', 'LINO-Delicateses', 'Nueva Esparta'),
 ('GREAL', 'Great Lakes Food Market', 'OR'),
 ('HUNGC', 'Hungry Coyote Import Store', 'OR'),
 ('LONEP', 'Lonesome Pine Restaurant', 'OR'),
 ('THEBI', 'The Big Cheese', 'OR'),
 ('MEREP', 'Mère Paillarde', 'Québec'),
 ('HANAR', 'Hanari Carnes', 'RJ'),
 ('QUEDE', 'Que Delícia', 'RJ'),
 ('RICAR', 'Ricardo Adocicados', 'RJ'),
 ('COMMI', 'Comércio Mineiro', 'SP'),
 ('FAMIA', 'Familia Arquibaldo', 'SP'),
 ('GOURL', 'Gourmet Lanchonetes', 'SP'),
 ('QUEEN', 'Queen Cozinha', 'SP'),
 ('TRADH', 'Tradição Hipermercados', 'SP'),
 ('WELLI', 'Wellington Importadora', 'SP'),
 ('HILAA', 'HILARION-Abastos', 'Táchira'),
 ('LAZYK', 'Lazy K Kountry Store', 'WA'),
 ('TRAIH', "Trail's Head Gourmet Provisioners", 'WA'),
 ('WHITC', 'White Clover Markets', 'WA'),
 ('SPLIR', 'Split Rail Beer & Ale', 'WY'),
 ('ALFKI', 'Alfreds Futterkiste', None),
 ('ANATR', 'Ana Trujillo Emparedados y helados', None),
 ('ANTON', 'Antonio Moreno Taquería', None),
 ('AROUT', 'Around the Horn', None),
 ('BERGS', 'Berglunds snabbköp', None),
 ('BLAUS', 'Blauer See Delikatessen', None),
 ('BLONP', 'Blondesddsl père et fils', None),
 ('BOLID', 'Bólido Comidas preparadas', None),
 ('BONAP', "Bon app'", None),
 ('BSBEV', "B's Beverages", None),
 ('CACTU', 'Cactus Comidas para llevar', None),
 ('CENTC', 'Centro comercial Moctezuma', None),
 ('CHOPS', 'Chop-suey Chinese', None),
 ('CONSH', 'Consolidated Holdings', None),
 ('DRACD', 'Drachenblut Delikatessen', None),
 ('DUMON', 'Du monde entier', None),
 ('EASTC', 'Eastern Connection', None),
 ('ERNSH', 'Ernst Handel', None),
 ('FISSA', 'FISSA Fabrica Inter. Salchichas S.A.', None),
 ('FOLIG', 'Folies gourmandes', None),
 ('FOLKO', 'Folk och fä HB', None),
 ('FRANK', 'Frankenversand', None),
 ('FRANR', 'France restauration', None),
 ('FRANS', 'Franchi S.p.A.', None),
 ('FURIB', 'Furia Bacalhau e Frutos do Mar', None),
 ('GALED', 'Galería del gastrónomo', None),
 ('GODOS', 'Godos Cocina Típica', None),
 ('KOENE', 'Königlich Essen', None),
 ('LACOR', "La corne d'abondance", None),
 ('LAMAI', "La maison d'Asie", None),
 ('LEHMS', 'Lehmanns Marktstand', None),
 ('MAGAA', 'Magazzini Alimentari Riuniti', None),
 ('MAISD', 'Maison Dewey', None),
 ('MORGK', 'Morgenstern Gesundkost', None),
 ('NORTS', 'North/South', None),
 ('OCEAN', 'Océano Atlántico Ltda.', None),
 ('OTTIK', 'Ottilies Käseladen', None),
 ('PARIS', 'Paris spécialités', None),
 ('PERIC', 'Pericles Comidas clásicas', None),
 ('PICCO', 'Piccolo und mehr', None),
 ('PRINI', 'Princesa Isabel Vinhos', None),
 ('QUICK', 'QUICK-Stop', None),
 ('RANCH', 'Rancho grande', None),
 ('REGGC', 'Reggiani Caseifici', None),
 ('RICSU', 'Richter Supermarkt', None),
 ('ROMEY', 'Romero y tomillo', None),
 ('SANTG', 'Santé Gourmet', None),
 ('SEVES', 'Seven Seas Imports', None),
 ('SIMOB', 'Simons bistro', None),
 ('SPECD', 'Spécialités du monde', None),
 ('SUPRD', 'Suprêmes délices', None),
 ('TOMSP', 'Toms Spezialitäten', None),
 ('TORTU', 'Tortuga Restaurante', None),
 ('VAFFE', 'Vaffeljernet', None),
 ('VICTE', 'Victuailles en stock', None),
 ('VINET', 'Vins et alcools Chevalier', None),
 ('WANDK', 'Die Wandernde Kuh', None),
 ('WARTH', 'Wartian Herkku', None),
 ('WILMK', 'Wilman Kala', None),
 ('WOLZA', 'Wolski  Zajazd', None)]

## M25. Show samples with extreme values

In [81]:
%%sql
SELECT TOP 3 ShipCountry, AverageFreight = AVG(Freight)
FROM Orders
GROUP BY ShipCountry
ORDER BY AverageFreight DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Austria', Decimal('184.7875')),
 ('Ireland', Decimal('145.0126')),
 ('USA', Decimal('112.8794'))]

## M26. Zoom in samples in a fixed time frame

In [90]:
%%sql
SELECT ShipCountry, OrderDate FROM Orders

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('France', datetime.datetime(1996, 7, 4, 0, 0)),
 ('Germany', datetime.datetime(1996, 7, 5, 0, 0)),
 ('Brazil', datetime.datetime(1996, 7, 8, 0, 0)),
 ('France', datetime.datetime(1996, 7, 8, 0, 0)),
 ('Belgium', datetime.datetime(1996, 7, 9, 0, 0)),
 ('Brazil', datetime.datetime(1996, 7, 10, 0, 0)),
 ('Switzerland', datetime.datetime(1996, 7, 11, 0, 0)),
 ('Switzerland', datetime.datetime(1996, 7, 12, 0, 0)),
 ('Brazil', datetime.datetime(1996, 7, 15, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 7, 16, 0, 0)),
 ('Austria', datetime.datetime(1996, 7, 17, 0, 0)),
 ('Mexico', datetime.datetime(1996, 7, 18, 0, 0)),
 ('Germany', datetime.datetime(1996, 7, 19, 0, 0)),
 ('Brazil', datetime.datetime(1996, 7, 19, 0, 0)),
 ('USA', datetime.datetime(1996, 7, 22, 0, 0)),
 ('Austria', datetime.datetime(1996, 7, 23, 0, 0)),
 ('Sweden', datetime.datetime(1996, 7, 24, 0, 0)),
 ('France', datetime.datetime(1996, 7, 25, 0, 0)),
 ('Finland', datetime.datetime(1996, 7, 26, 0, 0)),
 ('Germany', datetime.datetime(1996, 7, 29, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 7, 30, 0, 0)),
 ('USA', datetime.datetime(1996, 7, 31, 0, 0)),
 ('Finland', datetime.datetime(1996, 8, 1, 0, 0)),
 ('USA', datetime.datetime(1996, 8, 1, 0, 0)),
 ('USA', datetime.datetime(1996, 8, 2, 0, 0)),
 ('Germany', datetime.datetime(1996, 8, 5, 0, 0)),
 ('France', datetime.datetime(1996, 8, 6, 0, 0)),
 ('Italy', datetime.datetime(1996, 8, 7, 0, 0)),
 ('Mexico', datetime.datetime(1996, 8, 8, 0, 0)),
 ('Germany', datetime.datetime(1996, 8, 9, 0, 0)),
 ('Sweden', datetime.datetime(1996, 8, 12, 0, 0)),
 ('Germany', datetime.datetime(1996, 8, 13, 0, 0)),
 ('Sweden', datetime.datetime(1996, 8, 14, 0, 0)),
 ('Spain', datetime.datetime(1996, 8, 14, 0, 0)),
 ('Spain', datetime.datetime(1996, 8, 15, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 8, 16, 0, 0)),
 ('Germany', datetime.datetime(1996, 8, 19, 0, 0)),
 ('Germany', datetime.datetime(1996, 8, 20, 0, 0)),
 ('Germany', datetime.datetime(1996, 8, 21, 0, 0)),
 ('Brazil', datetime.datetime(1996, 8, 22, 0, 0)),
 ('Italy', datetime.datetime(1996, 8, 23, 0, 0)),
 ('UK', datetime.datetime(1996, 8, 26, 0, 0)),
 ('Brazil', datetime.datetime(1996, 8, 27, 0, 0)),
 ('Brazil', datetime.datetime(1996, 8, 27, 0, 0)),
 ('Brazil', datetime.datetime(1996, 8, 28, 0, 0)),
 ('Mexico', datetime.datetime(1996, 8, 29, 0, 0)),
 ('USA', datetime.datetime(1996, 8, 30, 0, 0)),
 ('France', datetime.datetime(1996, 9, 2, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 9, 3, 0, 0)),
 ('France', datetime.datetime(1996, 9, 4, 0, 0)),
 ('Ireland', datetime.datetime(1996, 9, 5, 0, 0)),
 ('Brazil', datetime.datetime(1996, 9, 6, 0, 0)),
 ('Italy', datetime.datetime(1996, 9, 9, 0, 0)),
 ('Germany', datetime.datetime(1996, 9, 9, 0, 0)),
 ('Belgium', datetime.datetime(1996, 9, 10, 0, 0)),
 ('Spain', datetime.datetime(1996, 9, 11, 0, 0)),
 ('Mexico', datetime.datetime(1996, 9, 12, 0, 0)),
 ('USA', datetime.datetime(1996, 9, 13, 0, 0)),
 ('Spain', datetime.datetime(1996, 9, 16, 0, 0)),
 ('USA', datetime.datetime(1996, 9, 17, 0, 0)),
 ('Mexico', datetime.datetime(1996, 9, 18, 0, 0)),
 ('Ireland', datetime.datetime(1996, 9, 19, 0, 0)),
 ('USA', datetime.datetime(1996, 9, 20, 0, 0)),
 ('France', datetime.datetime(1996, 9, 20, 0, 0)),
 ('Germany', datetime.datetime(1996, 9, 23, 0, 0)),
 ('Germany', datetime.datetime(1996, 9, 24, 0, 0)),
 ('USA', datetime.datetime(1996, 9, 25, 0, 0)),
 ('UK', datetime.datetime(1996, 9, 26, 0, 0)),
 ('USA', datetime.datetime(1996, 9, 27, 0, 0)),
 ('USA', datetime.datetime(1996, 9, 30, 0, 0)),
 ('UK', datetime.datetime(1996, 10, 1, 0, 0)),
 ('Mexico', datetime.datetime(1996, 10, 2, 0, 0)),
 ('Finland', datetime.datetime(1996, 10, 3, 0, 0)),
 ('UK', datetime.datetime(1996, 10, 3, 0, 0)),
 ('Mexico', datetime.datetime(1996, 10, 4, 0, 0)),
 ('Germany', datetime.datetime(1996, 10, 7, 0, 0)),
 ('USA', datetime.datetime(1996, 10, 8, 0, 0)),
 ('Germany', datetime.datetime(1996, 10, 9, 0, 0)),
 ('Spain', datetime.datetime(1996, 10, 10, 0, 0)),
 ('Sweden', datetime.datetime(1996, 10, 11, 0, 0)),
 ('Portugal', datetime.datetime(1996, 10, 14, 0, 0)),
 ('USA', datetime.datetime(1996, 10, 15, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 10, 16, 0, 0)),
 ('France', datetime.datetime(1996, 10, 16, 0, 0)),
 ('Canada', datetime.datetime(1996, 10, 17, 0, 0)),
 ('Finland', datetime.datetime(1996, 10, 18, 0, 0)),
 ('France', datetime.datetime(1996, 10, 21, 0, 0)),
 ('Ireland', datetime.datetime(1996, 10, 22, 0, 0)),
 ('Portugal', datetime.datetime(1996, 10, 23, 0, 0)),
 ('Germany', datetime.datetime(1996, 10, 24, 0, 0)),
 ('USA', datetime.datetime(1996, 10, 25, 0, 0)),
 ('Canada', datetime.datetime(1996, 10, 28, 0, 0)),
 ('France', datetime.datetime(1996, 10, 29, 0, 0)),
 ('Denmark', datetime.datetime(1996, 10, 29, 0, 0)),
 ('Germany', datetime.datetime(1996, 10, 30, 0, 0)),
 ('Germany', datetime.datetime(1996, 10, 31, 0, 0)),
 ('USA', datetime.datetime(1996, 11, 1, 0, 0)),
 ('Germany', datetime.datetime(1996, 11, 4, 0, 0)),
 ('USA', datetime.datetime(1996, 11, 5, 0, 0)),
 ('Brazil', datetime.datetime(1996, 11, 6, 0, 0)),
 ('Germany', datetime.datetime(1996, 11, 7, 0, 0)),
 ('USA', datetime.datetime(1996, 11, 8, 0, 0)),
 ('France', datetime.datetime(1996, 11, 11, 0, 0)),
 ('Austria', datetime.datetime(1996, 11, 11, 0, 0)),
 ('Portugal', datetime.datetime(1996, 11, 12, 0, 0)),
 ('Austria', datetime.datetime(1996, 11, 13, 0, 0)),
 ('Mexico', datetime.datetime(1996, 11, 14, 0, 0)),
 ('UK', datetime.datetime(1996, 11, 15, 0, 0)),
 ('Germany', datetime.datetime(1996, 11, 18, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 11, 19, 0, 0)),
 ('France', datetime.datetime(1996, 11, 20, 0, 0)),
 ('UK', datetime.datetime(1996, 11, 21, 0, 0)),
 ('France', datetime.datetime(1996, 11, 22, 0, 0)),
 ('Germany', datetime.datetime(1996, 11, 22, 0, 0)),
 ('France', datetime.datetime(1996, 11, 25, 0, 0)),
 ('Germany', datetime.datetime(1996, 11, 26, 0, 0)),
 ('UK', datetime.datetime(1996, 11, 26, 0, 0)),
 ('Mexico', datetime.datetime(1996, 11, 27, 0, 0)),
 ('Spain', datetime.datetime(1996, 11, 28, 0, 0)),
 ('Denmark', datetime.datetime(1996, 11, 28, 0, 0)),
 ('Austria', datetime.datetime(1996, 11, 29, 0, 0)),
 ('USA', datetime.datetime(1996, 12, 2, 0, 0)),
 ('Switzerland', datetime.datetime(1996, 12, 3, 0, 0)),
 ('France', datetime.datetime(1996, 12, 3, 0, 0)),
 ('Brazil', datetime.datetime(1996, 12, 4, 0, 0)),
 ('Ireland', datetime.datetime(1996, 12, 5, 0, 0)),
 ('Poland', datetime.datetime(1996, 12, 5, 0, 0)),
 ('USA', datetime.datetime(1996, 12, 6, 0, 0)),
 ('Canada', datetime.datetime(1996, 12, 9, 0, 0)),
 ('UK', datetime.datetime(1996, 12, 9, 0, 0)),
 ('Sweden', datetime.datetime(1996, 12, 10, 0, 0)),
 ('Brazil', datetime.datetime(1996, 12, 11, 0, 0)),
 ('Ireland', datetime.datetime(1996, 12, 12, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 12, 12, 0, 0)),
 ('Austria', datetime.datetime(1996, 12, 13, 0, 0)),
 ('UK', datetime.datetime(1996, 12, 16, 0, 0)),
 ('Sweden', datetime.datetime(1996, 12, 16, 0, 0)),
 ('USA', datetime.datetime(1996, 12, 17, 0, 0)),
 ('Brazil', datetime.datetime(1996, 12, 18, 0, 0)),
 ('Norway', datetime.datetime(1996, 12, 18, 0, 0)),
 ('UK', datetime.datetime(1996, 12, 19, 0, 0)),
 ('Canada', datetime.datetime(1996, 12, 20, 0, 0)),
 ('Austria', datetime.datetime(1996, 12, 23, 0, 0)),
 ('Germany', datetime.datetime(1996, 12, 23, 0, 0)),
 ('Austria', datetime.datetime(1996, 12, 24, 0, 0)),
 ('USA', datetime.datetime(1996, 12, 25, 0, 0)),
 ('USA', datetime.datetime(1996, 12, 25, 0, 0)),
 ('Venezuela', datetime.datetime(1996, 12, 26, 0, 0)),
 ('Germany', datetime.datetime(1996, 12, 27, 0, 0)),
 ('Portugal', datetime.datetime(1996, 12, 27, 0, 0)),
 ('USA', datetime.datetime(1996, 12, 30, 0, 0)),
 ('Denmark', datetime.datetime(1996, 12, 31, 0, 0)),
 ('UK', datetime.datetime(1997, 1, 1, 0, 0)),
 ('USA', datetime.datetime(1997, 1, 1, 0, 0)),
 ('Austria', datetime.datetime(1997, 1, 2, 0, 0)),
 ('Austria', datetime.datetime(1997, 1, 3, 0, 0)),
 ('Italy', datetime.datetime(1997, 1, 3, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 1, 6, 0, 0)),
 ('Brazil', datetime.datetime(1997, 1, 7, 0, 0)),
 ('Germany', datetime.datetime(1997, 1, 7, 0, 0)),
 ('France', datetime.datetime(1997, 1, 8, 0, 0)),
 ('Argentina', datetime.datetime(1997, 1, 9, 0, 0)),
 ('Canada', datetime.datetime(1997, 1, 10, 0, 0)),
 ('Canada', datetime.datetime(1997, 1, 10, 0, 0)),
 ('Finland', datetime.datetime(1997, 1, 13, 0, 0)),
 ('France', datetime.datetime(1997, 1, 14, 0, 0)),
 ('Brazil', datetime.datetime(1997, 1, 14, 0, 0)),
 ('USA', datetime.datetime(1997, 1, 15, 0, 0)),
 ('Finland', datetime.datetime(1997, 1, 16, 0, 0)),
 ('Denmark', datetime.datetime(1997, 1, 16, 0, 0)),
 ('Germany', datetime.datetime(1997, 1, 17, 0, 0)),
 ('Switzerland', datetime.datetime(1997, 1, 20, 0, 0)),
 ('Brazil', datetime.datetime(1997, 1, 21, 0, 0)),
 ('Brazil', datetime.datetime(1997, 1, 21, 0, 0)),
 ('Italy', datetime.datetime(1997, 1, 22, 0, 0)),
 ('Brazil', datetime.datetime(1997, 1, 23, 0, 0)),
 ('Canada', datetime.datetime(1997, 1, 23, 0, 0)),
 ('France', datetime.datetime(1997, 1, 24, 0, 0)),
 ('Spain', datetime.datetime(1997, 1, 27, 0, 0)),
 ('Austria', datetime.datetime(1997, 1, 27, 0, 0)),
 ('Italy', datetime.datetime(1997, 1, 28, 0, 0)),
 ('Ireland', datetime.datetime(1997, 1, 29, 0, 0)),
 ('Austria', datetime.datetime(1997, 1, 30, 0, 0)),
 ('Canada', datetime.datetime(1997, 1, 30, 0, 0)),
 ('USA', datetime.datetime(1997, 1, 31, 0, 0)),
 ('Portugal', datetime.datetime(1997, 2, 3, 0, 0)),
 ('Sweden', datetime.datetime(1997, 2, 3, 0, 0)),
 ('UK', datetime.datetime(1997, 2, 4, 0, 0)),
 ('France', datetime.datetime(1997, 2, 5, 0, 0)),
 ('Finland', datetime.datetime(1997, 2, 5, 0, 0)),
 ('Germany', datetime.datetime(1997, 2, 6, 0, 0)),
 ('Canada', datetime.datetime(1997, 2, 7, 0, 0)),
 ('USA', datetime.datetime(1997, 2, 10, 0, 0)),
 ('USA', datetime.datetime(1997, 2, 10, 0, 0)),
 ('Austria', datetime.datetime(1997, 2, 11, 0, 0)),
 ('Italy', datetime.datetime(1997, 2, 12, 0, 0)),
 ('Sweden', datetime.datetime(1997, 2, 12, 0, 0)),
 ('Sweden', datetime.datetime(1997, 2, 13, 0, 0)),
 ('Germany', datetime.datetime(1997, 2, 14, 0, 0)),
 ('Brazil', datetime.datetime(1997, 2, 14, 0, 0)),
 ('Argentina', datetime.datetime(1997, 2, 17, 0, 0)),
 ('France', datetime.datetime(1997, 2, 18, 0, 0)),
 ('France', datetime.datetime(1997, 2, 19, 0, 0)),
 ('Germany', datetime.datetime(1997, 2, 19, 0, 0)),
 ('USA', datetime.datetime(1997, 2, 20, 0, 0)),
 ('UK', datetime.datetime(1997, 2, 21, 0, 0)),
 ('France', datetime.datetime(1997, 2, 21, 0, 0)),
 ('Finland', datetime.datetime(1997, 2, 24, 0, 0)),
 ('Germany', datetime.datetime(1997, 2, 25, 0, 0)),
 ('Germany', datetime.datetime(1997, 2, 25, 0, 0)),
 ('Belgium', datetime.datetime(1997, 2, 26, 0, 0)),
 ('France', datetime.datetime(1997, 2, 27, 0, 0)),
 ('Sweden', datetime.datetime(1997, 2, 28, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 2, 28, 0, 0)),
 ('UK', datetime.datetime(1997, 3, 3, 0, 0)),
 ('Belgium', datetime.datetime(1997, 3, 4, 0, 0)),
 ('Portugal', datetime.datetime(1997, 3, 4, 0, 0)),
 ('Denmark', datetime.datetime(1997, 3, 5, 0, 0)),
 ('Brazil', datetime.datetime(1997, 3, 6, 0, 0)),
 ('Italy', datetime.datetime(1997, 3, 6, 0, 0)),
 ('Germany', datetime.datetime(1997, 3, 7, 0, 0)),
 ('USA', datetime.datetime(1997, 3, 10, 0, 0)),
 ('France', datetime.datetime(1997, 3, 11, 0, 0)),
 ('UK', datetime.datetime(1997, 3, 11, 0, 0)),
 ('UK', datetime.datetime(1997, 3, 12, 0, 0)),
 ('UK', datetime.datetime(1997, 3, 13, 0, 0)),
 ('Mexico', datetime.datetime(1997, 3, 13, 0, 0)),
 ('Belgium', datetime.datetime(1997, 3, 14, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 3, 17, 0, 0)),
 ('Portugal', datetime.datetime(1997, 3, 17, 0, 0)),
 ('France', datetime.datetime(1997, 3, 18, 0, 0)),
 ('USA', datetime.datetime(1997, 3, 19, 0, 0)),
 ('France', datetime.datetime(1997, 3, 20, 0, 0)),
 ('Brazil', datetime.datetime(1997, 3, 20, 0, 0)),
 ('USA', datetime.datetime(1997, 3, 21, 0, 0)),
 ('USA', datetime.datetime(1997, 3, 24, 0, 0)),
 ('UK', datetime.datetime(1997, 3, 24, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 3, 25, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 3, 26, 0, 0)),
 ('Brazil', datetime.datetime(1997, 3, 26, 0, 0)),
 ('Germany', datetime.datetime(1997, 3, 27, 0, 0)),
 ('Austria', datetime.datetime(1997, 3, 28, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 3, 31, 0, 0)),
 ('Portugal', datetime.datetime(1997, 3, 31, 0, 0)),
 ('Canada', datetime.datetime(1997, 4, 1, 0, 0)),
 ('France', datetime.datetime(1997, 4, 2, 0, 0)),
 ('Brazil', datetime.datetime(1997, 4, 2, 0, 0)),
 ('Canada', datetime.datetime(1997, 4, 3, 0, 0)),
 ('Brazil', datetime.datetime(1997, 4, 4, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 4, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 4, 7, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 4, 8, 0, 0)),
 ('France', datetime.datetime(1997, 4, 9, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 9, 0, 0)),
 ('Mexico', datetime.datetime(1997, 4, 10, 0, 0)),
 ('Ireland', datetime.datetime(1997, 4, 11, 0, 0)),
 ('USA', datetime.datetime(1997, 4, 11, 0, 0)),
 ('Canada', datetime.datetime(1997, 4, 14, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 15, 0, 0)),
 ('Mexico', datetime.datetime(1997, 4, 15, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 16, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 17, 0, 0)),
 ('USA', datetime.datetime(1997, 4, 18, 0, 0)),
 ('France', datetime.datetime(1997, 4, 18, 0, 0)),
 ('Brazil', datetime.datetime(1997, 4, 21, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 22, 0, 0)),
 ('Austria', datetime.datetime(1997, 4, 22, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 23, 0, 0)),
 ('Ireland', datetime.datetime(1997, 4, 24, 0, 0)),
 ('UK', datetime.datetime(1997, 4, 24, 0, 0)),
 ('Mexico', datetime.datetime(1997, 4, 25, 0, 0)),
 ('Switzerland', datetime.datetime(1997, 4, 28, 0, 0)),
 ('Norway', datetime.datetime(1997, 4, 29, 0, 0)),
 ('Argentina', datetime.datetime(1997, 4, 29, 0, 0)),
 ('Germany', datetime.datetime(1997, 4, 30, 0, 0)),
 ('UK', datetime.datetime(1997, 5, 1, 0, 0)),
 ('Sweden', datetime.datetime(1997, 5, 1, 0, 0)),
 ('France', datetime.datetime(1997, 5, 2, 0, 0)),
 ('Finland', datetime.datetime(1997, 5, 5, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 5, 0, 0)),
 ('USA', datetime.datetime(1997, 5, 6, 0, 0)),
 ('Belgium', datetime.datetime(1997, 5, 7, 0, 0)),
 ('Austria', datetime.datetime(1997, 5, 8, 0, 0)),
 ('Argentina', datetime.datetime(1997, 5, 8, 0, 0)),
 ('UK', datetime.datetime(1997, 5, 9, 0, 0)),
 ('Sweden', datetime.datetime(1997, 5, 12, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 12, 0, 0)),
 ('Mexico', datetime.datetime(1997, 5, 13, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 14, 0, 0)),
 ('Switzerland', datetime.datetime(1997, 5, 14, 0, 0)),
 ('UK', datetime.datetime(1997, 5, 15, 0, 0)),
 ('UK', datetime.datetime(1997, 5, 16, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 19, 0, 0)),
 ('Brazil', datetime.datetime(1997, 5, 19, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 20, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 5, 21, 0, 0)),
 ('USA', datetime.datetime(1997, 5, 21, 0, 0)),
 ('USA', datetime.datetime(1997, 5, 22, 0, 0)),
 ('France', datetime.datetime(1997, 5, 23, 0, 0)),
 ('UK', datetime.datetime(1997, 5, 23, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 26, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 27, 0, 0)),
 ('Spain', datetime.datetime(1997, 5, 28, 0, 0)),
 ('Portugal', datetime.datetime(1997, 5, 28, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 5, 29, 0, 0)),
 ('Finland', datetime.datetime(1997, 5, 30, 0, 0)),
 ('Germany', datetime.datetime(1997, 5, 30, 0, 0)),
 ('USA', datetime.datetime(1997, 6, 2, 0, 0)),
 ('Denmark', datetime.datetime(1997, 6, 3, 0, 0)),
 ('Germany', datetime.datetime(1997, 6, 3, 0, 0)),
 ('UK', datetime.datetime(1997, 6, 4, 0, 0)),
 ('France', datetime.datetime(1997, 6, 5, 0, 0)),
 ('Germany', datetime.datetime(1997, 6, 6, 0, 0)),
 ('Sweden', datetime.datetime(1997, 6, 6, 0, 0)),
 ('Italy', datetime.datetime(1997, 6, 9, 0, 0)),
 ('Brazil', datetime.datetime(1997, 6, 10, 0, 0)),
 ('USA', datetime.datetime(1997, 6, 10, 0, 0)),
 ('Canada', datetime.datetime(1997, 6, 11, 0, 0)),
 ('France', datetime.datetime(1997, 6, 12, 0, 0)),
 ('Ireland', datetime.datetime(1997, 6, 12, 0, 0)),
 ('Spain', datetime.datetime(1997, 6, 13, 0, 0)),
 ('USA', datetime.datetime(1997, 6, 16, 0, 0)),
 ('Canada', datetime.datetime(1997, 6, 17, 0, 0)),
 ('Austria', datetime.datetime(1997, 6, 17, 0, 0)),
 ('Sweden', datetime.datetime(1997, 6, 18, 0, 0)),
 ('Mexico', datetime.datetime(1997, 6, 19, 0, 0)),
 ('USA', datetime.datetime(1997, 6, 19, 0, 0)),
 ('Germany', datetime.datetime(1997, 6, 20, 0, 0)),
 ('Mexico', datetime.datetime(1997, 6, 23, 0, 0)),
 ('USA', datetime.datetime(1997, 6, 23, 0, 0)),
 ('UK', datetime.datetime(1997, 6, 24, 0, 0)),
 ('USA', datetime.datetime(1997, 6, 25, 0, 0)),
 ('Germany', datetime.datetime(1997, 6, 26, 0, 0)),
 ('Brazil', datetime.datetime(1997, 6, 26, 0, 0)),
 ('Germany', datetime.datetime(1997, 6, 27, 0, 0)),
 ('Finland', datetime.datetime(1997, 6, 30, 0, 0)),
 ('France', datetime.datetime(1997, 6, 30, 0, 0)),
 ('Brazil', datetime.datetime(1997, 7, 1, 0, 0)),
 ('Italy', datetime.datetime(1997, 7, 2, 0, 0)),
 ('Brazil', datetime.datetime(1997, 7, 2, 0, 0)),
 ('Germany', datetime.datetime(1997, 7, 3, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 4, 0, 0)),
 ('Canada', datetime.datetime(1997, 7, 7, 0, 0)),
 ('Denmark', datetime.datetime(1997, 7, 7, 0, 0)),
 ('Germany', datetime.datetime(1997, 7, 8, 0, 0)),
 ('Germany', datetime.datetime(1997, 7, 9, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 9, 0, 0)),
 ('Austria', datetime.datetime(1997, 7, 10, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 11, 0, 0)),
 ('Austria', datetime.datetime(1997, 7, 11, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 14, 0, 0)),
 ('UK', datetime.datetime(1997, 7, 15, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 16, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 7, 16, 0, 0)),
 ('Denmark', datetime.datetime(1997, 7, 17, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 18, 0, 0)),
 ('Portugal', datetime.datetime(1997, 7, 18, 0, 0)),
 ('Canada', datetime.datetime(1997, 7, 21, 0, 0)),
 ('Brazil', datetime.datetime(1997, 7, 22, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 22, 0, 0)),
 ('Germany', datetime.datetime(1997, 7, 23, 0, 0)),
 ('France', datetime.datetime(1997, 7, 24, 0, 0)),
 ('France', datetime.datetime(1997, 7, 25, 0, 0)),
 ('Poland', datetime.datetime(1997, 7, 25, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 28, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 7, 29, 0, 0)),
 ('Germany', datetime.datetime(1997, 7, 29, 0, 0)),
 ('Finland', datetime.datetime(1997, 7, 30, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 31, 0, 0)),
 ('USA', datetime.datetime(1997, 7, 31, 0, 0)),
 ('Canada', datetime.datetime(1997, 8, 1, 0, 0)),
 ('Canada', datetime.datetime(1997, 8, 4, 0, 0)),
 ('Canada', datetime.datetime(1997, 8, 5, 0, 0)),
 ('UK', datetime.datetime(1997, 8, 5, 0, 0)),
 ('Brazil', datetime.datetime(1997, 8, 6, 0, 0)),
 ('Germany', datetime.datetime(1997, 8, 7, 0, 0)),
 ('USA', datetime.datetime(1997, 8, 7, 0, 0)),
 ('Mexico', datetime.datetime(1997, 8, 8, 0, 0)),
 ('Sweden', datetime.datetime(1997, 8, 11, 0, 0)),
 ('USA', datetime.datetime(1997, 8, 11, 0, 0)),
 ('France', datetime.datetime(1997, 8, 12, 0, 0)),
 ('Spain', datetime.datetime(1997, 8, 12, 0, 0)),
 ('Germany', datetime.datetime(1997, 8, 13, 0, 0)),
 ('France', datetime.datetime(1997, 8, 14, 0, 0)),
 ('Germany', datetime.datetime(1997, 8, 14, 0, 0)),
 ('Austria', datetime.datetime(1997, 8, 15, 0, 0)),
 ('France', datetime.datetime(1997, 8, 15, 0, 0)),
 ('Italy', datetime.datetime(1997, 8, 18, 0, 0)),
 ('Finland', datetime.datetime(1997, 8, 19, 0, 0)),
 ('Brazil', datetime.datetime(1997, 8, 19, 0, 0)),
 ('Venezuela', datetime.datetime(1997, 8, 20, 0, 0)),
 ('Norway', datetime.datetime(1997, 8, 20, 0, 0)),
 ('Germany', datetime.datetime(1997, 8, 21, 0, 0)),

In [4]:
# Method 1
%%sql
SELECT TOP 3 ShipCountry, AverageFreight = AVG(Freight)
FROM Orders
WHERE OrderDate >= '1996-01-01' AND OrderDate < '1997-01-01'
GROUP BY ShipCountry
ORDER BY AverageFreight DESC;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Austria', Decimal('156.8862')),
 ('Brazil', Decimal('94.1453')),
 ('Norway', Decimal('93.6300'))]

In [6]:
# Method 2
%%sql
SELECT TOP 3 ShipCountry, AverageFreight = AVG(Freight)
FROM Orders
WHERE YEAR(OrderDate) = 1996
GROUP BY ShipCountry
ORDER BY AverageFreight DESC;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Austria', Decimal('156.8862')),
 ('Brazil', Decimal('94.1453')),
 ('Norway', Decimal('93.6300'))]

## M27 and M28. Outliers skew the high freight charge rankings

In [28]:
%sql mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC+Driver+13+for+SQL+Server

'Connected: sa@NorthWind2016'

Method 1.

In [53]:
%%sql 
SELECT TOP 4 ShipCountry, AverageFreight = AVG(Freight)
FROM Orders
WHERE OrderDate BETWEEN '20150101' AND '20151231' -- this 20151231 is only equivalent to 20151-12-31 00:00:00, not the full day
GROUP BY ShipCountry
ORDER BY AverageFreight DESC;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Austria', Decimal('178.3642')),
 ('Switzerland', Decimal('117.1775')),
 ('Sweden', Decimal('105.1600')),
 ('Canada', Decimal('99.2800'))]

Method 2.

In [33]:
%%sql 
SELECT TOP 4 ShipCountry, AverageFreight = AVG(Freight)
FROM Orders
WHERE YEAR(OrderDate) = 2015
GROUP BY ShipCountry
ORDER BY AverageFreight DESC;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Austria', Decimal('178.3642')),
 ('Switzerland', Decimal('117.1775')),
 ('France', Decimal('113.9910')),
 ('Sweden', Decimal('105.1600'))]

In [ ]:
Method 3.

In [32]:
%%sql 
SELECT TOP 4 ShipCountry, AverageFreight = AVG(Freight)
FROM Orders
WHERE OrderDate >= '20150101' AND OrderDate < '20160101'
GROUP BY ShipCountry
ORDER BY AverageFreight DESC;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('Austria', Decimal('178.3642')),
 ('Switzerland', Decimal('117.1775')),
 ('France', Decimal('113.9910')),
 ('Sweden', Decimal('105.1600'))]

The result of Method 1 is different from those of Methods 2 and 3.

## M29. Merge of multiple tables

In [61]:
%%sql
SELECT Employees.EmployeeID, Employees.LastName, Orders.OrderID, Products.ProductName, OrderDetails.Quantity
FROM Employees
    JOIN Orders ON Orders.EmployeeID = Employees.EmployeeID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
    JOIN Products ON Products.ProductID = OrderDetails.ProductID
ORDER BY Orders.OrderID, Products.ProductID;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(5, 'Buchanan', 10248, 'Queso Cabrales', 12),
 (5, 'Buchanan', 10248, 'Singaporean Hokkien Fried Mee', 10),
 (5, 'Buchanan', 10248, 'Mozzarella di Giovanni', 5),
 (6, 'Suyama', 10249, 'Tofu', 9),
 (6, 'Suyama', 10249, 'Manjimup Dried Apples', 40),
 (4, 'Peacock', 10250, "Jack's New England Clam Chowder", 10),
 (4, 'Peacock', 10250, 'Manjimup Dried Apples', 35),
 (4, 'Peacock', 10250, 'Louisiana Fiery Hot Pepper Sauce', 15),
 (3, 'Leverling', 10251, "Gustaf's Knäckebröd", 6),
 (3, 'Leverling', 10251, 'Ravioli Angelo', 15),
 (3, 'Leverling', 10251, 'Louisiana Fiery Hot Pepper Sauce', 20),
 (4, 'Peacock', 10252, "Sir Rodney's Marmalade", 40),
 (4, 'Peacock', 10252, 'Geitost', 25),
 (4, 'Peacock', 10252, 'Camembert Pierrot', 40),
 (3, 'Leverling', 10253, 'Gorgonzola Telino', 20),
 (3, 'Leverling', 10253, 'Chartreuse verte', 42),
 (3, 'Leverling', 10253, 'Maxilaku', 40),
 (5, 'Buchanan', 10254, 'Guaraná Fantástica', 15),
 (5, 'Buchanan', 10254, 'Pâté chinois', 21),
 (5, 'Buchanan', 10254, 'Longlife Tofu', 21),
 (9, 'Dodsworth', 10255, 'Chang', 20),
 (9, 'Dodsworth', 10255, 'Pavlova', 35),
 (9, 'Dodsworth', 10255, 'Inlagd Sill', 25),
 (9, 'Dodsworth', 10255, 'Raclette Courdavault', 30),
 (3, 'Leverling', 10256, 'Perth Pasties', 15),
 (3, 'Leverling', 10256, 'Original Frankfurter grüne Soße', 12),
 (4, 'Peacock', 10257, 'Schoggi Schokolade', 25),
 (4, 'Peacock', 10257, 'Chartreuse verte', 6),
 (4, 'Peacock', 10257, 'Original Frankfurter grüne Soße', 15),
 (1, 'Davolio', 10258, 'Chang', 50),
 (1, 'Davolio', 10258, "Chef Anton's Gumbo Mix", 65),
 (1, 'Davolio', 10258, 'Mascarpone Fabioli', 6),
 (4, 'Peacock', 10259, "Sir Rodney's Scones", 10),
 (4, 'Peacock', 10259, 'Gravad lax', 1),
 (4, 'Peacock', 10260, "Jack's New England Clam Chowder", 16),
 (4, 'Peacock', 10260, 'Ravioli Angelo', 50),
 (4, 'Peacock', 10260, 'Tarte au sucre', 15),
 (4, 'Peacock', 10260, 'Outback Lager', 21),
 (4, 'Peacock', 10261, "Sir Rodney's Scones", 20),
 (4, 'Peacock', 10261, 'Steeleye Stout', 20),
 (8, 'Callahan', 10262, "Chef Anton's Gumbo Mix", 12),
 (8, 'Callahan', 10262, "Uncle Bob's Organic Dried Pears", 15),
 (8, 'Callahan', 10262, 'Gnocchi di nonna Alice', 2),
 (9, 'Dodsworth', 10263, 'Pavlova', 60),
 (9, 'Dodsworth', 10263, 'Guaraná Fantástica', 65),
 (9, 'Dodsworth', 10263, 'Nord-Ost Matjeshering', 60),
 (9, 'Dodsworth', 10263, 'Longlife Tofu', 65),
 (6, 'Suyama', 10264, 'Chang', 35),
 (6, 'Suyama', 10264, "Jack's New England Clam Chowder", 25),
 (2, 'Fuller', 10265, 'Alice Mutton', 30),
 (2, 'Fuller', 10265, 'Outback Lager', 20),
 (3, 'Leverling', 10266, 'Queso Manchego La Pastora', 12),
 (4, 'Peacock', 10267, 'Boston Crab Meat', 50),
 (4, 'Peacock', 10267, 'Raclette Courdavault', 70),
 (4, 'Peacock', 10267, 'Lakkalikööri', 15),
 (8, 'Callahan', 10268, 'Thüringer Rostbratwurst', 10),
 (8, 'Callahan', 10268, 'Mozzarella di Giovanni', 4),
 (5, 'Buchanan', 10269, 'Geitost', 60),
 (5, 'Buchanan', 10269, 'Mozzarella di Giovanni', 20),
 (1, 'Davolio', 10270, 'Inlagd Sill', 30),
 (1, 'Davolio', 10270, 'Ipoh Coffee', 25),
 (6, 'Suyama', 10271, 'Geitost', 24),
 (6, 'Suyama', 10272, "Sir Rodney's Marmalade", 6),
 (6, 'Suyama', 10272, 'Gorgonzola Telino', 40),
 (6, 'Suyama', 10272, 'Mozzarella di Giovanni', 24),
 (3, 'Leverling', 10273, 'Ikura', 24),
 (3, 'Leverling', 10273, 'Gorgonzola Telino', 15),
 (3, 'Leverling', 10273, 'Geitost', 20),
 (3, 'Leverling', 10273, 'Boston Crab Meat', 60),
 (3, 'Leverling', 10273, 'Lakkalikööri', 33),
 (6, 'Suyama', 10274, 'Flotemysost', 20),
 (6, 'Suyama', 10274, 'Mozzarella di Giovanni', 7),
 (1, 'Davolio', 10275, 'Guaraná Fantástica', 12),
 (1, 'Davolio', 10275, 'Raclette Courdavault', 6),
 (8, 'Callahan', 10276, 'Ikura', 15),
 (8, 'Callahan', 10276, 'Konbu', 10),
 (2, 'Fuller', 10277, 'Rössle Sauerkraut', 20),
 (2, 'Fuller', 10277, 'Tarte au sucre', 12),
 (8, 'Callahan', 10278, 'Gula Malacca', 16),
 (8, 'Callahan', 10278, 'Raclette Courdavault', 15),
 (8, 'Callahan', 10278, 'Vegie-spread', 8),
 (8, 'Callahan', 10278, 'Röd Kaviar', 25),
 (8, 'Callahan', 10279, 'Alice Mutton', 15),
 (2, 'Fuller', 10280, 'Guaraná Fantástica', 12),
 (2, 'Fuller', 10280, 'Pâté chinois', 20),
 (2, 'Fuller', 10280, 'Rhönbräu Klosterbier', 30),
 (4, 'Peacock', 10281, 'Teatime Chocolate Biscuits', 1),
 (4, 'Peacock', 10281, 'Guaraná Fantástica', 6),
 (4, 'Peacock', 10281, 'Steeleye Stout', 4),
 (4, 'Peacock', 10282, 'Nord-Ost Matjeshering', 6),
 (4, 'Peacock', 10282, 'Ravioli Angelo', 2),
 (3, 'Leverling', 10283, 'Genen Shouyu', 20),
 (3, 'Leverling', 10283, 'Teatime Chocolate Biscuits', 18),
 (3, 'Leverling', 10283, 'Camembert Pierrot', 35),
 (3, 'Leverling', 10283, 'Mozzarella di Giovanni', 3),
 (4, 'Peacock', 10284, 'Schoggi Schokolade', 15),
 (4, 'Peacock', 10284, 'Gula Malacca', 21),
 (4, 'Peacock', 10284, 'Camembert Pierrot', 20),
 (4, 'Peacock', 10284, 'Laughing Lumberjack Lager', 5),
 (1, 'Davolio', 10285, 'Chai', 45),
 (1, 'Davolio', 10285, 'Boston Crab Meat', 40),
 (1, 'Davolio', 10285, 'Perth Pasties', 36),
 (8, 'Callahan', 10286, 'Steeleye Stout', 100),
 (8, 'Callahan', 10286, 'Tarte au sucre', 40),
 (8, 'Callahan', 10287, 'Pavlova', 40),
 (8, 'Callahan', 10287, 'Sasquatch Ale', 20),
 (8, 'Callahan', 10287, 'Spegesild', 15),
 (4, 'Peacock', 10288, 'Tourtière', 10),
 (4, 'Peacock', 10288, 'Scottish Longbreads', 3),
 (7, 'King', 10289, 'Aniseed Syrup', 30),
 (7, 'King', 10289, 'Wimmers gute Semmelknödel', 9),
 (8, 'Callahan', 10290, "Chef Anton's Gumbo Mix", 20),
 (8, 'Callahan', 10290, 'Thüringer Rostbratwurst', 15),
 (8, 'Callahan', 10290, 'Maxilaku', 15),
 (8, 'Callahan', 10290, 'Original Frankfurter grüne Soße', 10),
 (6, 'Suyama', 10291, 'Konbu', 20),
 (6, 'Suyama', 10291, 'Gula Malacca', 24),
 (6, 'Suyama', 10291, 'Manjimup Dried Apples', 2),
 (1, 'Davolio', 10292, "Sir Rodney's Marmalade", 20),
 (1, 'Davolio', 10293, 'Carnarvon Tigers', 12),
 (1, 'Davolio', 10293, 'Guaraná Fantástica', 10),
 (1, 'Davolio', 10293, 'Vegie-spread', 5),
 (1, 'Davolio', 10293, 'Rhönbräu Klosterbier', 6),
 (4, 'Peacock', 10294, 'Chai', 18),
 (4, 'Peacock', 10294, 'Alice Mutton', 15),
 (4, 'Peacock', 10294, 'Ipoh Coffee', 15),
 (4, 'Peacock', 10294, 'Camembert Pierrot', 21),
 (4, 'Peacock', 10294, 'Rhönbräu Klosterbier', 6),
 (2, 'Fuller', 10295, 'Gnocchi di nonna Alice', 4),
 (6, 'Suyama', 10296, 'Queso Cabrales', 12),
 (6, 'Suyama', 10296, 'Pavlova', 30),
 (6, 'Suyama', 10296, 'Gudbrandsdalsost', 15),
 (5, 'Buchanan', 10297, 'Chartreuse verte', 60),
 (5, 'Buchanan', 10297, 'Mozzarella di Giovanni', 20),
 (6, 'Suyama', 10298, 'Chang', 40),
 (6, 'Suyama', 10298, 'Inlagd Sill', 40),
 (6, 'Suyama', 10298, 'Raclette Courdavault', 30),
 (6, 'Suyama', 10298, 'Tarte au sucre', 15),
 (4, 'Peacock', 10299, 'Teatime Chocolate Biscuits', 15),
 (4, 'Peacock', 10299, 'Outback Lager', 20),
 (2, 'Fuller', 10300, 'Louisiana Hot Spiced Okra', 30),
 (2, 'Fuller', 10300, 'Scottish Longbreads', 20),
 (8, 'Callahan', 10301, 'Boston Crab Meat', 10),
 (8, 'Callahan', 10301, 'Gnocchi di nonna Alice', 20),
 (4, 'Peacock', 10302, 'Alice Mutton', 40),
 (4, 'Peacock', 10302, 'Rössle Sauerkraut', 28),
 (4, 'Peacock', 10302, 'Ipoh Coffee', 12),
 (7, 'King', 10303, 'Boston Crab Meat', 40),
 (7, 'King', 10303, 'Louisiana Fiery Hot Pepper Sauce', 30),
 (7, 'King', 10303, 'Scottish Longbreads', 15),
 (1, 'Davolio', 10304, 'Maxilaku', 30),
 (1, 'Davolio', 10304, 'Raclette Courdavault', 10),
 (1, 'Davolio', 10304, 'Flotemysost', 2),
 (8, 'Callahan', 10305, 'Carnarvon Tigers', 25),
 (8, 'Callahan', 10305, 'Thüringer Rostbratwurst', 25),
 (8, 'Callahan', 10305, 'Chartreuse verte', 30),
 (1, 'Davolio', 10306, 'Nord-Ost Matjeshering', 10),
 (1, 'Davolio', 10306, 'Perth Pasties', 10),
 (1, 'Davolio', 10306, 'Tourtière', 5),
 (2, 'Fuller', 10307, 'Tarte au sucre', 10),
 (2, 'Fuller', 10307, 'Scottish Longbreads', 3),
 (7, 'King', 10308, 'Gudbrandsdalsost', 1),
 (7, 'King', 10308, 'Outback Lager', 5),
 (3, 'Leverling', 10309, "Chef Anton's Cajun Seasoning", 20),
 (3, 'Leverling', 10309, "Grandma's Boysenberry Spread", 30),
 (3, 'Leverling', 10309, 'Singaporean Hokkien Fried Mee', 2),
 (3, 'Leverling', 10309, 'Ipoh Coffee', 20),
 (3, 'Leverling', 10309, 'Flotemysost', 3),
 (8, 'Callahan', 10310, 'Pavlova', 10),
 (8, 'Callahan', 10310, 'Tarte au sucre', 5),
 (1, 'Davolio', 10311, 'Singaporean Hokkien Fried Mee', 6),
 (1, 'Davolio', 10311, 'Gudbrandsdalsost', 7),
 (2, 'Fuller', 10312, 'Rössle Sauerkraut', 4),
 (2, 'Fuller', 10312, 'Ipoh Coffee', 24),
 (2, 'Fuller', 10312, 'Perth Pasties', 20),
 (2, 'Fuller', 10312, 'Rhönbräu Klosterbier', 10),
 (2, 'Fuller', 10313, 'Inlagd Sill', 12),
 (1, 'Davolio', 10314, 'Mascarpone Fabioli', 40),
 (1, 'Davolio', 10314, 'Escargots de Bourgogne', 30),
 (1, 'Davolio', 10314, 'Tarte au sucre', 25),
 (4, 'Peacock', 10315, 'Sasquatch Ale', 14),
 (4, 'Peacock', 10315, 'Outback Lager', 30),
 (1, 'Davolio', 10316, "Jack's New England Clam Chowder", 10),
 (1, 'Davolio', 10316, 'Tarte au sucre', 70),
 (6, 'Suyama', 10317, 'Chai', 20),
 (8, 'Callahan', 10318, "Jack's New England Clam Chowder", 20),
 (8, 'Callahan', 10318, 'Lakkalikööri', 6),
 (7, 'King', 10319, 'Alice Mutton', 8),
 (7, 'King', 10319, 'Rössle Sauerkraut', 14),
 (7, 'King', 10319, 'Lakkalikööri', 30),
 (5, 'Buchanan', 10320, 'Flotemysost', 30),
 (3, 'Leverling', 10321, 'Steeleye Stout', 10),
 (7, 'King', 10322, 'Filo Mix', 20),
 (4, 'Peacock', 10323, 'Genen Shouyu', 5),
 (4, 'Peacock', 10323, 'NuNuCa Nuß-Nougat-Creme', 4),
 (4, 'Peacock', 10323, 'Chartreuse verte', 4),
 (9, 'Dodsworth', 10324, 'Pavlova', 21),
 (9, 'Dodsworth', 10324, 'Steeleye Stout', 70),
 (9, 'Dodsworth', 10324, 'Spegesild', 30),
 (9, 'Dodsworth', 10324, 'Raclette Courdavault', 40),
 (9, 'Dodsworth', 10324, 'Vegie-spread', 80),
 (1, 'Davolio', 10325, "Grandma's Boysenberry Spread", 6),
 (1, 'Davolio', 10325, 'Konbu', 12),
 (1, 'Davolio', 10325, 'Tofu', 9),
 (1, 'Davolio', 10325, 'Gorgonzola Telino', 4),
 (1, 'Davolio', 10325, 'Mozzarella di Giovanni', 40),
 (4, 'Peacock', 10326, "Chef Anton's Cajun Seasoning", 24),
 (4, 'Peacock', 10326, 'Ravioli Angelo', 16),
 (4, 'Peacock', 10326, 'Rhönbräu Klosterbier', 50),
 (2, 'Fuller', 10327, 'Chang', 25),
 (2, 'Fuller', 10327, 'Queso Cabrales', 50),
 (2, 'Fuller', 10327, 'Nord-Ost Matjeshering', 35),
 (2, 'Fuller', 10327, 'Escargots de Bourgogne', 30),
 (4, 'Peacock', 10328, 'Raclette Courdavault', 9),
 (4, 'Peacock', 10328, 'Louisiana Fiery Hot Pepper Sauce', 40),
 (4, 'Peacock', 10328, 'Scottish Longbreads', 10),
 (4, 'Peacock', 10329, 'Teatime Chocolate Biscuits', 10),
 (4, 'Peacock', 10329, 'Nord-Ost Matjeshering', 8),
 (4, 'Peacock', 10329, 'Côte de Blaye', 20),
 (4, 'Peacock', 10329, 'Gnocchi di nonna Alice', 12),
 (3, 'Leverling', 10330, 'Gumbär Gummibärchen', 50),
 (3, 'Leverling', 10330, 'Mozzarella di Giovanni', 25),
 (9, 'Dodsworth', 10331, 'Tourtière', 15),
 (3, 'Leverling', 10332, 'Carnarvon Tigers', 40),
 (3, 'Leverling', 10332, 'Singaporean Hokkien Fried Mee', 10),
 (3, 'Leverling', 10332, 'Zaanse koeken', 16),
 (5, 'Buchanan', 10333, 'Tofu', 10),
 (5, 'Buchanan', 10333, "Sir Rodney's Scones", 10),
 (5, 'Buchanan', 10333, 'Flotemysost', 40),
 (8, 'Callahan', 10334, 'Filo Mix', 8),
 (8, 'Callahan', 10334, 'Scottish Longbreads', 10),
 (7, 'King', 10335, 'Chang', 7),
 (7, 'King', 10335, 'Gorgonzola Telino', 25),
 (7, 'King', 10335, 'Mascarpone Fabioli', 6),
 (7, 'King', 10335, 'Manjimup Dried Apples', 48),
 (7, 'King', 10336, "Chef Anton's Cajun Seasoning", 18),
 (4, 'Peacock', 10337, 'Tunnbröd', 40),
 (4, 'Peacock', 10337, 'Gumbär Gummibärchen', 24),
 (4, 'Peacock', 10337, 'Inlagd Sill', 20),
 (4, 'Peacock', 10337, 'Gravad lax', 28),
 (4, 'Peacock', 10337, 'Mozzarella di Giovanni', 25),
 (4, 'Peacock', 10338, 'Alice Mutton', 20),
 (4, 'Peacock', 10338, 'Nord-Ost Matjeshering', 15),
 (2, 'Fuller', 10339, "Chef Anton's Cajun Seasoning", 10),
 (2, 'Fuller', 10339, 'Alice Mutton', 70),
 (2, 'Fuller', 10339, 'Tarte au sucre', 28),
 (1, 'Davolio', 10340, 'Carnarvon Tigers', 20),
 (1, 'Davolio', 10340, "Jack's New England Clam Chowder", 12),
 (1, 'Davolio', 10340, 'Ipoh Coffee', 40),
 (7, 'King', 10341, 'Geitost', 8),
 (7, 'King', 10341, 'Raclette Courdavault', 9),
 (4, 'Peacock', 10342, 'Chang', 24),
 (4, 'Peacock', 10342, 'Gorgonzola Telino', 56),
 (4, 'Peacock', 10342, 'Inlagd Sill', 40),
 (4, 'Peacock', 10342, 'Pâté chinois', 40),
 (4, 'Peacock', 10343, 'Wimmers gute Semmelknödel', 50),
 (4, 'Peacock', 10343, 'Scottish Longbreads', 4),
 (4, 'Peacock', 10343, 'Lakkalikööri', 15),
 (4, 'Peacock', 10344, "Chef Anton's Cajun Seasoning", 35),
 (4, 'Peacock', 10344, 'Northwoods Cranberry Sauce', 70),
 (2, 'Fuller', 10345, 'Northwoods Cranberry Sauce', 70),
 (2, 'Fuller', 10345, 'Teatime Chocolate Biscuits', 80),
 (2, 'Fuller', 10345, 'Singaporean Hokkien Fried Mee', 9),
 (3, 'Leverling', 10346, 'Alice Mutton', 36),
 (3, 'Leverling', 10346, 'Gnocchi di nonna Alice', 20),
 (4, 'Peacock', 10347, 'NuNuCa Nuß-Nougat-Creme', 10),
 (4, 'Peacock', 10347, 'Chartreuse verte', 50),
 (4, 'Peacock', 10347, 'Boston Crab Meat', 4),
 (4, 'Peacock', 10347, 'Rhönbräu Klosterbier', 6),
 (4, 'Peacock', 10348, 'Chai', 15),
 (4, 'Peacock', 10348, 'Tunnbröd', 25),
 (7, 'King', 10349, 'Tourtière', 24),
 (6, 'Suyama', 10350, 'Valkoinen suklaa', 15),
 (6, 'Suyama', 10350, 'Gudbrandsdalsost', 18),
 (1, 'Davolio', 10351, 'Côte de Blaye', 20),
 (1, 'Davolio', 10351, "Jack's New England Clam Chowder", 13),
 (1, 'Davolio', 10351, 'Gula Malacca', 77),
 (1, 'Davolio', 10351, 'Louisiana Fiery Hot Pepper Sauce', 10),
 (3, 'Leverling', 10352, 'Guaraná Fantástica', 10),
 (3, 'Leverling', 10352, 'Tourtière', 20),
 (7, 'King', 10353, 'Queso Cabrales', 12),
 (7, 'King', 10353, 'Côte de Blaye', 50),
 (8, 'Callahan', 10354, 'Chai', 12),
 (8, 'Callahan', 10354, 'Thüringer Rostbratwurst', 4),
 (6, 'Suyama', 10355, 'Guaraná Fantástica', 25),
 (6, 'Suyama', 10355, 'Ravioli Angelo', 25),
 (6, 'Suyama', 10356, 'Gorgonzola Telino', 30),
 (6, 'Suyama', 10356, 'Pâté chinois', 12),
 (6, 'Suyama', 10356, 'Gudbrandsdalsost', 20),
 (1, 'Davolio', 10357, 'Ikura', 30),
 (1, 'Davolio', 10357, 'Gumbär Gummibärchen', 16),
 (1, 'Davolio', 10357, 'Camembert Pierrot', 8),
 (5, 'Buchanan', 10358, 'Guaraná Fantástica', 10),
 (5, 'Buchanan', 10358, 'Sasquatch Ale', 10),
 (5, 'Buchanan', 10358, 'Inlagd Sill', 20),
 (5, 'Buchanan', 10359, 'Pavlova', 56),
 (5, 'Buchanan', 10359, 'Gorgonzola Telino', 70),
 (5, 'Buchanan', 10359, 'Camembert Pierrot', 80),
 (4, 'Peacock', 10360, 'Rössle Sauerkraut', 30),
 (4, 'Peacock', 10360, 'Thüringer Rostbratwurst', 35),
 (4, 'Peacock', 10360, 'Côte de Blaye', 10),
 (4, 'Peacock', 10360, 'Maxilaku', 35),
 (4, 'Peacock', 10360, 'Tourtière', 28),
 (1, 'Davolio', 10361, 'Chartreuse verte', 54),
 (1, 'Davolio', 10361, 'Camembert Pierrot', 55),
 (3, 'Leverling', 10362, 'NuNuCa Nuß-Nougat-Creme', 50),
 (3, 'Leverling', 10362, 'Manjimup Dried Apples', 20),
 (3, 'Leverling', 10362, 'Tourtière', 24),
 (4, 'Peacock', 10363, 'Gorgonzola Telino', 20),
 (4, 'Peacock', 10363, 'Rhönbräu Klosterbier', 12),
 (4, 'Peacock', 10363, 'Lakkalikööri', 12),
 (1, 'Davolio', 10364, 'Gudbrandsdalsost', 30),
 (1, 'Davolio', 10364, 'Flotemysost', 5),
 (3, 'Leverling', 10365, 'Queso Cabrales', 24),
 (8, 'Callahan', 10366, 'Louisiana Fiery Hot Pepper Sauce', 5),
 (8, 'Callahan', 10366, 'Original Frankfurter grüne Soße', 5),
 (7, 'King', 10367, 'Sasquatch Ale', 36),
 (7, 'King', 10367, 'Tourtière', 18),
 (7, 'King', 10367, 'Louisiana Fiery Hot Pepper Sauce', 15),
 (7, 'King', 10367, 'Original Frankfurter grüne Soße', 7),
 (2, 'Fuller', 10368, "Sir Rodney's Scones", 5),
 (2, 'Fuller', 10368, 'Rössle Sauerkraut', 13),
 (2, 'Fuller', 10368, 'Ravioli Angelo', 25),
 (2, 'Fuller', 10368, 'Wimmers gute Semmelknödel', 35),
 (8, 'Callahan', 10369, 'Thüringer Rostbratwurst', 20),
 (8, 'Callahan', 10369, 'Gnocchi di nonna Alice', 18),
 (6, 'Suyama', 10370, 'Chai', 15),
 (6, 'Suyama', 10370, 'Wimmers gute Semmelknödel', 30),
 (6, 'Suyama', 10370, 'Longlife Tofu', 20),
 (1, 'Davolio', 10371, 'Inlagd Sill', 6),
 (5, 'Buchanan', 10372, "Sir Rodney's Marmalade", 12),
 (5, 'Buchanan', 10372, 'Côte de Blaye', 40),
 (5, 'Buchanan', 10372, 'Camembert Pierrot', 70),
 (5, 'Buchanan', 10372, 'Mozzarella di Giovanni', 42),
 (4, 'Peacock', 10373, 'Escargots de Bourgogne', 80),
 (4, 'Peacock', 10373, 'Flotemysost', 50),
 (1, 'Davolio', 10374, 'Gorgonzola Telino', 30),
 (1, 'Davolio', 10374, 'Escargots de Bourgogne', 15),
 (3, 'Leverling', 10375, 'Tofu', 15),
 (3, 'Leverling', 10375, 'Tourtière', 10),
 (1, 'Davolio', 10376, 'Gorgonzola Telino', 42),
 (1, 'Davolio', 10377, 'Rössle Sauerkraut', 20),
 (1, 'Davolio', 10377, 'Chartreuse verte', 20),
 (5, 'Buchanan', 10378, 'Flotemysost', 6),
 (2, 'Fuller', 10379, "Jack's New England Clam Chowder", 8),
 (2, 'Fuller', 10379, 'Vegie-spread', 16),
 (2, 'Fuller', 10379, 'Louisiana Fiery Hot Pepper Sauce', 20),
 (8, 'Callahan', 10380, 'Nord-Ost Matjeshering', 18),
 (8, 'Callahan', 10380, 'Perth Pasties', 20),
 (8, 'Callahan', 10380, 'Camembert Pierrot', 6),
 (8, 'Callahan', 10380, 'Outback Lager', 30),
 (3, 'Leverling', 10381, 'Longlife Tofu', 14),
 (4, 'Peacock', 10382, "Chef Anton's Gumbo Mix", 32),
 (4, 'Peacock', 10382, 'Carnarvon Tigers', 9),
 (4, 'Peacock', 10382, 'Thüringer Rostbratwurst', 14),
 (4, 'Peacock', 10382, 'Geitost', 60),
 (4, 'Peacock', 10382, 'Longlife Tofu', 50),
 (8, 'Callahan', 10383, 'Konbu', 20),
 (8, 'Callahan', 10383, 'Valkoinen suklaa', 15),
 (8, 'Callahan', 10383, 'Gnocchi di nonna Alice', 20),
 (3, 'Leverling', 10384, "Sir Rodney's Marmalade", 28),
 (3, 'Leverling', 10384, 'Camembert Pierrot', 15),
 (1, 'Davolio', 10385, "Uncle Bob's Organic Dried Pears", 10),
 (1, 'Davolio', 10385, 'Camembert Pierrot', 20),
 (1, 'Davolio', 10385, 'Scottish Longbreads', 8),
 (9, 'Dodsworth', 10386, 'Guaraná Fantástica', 15),
 (9, 'Dodsworth', 10386, 'Sasquatch Ale', 10),
 (1, 'Davolio', 10387, 'Guaraná Fantástica', 15),
 (1, 'Davolio', 10387, 'Rössle Sauerkraut', 6),
 (1, 'Davolio', 10387, 'Raclette Courdavault', 12),
 (1, 'Davolio', 10387, 'Flotemysost', 15),
 (2, 'Fuller', 10388, 'Rogede sild', 15),
 (2, 'Fuller', 10388, 'Filo Mix', 20),
 (2, 'Fuller', 10388, 'Perth Pasties', 40),
 (4, 'Peacock', 10389, 'Ikura', 16),
 (4, 'Peacock', 10389, 'Pâté chinois', 15),
 (4, 'Peacock', 10389, 'Tarte au sucre', 20),
 (4, 'Peacock', 10389, 'Outback Lager', 30),
 (6, 'Suyama', 10390, 'Gorgonzola Telino', 60),
 (6, 'Suyama', 10390, 'Steeleye Stout', 40),
 (6, 'Suyama', 10390, 'Spegesild', 45),
 (6, 'Suyama', 10390, 'Mozzarella di Giovanni', 24),
 (3, 'Leverling', 10391, 'Konbu', 18),
 (2, 'Fuller', 10392, 'Gudbrandsdalsost', 50),
 (1, 'Davolio', 10393, 'Chang', 25),
 (1, 'Davolio', 10393, 'Tofu', 42),
 (1, 'Davolio', 10393, 'NuNuCa Nuß-Nougat-Creme', 7),
 (1, 'Davolio', 10393, 'Gumbär Gummibärchen', 70),
 (1, 'Davolio', 10393, 'Gorgonzola Telino', 32),
 (1, 'Davolio', 10394, 'Konbu', 10),
 (1, 'Davolio', 10394, 'Tarte au sucre', 10),
 (6, 'Suyama', 10395, 'Spegesild', 28),
 (6, 'Suyama', 10395, 'Perth Pasties', 70),
 (6, 'Suyama', 10395, 'Gudbrandsdalsost', 8),
 (1, 'Davolio', 10396, 'Tunnbröd', 40),
 (1, 'Davolio', 10396, 'Flotemysost', 60),
 (1, 'Davolio', 10396, 'Mozzarella di Giovanni', 21),
 (5, 'Buchanan', 10397, "Sir Rodney's Scones", 10),
 (5, 'Buchanan', 10397, 'Manjimup Dried Apples', 18),
 (2, 'Fuller', 10398, 'Steeleye Stout', 30),
 (2, 'Fuller', 10398, 'Pâté chinois', 120),
 (8, 'Callahan', 10399, 'Scottish Longbreads', 60),
 (8, 'Callahan', 10399, 'Flotemysost', 30),
 (8, 'Callahan', 10399, 'Lakkalikööri', 35),
 (8, 'Callahan', 10399, 'Original Frankfurter grüne Soße', 14),
 (1, 'Davolio', 10400, 'Thüringer Rostbratwurst', 21),
 (1, 'Davolio', 10400, 'Steeleye Stout', 35),
 (1, 'Davolio', 10400, 'Maxilaku', 30),
 (1, 'Davolio', 10401, 'Nord-Ost Matjeshering', 18),
 (1, 'Davolio', 10401, 'Gnocchi di nonna Alice', 70),
 (1, 'Davolio', 10401, 'Louisiana Fiery Hot Pepper Sauce', 20),
 (1, 'Davolio', 10401, 'Flotemysost', 60),
 (8, 'Callahan', 10402, 'Tunnbröd', 60),
 (8, 'Callahan', 10402, 'Vegie-spread', 65),

## M30. Customers who never work with any employees of the trade company \[read data\]

In [7]:
%load_ext sql
%sql mssql+pyodbc://sa:1234@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC+Driver+13+for+SQL+Server

'Connected: sa@NorthWind2016'

In [77]:
%%sql
SELECT Customers_CustomerID = Customers.CustomerID, Orders_CustomerID = Orders.CustomerID, Orders.EmployeeID
FROM Customers
    LEFT JOIN Orders
    ON Orders.CustomerID = Customers.CustomerID
WHERE Orders.CustomerID IS NULL;

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('PARIS', None, None), ('FISSA', None, None)]

## M31. Customers who never work with employee \#4

In [80]:
%%sql
SELECT Customers.CustomerID, Orders.CustomerID
FROM Customers
    LEFT JOIN Orders
    ON Orders.CustomerID = Customers.CustomerID AND Orders.EmployeeID = 4
WHERE Orders.CustomerID IS NULL

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('SEVES', None, None),
 ('THEBI', None, None),
 ('LAZYK', None, None),
 ('GROSR', None, None),
 ('PARIS', None, None),
 ('FISSA', None, None),
 ('SPECD', None, None),
 ('LAUGB', None, None),
 ('PRINI', None, None),
 ('VINET', None, None),
 ('FRANR', None, None),
 ('CONSH', None, None),
 ('NORTS', None, None),
 ('PERIC', None, None),
 ('DUMON', None, None),
 ('SANTG', None, None)]

## M32. Conditional selection
Customers who ever made a `single` order worht of more than \$10000 in 2016.

In [81]:
%%sql 
SELECT Customers.CustomerID, Customers.CompanyName, Orders.OrderID, TotalOrderAmount = SUM(Quantity * UnitPrice)
FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
WHERE OrderDate BETWEEN '2016-01-01' AND '2017-01-01'
GROUP BY Customers.CustomerID, Customers.CompanyName, Orders.Orderid
HAVING SUM(Quantity * UnitPrice) > 10000
ORDER BY TotalOrderAmount DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('QUICK', 'QUICK-Stop', 10865, Decimal('17250.0000')),
 ('SAVEA', 'Save-a-lot Markets', 11030, Decimal('16321.9000')),
 ('HANAR', 'Hanari Carnes', 10981, Decimal('15810.0000')),
 ('KOENE', 'Königlich Essen', 10817, Decimal('11490.7000')),
 ('RATTC', 'Rattlesnake Canyon Grocery', 10889, Decimal('11380.0000')),
 ('HUNGO', 'Hungry Owl All-Night Grocers', 10897, Decimal('10835.2400'))]

## M33. Conditional Selection (continued)
Show customers whose total purchase exceeds $15000 in 2016.

In [82]:
%%sql 
SELECT Customers.CustomerID, Customers.CompanyName, TotalOrderAmount = SUM(Quantity * UnitPrice)
FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
WHERE OrderDate BETWEEN '2016-01-01' AND '2017-01-01'
GROUP BY Customers.CustomerID, Customers.CompanyName ---remove this feature Orders.Orderid
HAVING SUM(Quantity * UnitPrice) > 10000
ORDER BY TotalOrderAmount DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('SAVEA', 'Save-a-lot Markets', Decimal('42806.2500')),
 ('ERNSH', 'Ernst Handel', Decimal('42598.9000')),
 ('QUICK', 'QUICK-Stop', Decimal('40526.9900')),
 ('HANAR', 'Hanari Carnes', Decimal('24238.0500')),
 ('HUNGO', 'Hungry Owl All-Night Grocers', Decimal('22796.3400')),
 ('RATTC', 'Rattlesnake Canyon Grocery', Decimal('21725.6000')),
 ('KOENE', 'Königlich Essen', Decimal('20204.9500')),
 ('FOLKO', 'Folk och fä HB', Decimal('15973.8500')),
 ('WHITC', 'White Clover Markets', Decimal('15278.9000')),
 ('BOTTM', 'Bottom-Dollar Markets', Decimal('12227.4000')),
 ('SUPRD', 'Suprêmes délices', Decimal('11862.5000')),
 ('GREAL', 'Great Lakes Food Market', Decimal('10562.5800')),
 ('LINOD', 'LINO-Delicateses', Decimal('10085.6000'))]

## M34. Conditional selection (continued)
Take the discount into consideration when calculating high-value customers

In [83]:
%%sql 
SELECT Customers.CustomerID, Customers.CompanyName, TotalsWithoutDiscount = SUM(Quantity * UnitPrice),  TotalsWithDiscount = SUM(Quantity * UnitPrice * (1 - Discount))
FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
WHERE OrderDate BETWEEN '2016-01-01' AND '2017-01-01'
GROUP BY Customers.CustomerID, Customers.CompanyName ---remove this feature Orders.Orderid
HAVING SUM(Quantity * UnitPrice) > 10000
ORDER BY TotalsWithDiscount DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[('ERNSH', 'Ernst Handel', Decimal('42598.9000'), 41210.65002441406),
 ('QUICK', 'QUICK-Stop', Decimal('40526.9900'), 37217.315002441406),
 ('SAVEA', 'Save-a-lot Markets', Decimal('42806.2500'), 36310.10977935791),
 ('HANAR', 'Hanari Carnes', Decimal('24238.0500'), 23821.199989318848),
 ('RATTC', 'Rattlesnake Canyon Grocery', Decimal('21725.6000'), 21238.270441055298),
 ('HUNGO', 'Hungry Owl All-Night Grocers', Decimal('22796.3400'), 20402.11993408203),
 ('KOENE', 'Königlich Essen', Decimal('20204.9500'), 19582.773986816406),
 ('WHITC', 'White Clover Markets', Decimal('15278.9000'), 15278.89998626709),
 ('FOLKO', 'Folk och fä HB', Decimal('15973.8500'), 13644.067497253418),
 ('SUPRD', 'Suprêmes délices', Decimal('11862.5000'), 11644.599998474121),
 ('BOTTM', 'Bottom-Dollar Markets', Decimal('12227.4000'), 11338.550048828125),
 ('GREAL', 'Great Lakes Food Market', Decimal('10562.5800'), 9942.135009765625),
 ('LINOD', 'LINO-Delicateses', Decimal('10085.6000'), 9117.090065002441)]

## M35. Datetime function
Show the sales at the end of the month.

In [84]:
%%sql
SELECT EmployeeID, OrderID, OrderDate
FROM Orders
WHERE OrderDate = EOMONTH(OrderDate)
ORDER BY EmployeeID, OrderID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(1, 10461, datetime.datetime(2015, 2, 28, 0, 0)),
 (1, 10616, datetime.datetime(2015, 7, 31, 0, 0)),
 (2, 10583, datetime.datetime(2015, 6, 30, 0, 0)),
 (2, 10686, datetime.datetime(2015, 9, 30, 0, 0)),
 (2, 10989, datetime.datetime(2016, 3, 31, 0, 0)),
 (2, 11060, datetime.datetime(2016, 4, 30, 0, 0)),
 (3, 10432, datetime.datetime(2015, 1, 31, 0, 0)),
 (3, 10988, datetime.datetime(2016, 3, 31, 0, 0)),
 (3, 11063, datetime.datetime(2016, 4, 30, 0, 0)),
 (4, 10343, datetime.datetime(2014, 10, 31, 0, 0)),
 (4, 10522, datetime.datetime(2015, 4, 30, 0, 0)),
 (4, 10584, datetime.datetime(2015, 6, 30, 0, 0)),
 (4, 10617, datetime.datetime(2015, 7, 31, 0, 0)),
 (4, 10725, datetime.datetime(2015, 10, 31, 0, 0)),
 (4, 11061, datetime.datetime(2016, 4, 30, 0, 0)),
 (4, 11062, datetime.datetime(2016, 4, 30, 0, 0)),
 (5, 10269, datetime.datetime(2014, 7, 31, 0, 0)),
 (6, 10317, datetime.datetime(2014, 9, 30, 0, 0)),
 (7, 10490, datetime.datetime(2015, 3, 31, 0, 0)),
 (8, 10399, datetime.datetime(2014, 12, 31, 0, 0)),
 (8, 10460, datetime.datetime(2015, 2, 28, 0, 0)),
 (8, 10491, datetime.datetime(2015, 3, 31, 0, 0)),
 (8, 10987, datetime.datetime(2016, 3, 31, 0, 0)),
 (9, 10687, datetime.datetime(2015, 9, 30, 0, 0))]

## M36. Most frequent
Show the 10 orders with the most line items, in order of total line items.

In [87]:
%%sql
SELECT TOP 10 Orders.OrderID, TotalOrderDetails = COUNT(*)
FROM Orders 
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
GROUP BY Orders.OrderID
ORDER BY COUNT(*) DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(11077, 25),
 (10979, 6),
 (10657, 6),
 (10847, 6),
 (10845, 5),
 (10836, 5),
 (10714, 5),
 (10670, 5),
 (10691, 5),
 (10698, 5)]

## M37. Data raffling
Show a random set of 2\% of all orders.
Reference: [NewID](https://www.techrepublic.com/article/generate-random-sets-in-sql-server-with-newid/)()

In [88]:
%%sql
SELECT TOP 2 PERCENT OrderID
FROM Orders
ORDER BY NewID()

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10849,),
 (10260,),
 (10879,),
 (10865,),
 (10354,),
 (10745,),
 (10642,),
 (10749,),
 (10431,),
 (10797,),
 (10734,),
 (10772,),
 (10463,),
 (10775,),
 (10643,),
 (10567,),
 (10604,)]

## M38. Identifying duplicates
The HAVING clause was added to SQL because the WHERE keyword could not be used with aggregate functions.

In [89]:
%%sql
SELECT OrderID
FROM OrderDetails
WHERE Quantity >=60 -- the salesperson said the vaolume of the duplicats exceed 60. 
GROUP BY OrderID, Quantity
HAVING Count(*) > 1

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10263,), (10263,), (10990,), (10658,), (11030,)]

## M39. Derived tables
Show the details of the duplicated items (continued).

The first part deals with the duplicated items. <br>
The second part shows the details of the identified duplicates. <br>

In [95]:
%%sql
; WITH PotentialDuplicates AS(
    SELECT OrderID
    FROM OrderDetails
    WHERE Quantity >= 60
    GROUP BY OrderID, Quantity
    HAVING COUNT(*) > 1
)

SELECT OrderID, ProductID, UnitPrice, Quantity, Discount
FROM OrderDetails
WHERE OrderID IN (SELECT OrderID FROM PotentialDuplicates)
ORDER BY OrderID, Quantity

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(10263, 16, Decimal('13.9000'), 60, 0.25),
 (10263, 30, Decimal('20.7000'), 60, 0.25),
 (10263, 24, Decimal('3.6000'), 65, 0.0),
 (10263, 74, Decimal('8.0000'), 65, 0.25),
 (10658, 60, Decimal('34.0000'), 55, 0.05000000074505806),
 (10658, 21, Decimal('10.0000'), 60, 0.0),
 (10658, 40, Decimal('18.4000'), 70, 0.05000000074505806),
 (10658, 77, Decimal('13.0000'), 70, 0.05000000074505806),
 (10990, 34, Decimal('14.0000'), 60, 0.15000000596046448),
 (10990, 21, Decimal('10.0000'), 65, 0.0),
 (10990, 55, Decimal('24.0000'), 65, 0.15000000596046448),
 (10990, 61, Decimal('28.5000'), 66, 0.15000000596046448),
 (11030, 29, Decimal('123.7900'), 60, 0.25),
 (11030, 5, Decimal('21.3500'), 70, 0.0),
 (11030, 2, Decimal('19.0000'), 100, 0.25),
 (11030, 59, Decimal('55.0000'), 100, 0.25)]

## M40. Equivalent to M39.

In [102]:
%%sql
SELECT OrderDetails.OrderID, ProductID, UnitPrice, Quantity, Discount
FROM OrderDetails
    JOIN (
        SELECT DISTINCT OrderID --<<<<
        FROM OrderDetails
        WHERE Quantity >= 60
        GROUP BY OrderID, Quantity
        HAVING COUNT(*) > 1
    ) PotentialProblemOrders
    On PotentialProblemOrders.OrderID = OrderDetails.OrderID
ORDER BY OrderID, ProductID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10263, 16, Decimal('13.9000'), 60, 0.25),
 (10263, 24, Decimal('3.6000'), 65, 0.0),
 (10263, 30, Decimal('20.7000'), 60, 0.25),
 (10263, 74, Decimal('8.0000'), 65, 0.25),
 (10658, 21, Decimal('10.0000'), 60, 0.0),
 (10658, 40, Decimal('18.4000'), 70, 0.05000000074505806),
 (10658, 60, Decimal('34.0000'), 55, 0.05000000074505806),
 (10658, 77, Decimal('13.0000'), 70, 0.05000000074505806),
 (10990, 21, Decimal('10.0000'), 65, 0.0),
 (10990, 34, Decimal('14.0000'), 60, 0.15000000596046448),
 (10990, 55, Decimal('24.0000'), 65, 0.15000000596046448),
 (10990, 61, Decimal('28.5000'), 66, 0.15000000596046448),
 (11030, 2, Decimal('19.0000'), 100, 0.25),
 (11030, 5, Decimal('21.3500'), 70, 0.0),
 (11030, 29, Decimal('123.7900'), 60, 0.25),
 (11030, 59, Decimal('55.0000'), 100, 0.25)]

## M41. Datetime function

In [103]:
%%sql
SELECT OrderID, OrderDate = CONVERT(DATE, OrderDate), RequiredDate = CONVERT(DATE, RequiredDate), ShippedDate = CONVERT(DATE, ShippedDate)
FROM Orders
WHERE RequiredDate <= ShippedDate

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(10264, datetime.date(2014, 7, 24), datetime.date(2014, 8, 21), datetime.date(2014, 8, 23)),
 (10271, datetime.date(2014, 8, 1), datetime.date(2014, 8, 29), datetime.date(2014, 8, 30)),
 (10280, datetime.date(2014, 8, 14), datetime.date(2014, 9, 11), datetime.date(2014, 9, 12)),
 (10302, datetime.date(2014, 9, 10), datetime.date(2014, 10, 8), datetime.date(2014, 10, 9)),
 (10309, datetime.date(2014, 9, 19), datetime.date(2014, 10, 17), datetime.date(2014, 10, 23)),
 (10380, datetime.date(2014, 12, 12), datetime.date(2015, 1, 9), datetime.date(2015, 1, 16)),
 (10423, datetime.date(2015, 1, 23), datetime.date(2015, 2, 6), datetime.date(2015, 2, 24)),
 (10427, datetime.date(2015, 1, 27), datetime.date(2015, 2, 24), datetime.date(2015, 3, 3)),
 (10433, datetime.date(2015, 2, 3), datetime.date(2015, 3, 3), datetime.date(2015, 3, 4)),
 (10451, datetime.date(2015, 2, 19), datetime.date(2015, 3, 5), datetime.date(2015, 3, 12)),
 (10483, datetime.date(2015, 3, 24), datetime.date(2015, 4, 21), datetime.date(2015, 4, 25)),
 (10515, datetime.date(2015, 4, 23), datetime.date(2015, 5, 7), datetime.date(2015, 5, 23)),
 (10523, datetime.date(2015, 5, 1), datetime.date(2015, 5, 29), datetime.date(2015, 5, 30)),
 (10545, datetime.date(2015, 5, 22), datetime.date(2015, 6, 19), datetime.date(2015, 6, 26)),
 (10578, datetime.date(2015, 6, 24), datetime.date(2015, 7, 22), datetime.date(2015, 7, 25)),
 (10593, datetime.date(2015, 7, 9), datetime.date(2015, 8, 6), datetime.date(2015, 8, 13)),
 (10596, datetime.date(2015, 7, 11), datetime.date(2015, 8, 8), datetime.date(2015, 8, 12)),
 (10660, datetime.date(2015, 9, 8), datetime.date(2015, 10, 6), datetime.date(2015, 10, 15)),
 (10663, datetime.date(2015, 9, 10), datetime.date(2015, 9, 24), datetime.date(2015, 10, 3)),
 (10687, datetime.date(2015, 9, 30), datetime.date(2015, 10, 28), datetime.date(2015, 10, 30)),
 (10705, datetime.date(2015, 10, 15), datetime.date(2015, 11, 12), datetime.date(2015, 11, 18)),
 (10709, datetime.date(2015, 10, 17), datetime.date(2015, 11, 14), datetime.date(2015, 11, 20)),
 (10726, datetime.date(2015, 11, 3), datetime.date(2015, 11, 17), datetime.date(2015, 12, 5)),
 (10727, datetime.date(2015, 11, 3), datetime.date(2015, 12, 1), datetime.date(2015, 12, 5)),
 (10749, datetime.date(2015, 11, 20), datetime.date(2015, 12, 18), datetime.date(2015, 12, 19)),
 (10777, datetime.date(2015, 12, 15), datetime.date(2015, 12, 29), datetime.date(2016, 1, 21)),
 (10779, datetime.date(2015, 12, 16), datetime.date(2016, 1, 13), datetime.date(2016, 1, 14)),
 (10788, datetime.date(2015, 12, 22), datetime.date(2016, 1, 19), datetime.date(2016, 1, 19)),
 (10807, datetime.date(2015, 12, 31), datetime.date(2016, 1, 28), datetime.date(2016, 1, 30)),
 (10816, datetime.date(2016, 1, 6), datetime.date(2016, 2, 3), datetime.date(2016, 2, 4)),
 (10827, datetime.date(2016, 1, 12), datetime.date(2016, 1, 26), datetime.date(2016, 2, 6)),
 (10828, datetime.date(2016, 1, 13), datetime.date(2016, 1, 27), datetime.date(2016, 2, 4)),
 (10847, datetime.date(2016, 1, 22), datetime.date(2016, 2, 5), datetime.date(2016, 2, 10)),
 (10924, datetime.date(2016, 3, 4), datetime.date(2016, 4, 1), datetime.date(2016, 4, 8)),
 (10927, datetime.date(2016, 3, 5), datetime.date(2016, 4, 2), datetime.date(2016, 4, 8)),
 (10960, datetime.date(2016, 3, 19), datetime.date(2016, 4, 2), datetime.date(2016, 4, 8)),
 (10970, datetime.date(2016, 3, 24), datetime.date(2016, 4, 7), datetime.date(2016, 4, 24)),
 (10978, datetime.date(2016, 3, 26), datetime.date(2016, 4, 23), datetime.date(2016, 4, 23)),
 (10998, datetime.date(2016, 4, 3), datetime.date(2016, 4, 17), datetime.date(2016, 4, 17))]

## M42. Datetime function (continued)
Which salespeople have the most orders being delivered late?

In [105]:
%%sql
SELECT Employees.EmployeeID, LastName, TotalLateOrders = COUNT(*)
FROM Orders
JOIN Employees ON Employees.EmployeeID = Orders.EmployeeID
WHERE RequiredDate <= ShippedDate  
GROUP BY Employees.EmployeeID, Employees.LastName
ORDER BY TotalLateOrders DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
   mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind?driver=ODBC Driver 13 for SQL Server
Done.

[(4, 'Peacock', 10),
 (3, 'Leverling', 5),
 (8, 'Callahan', 5),
 (9, 'Dodsworth', 5),
 (7, 'King', 4),
 (2, 'Fuller', 4),
 (1, 'Davolio', 3),
 (6, 'Suyama', 3)]

## M43. Multiple Derived tables (continued)

In [10]:
%%sql
; WITH LateOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    WHERE RequiredDate <= ShippedDate --<<<
    GROUP BY EmployeeID
)
, AllOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    GROUP BY EmployeeID
)

SELECT Employees.EmployeeID, LastName, AllOrders = AllOrders.TotalOrders, LateOrders = LateOrders.TotalOrders
FROM Employees
JOIN AllOrders ON AllOrders.EmployeeID = Employees.EmployeeID
JOIN LateOrders ON LateOrders.EmployeeID = Employees.EmployeeID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(1, 'Davolio', 123, 3),
 (2, 'Fuller', 96, 4),
 (3, 'Leverling', 127, 5),
 (4, 'Peacock', 156, 10),
 (6, 'Suyama', 67, 3),
 (7, 'King', 72, 4),
 (8, 'Callahan', 104, 5),
 (9, 'Dodsworth', 43, 5)]

## M.44 Left Join (continued)
Some employees are missing from the last result due to wrong merge method.

In [9]:
%%sql
; WITH LateOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    WHERE RequiredDate <= ShippedDate --<<<
    GROUP BY EmployeeID
)
, AllOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    GROUP BY EmployeeID
)

SELECT Employees.EmployeeID, LastName, AllOrders = AllOrders.TotalOrders, LateOrders = LateOrders.TotalOrders
FROM Employees
JOIN AllOrders ON AllOrders.EmployeeID = Employees.EmployeeID
LEFT JOIN LateOrders ON LateOrders.EmployeeID = Employees.EmployeeID --<<<

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(1, 'Davolio', 123, 3),
 (2, 'Fuller', 96, 4),
 (3, 'Leverling', 127, 5),
 (4, 'Peacock', 156, 10),
 (5, 'Buchanan', 42, None),
 (6, 'Suyama', 67, 3),
 (7, 'King', 72, 4),
 (8, 'Callahan', 104, 5),
 (9, 'Dodsworth', 43, 5)]

## M.45 Date transformation (continued)

Method 1.

In [15]:
%%sql
; WITH LateOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    WHERE RequiredDate <= ShippedDate --<<<
    GROUP BY EmployeeID
)
, AllOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    GROUP BY EmployeeID
)

SELECT 
    Employees.EmployeeID, 
    LastName, 
    AllOrders = AllOrders.TotalOrders, 
    LateOrders = 
        CASE WHEN LateOrders.TotalOrders IS NULL THEN 0
        ELSE LateOrders.TotalOrders
        END
FROM Employees
JOIN AllOrders ON AllOrders.EmployeeID = Employees.EmployeeID
LEFT JOIN LateOrders ON LateOrders.EmployeeID = Employees.EmployeeID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(1, 'Davolio', 123, 3),
 (2, 'Fuller', 96, 4),
 (3, 'Leverling', 127, 5),
 (4, 'Peacock', 156, 10),
 (5, 'Buchanan', 42, 0),
 (6, 'Suyama', 67, 3),
 (7, 'King', 72, 4),
 (8, 'Callahan', 104, 5),
 (9, 'Dodsworth', 43, 5)]

Method 2. better just using ISNULL()

In [12]:
%%sql
; WITH LateOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    WHERE RequiredDate <= ShippedDate
    GROUP BY EmployeeID
)
, AllOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    GROUP BY EmployeeID
)

SELECT Employees.EmployeeID, LastName, AllOrders = AllOrders.TotalOrders, LateOrders = ISNULL(LateOrders.TotalOrders, 0) --<<<
FROM Employees
JOIN AllOrders ON AllOrders.EmployeeID = Employees.EmployeeID
LEFT JOIN LateOrders ON LateOrders.EmployeeID = Employees.EmployeeID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(1, 'Davolio', 123, 3),
 (2, 'Fuller', 96, 4),
 (3, 'Leverling', 127, 5),
 (4, 'Peacock', 156, 10),
 (5, 'Buchanan', 42, 0),
 (6, 'Suyama', 67, 3),
 (7, 'King', 72, 4),
 (8, 'Callahan', 104, 5),
 (9, 'Dodsworth', 43, 5)]

## M.46 Normalization

In [17]:
%%sql
; WITH LateOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    WHERE RequiredDate <= ShippedDate
    GROUP BY EmployeeID
)
, AllOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    GROUP BY EmployeeID
)

SELECT Employees.EmployeeID, 
    LastName, 
    AllOrders = AllOrders.TotalOrders, 
    LateOrders = ISNULL(LateOrders.TotalOrders, 0),
    PercentLateOrders = ISNULL(LateOrders.TotalOrders, 0) * 1.00 / AllOrders.TotalOrders
FROM Employees
JOIN AllOrders ON AllOrders.EmployeeID = Employees.EmployeeID
LEFT JOIN LateOrders ON LateOrders.EmployeeID = Employees.EmployeeID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(1, 'Davolio', 123, 3, Decimal('0.0243902439024')),
 (2, 'Fuller', 96, 4, Decimal('0.0416666666666')),
 (3, 'Leverling', 127, 5, Decimal('0.0393700787401')),
 (4, 'Peacock', 156, 10, Decimal('0.0641025641025')),
 (5, 'Buchanan', 42, 0, Decimal('0E-13')),
 (6, 'Suyama', 67, 3, Decimal('0.0447761194029')),
 (7, 'King', 72, 4, Decimal('0.0555555555555')),
 (8, 'Callahan', 104, 5, Decimal('0.0480769230769')),
 (9, 'Dodsworth', 43, 5, Decimal('0.1162790697674'))]

## M.47 Format Statement
Display the PercentLateOrders in the format of 2 digits to the right of the decimal point.

In [19]:
%%sql
; WITH LateOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    WHERE RequiredDate <= ShippedDate
    GROUP BY EmployeeID
)
, AllOrders AS(
    SELECT EmployeeID, TotalOrders = COUNT(*)
    FROM Orders
    GROUP BY EmployeeID
)

SELECT Employees.EmployeeID, 
    LastName, 
    AllOrders = AllOrders.TotalOrders, 
    LateOrders = ISNULL(LateOrders.TotalOrders, 0),
    PercentLateOrders = CONVERT(DECIMAL(10, 2), ISNULL(LateOrders.TotalOrders, 0) * 1.00 / AllOrders.TotalOrders)
FROM Employees
JOIN AllOrders ON AllOrders.EmployeeID = Employees.EmployeeID
LEFT JOIN LateOrders ON LateOrders.EmployeeID = Employees.EmployeeID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(1, 'Davolio', 123, 3, Decimal('0.02')),
 (2, 'Fuller', 96, 4, Decimal('0.04')),
 (3, 'Leverling', 127, 5, Decimal('0.04')),
 (4, 'Peacock', 156, 10, Decimal('0.06')),
 (5, 'Buchanan', 42, 0, Decimal('0.00')),
 (6, 'Suyama', 67, 3, Decimal('0.04')),
 (7, 'King', 72, 4, Decimal('0.06')),
 (8, 'Callahan', 104, 5, Decimal('0.05')),
 (9, 'Dodsworth', 43, 5, Decimal('0.12'))]

## M.48 Data binning
Group customers into groups based on how much they ordered in 2016. <br>
The bins for categorization are 0 to 1000, 1000 to 5000, 5000 to 10,000, and over 10,000. <br>

In [20]:
%%sql
; WITH Orders2016 AS(
    SELECT Customers.CustomerID, Customers.CompanyName, TotalOrderAmount = SUM(Quantity * UnitPrice)
    FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
    WHERE YEAR(OrderDate) = 2016
    GROUP BY Customers.CustomerID, Customers.CompanyName
)
SELECT CustomerID, CompanyName, TotalOrderAmount, 
    CustomerGroup = 
        CASE
        WHEN TotalOrderAmount BETWEEN 0 AND 1000 THEN 'Low'
        WHEN TotalOrderAmount BETWEEN 1001 AND 5000 THEN 'Medium'
        WHEN TotalOrderAmount BETWEEN 5001 AND 10000 THEN 'High'
        WHEN TotalOrderAmount > 10000 THEN 'Very High'
        END    
FROM Orders2016
ORDER BY CustomerID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[('ALFKI', 'Alfreds Futterkiste', Decimal('2302.2000'), 'Medium'),
 ('ANATR', 'Ana Trujillo Emparedados y helados', Decimal('514.4000'), 'Low'),
 ('ANTON', 'Antonio Moreno Taquería', Decimal('660.0000'), 'Low'),
 ('AROUT', 'Around the Horn', Decimal('5838.5000'), 'High'),
 ('BERGS', 'Berglunds snabbköp', Decimal('8110.5500'), 'High'),
 ('BLAUS', 'Blauer See Delikatessen', Decimal('2160.0000'), 'Medium'),
 ('BLONP', 'Blondesddsl père et fils', Decimal('730.0000'), 'Low'),
 ('BOLID', 'Bólido Comidas preparadas', Decimal('280.0000'), 'Low'),
 ('BONAP', "Bon app'", Decimal('7185.9000'), 'High'),
 ('BOTTM', 'Bottom-Dollar Markets', Decimal('12227.4000'), 'Very High'),
 ('BSBEV', "B's Beverages", Decimal('2431.0000'), 'Medium'),
 ('CACTU', 'Cactus Comidas para llevar', Decimal('1576.8000'), 'Medium'),
 ('CHOPS', 'Chop-suey Chinese', Decimal('4429.4000'), 'Medium'),
 ('COMMI', 'Comércio Mineiro', Decimal('513.7500'), 'Low'),
 ('CONSH', 'Consolidated Holdings', Decimal('931.5000'), 'Low'),
 ('DRACD', 'Drachenblut Delikatessen', Decimal('2809.6100'), 'Medium'),
 ('DUMON', 'Du monde entier', Decimal('860.1000'), 'Low'),
 ('EASTC', 'Eastern Connection', Decimal('9569.3100'), 'High'),
 ('ERNSH', 'Ernst Handel', Decimal('42598.9000'), 'Very High'),
 ('FOLKO', 'Folk och fä HB', Decimal('15973.8500'), 'Very High'),
 ('FRANK', 'Frankenversand', Decimal('5587.0000'), 'High'),
 ('FRANR', 'France restauration', Decimal('2252.0600'), 'Medium'),
 ('FRANS', 'Franchi S.p.A.', Decimal('1296.0000'), 'Medium'),
 ('FURIB', 'Furia Bacalhau e Frutos do Mar', Decimal('68.0000'), 'Low'),
 ('GALED', 'Galería del gastrónomo', Decimal('207.5000'), 'Low'),
 ('GODOS', 'Godos Cocina Típica', Decimal('7064.0500'), 'High'),
 ('GOURL', 'Gourmet Lanchonetes', Decimal('497.0000'), 'Low'),
 ('GREAL', 'Great Lakes Food Market', Decimal('10562.5800'), 'Very High'),
 ('HANAR', 'Hanari Carnes', Decimal('24238.0500'), 'Very High'),
 ('HILAA', 'HILARION-Abastos', Decimal('6132.3000'), 'High'),
 ('HUNGO', 'Hungry Owl All-Night Grocers', Decimal('22796.3400'), 'Very High'),
 ('ISLAT', 'Island Trading', Decimal('2684.6000'), 'Medium'),
 ('KOENE', 'Königlich Essen', Decimal('20204.9500'), 'Very High'),
 ('LACOR', "La corne d'abondance", Decimal('1992.0500'), 'Medium'),
 ('LAMAI', "La maison d'Asie", Decimal('1549.9500'), 'Medium'),
 ('LAUGB', 'Laughing Bacchus Wine Cellars', Decimal('187.0000'), 'Low'),
 ('LEHMS', 'Lehmanns Marktstand', Decimal('3342.8500'), 'Medium'),
 ('LETSS', "Let's Stop N Shop", Decimal('1450.6000'), 'Medium'),
 ('LILAS', 'LILA-Supermercado', Decimal('5994.0600'), 'High'),
 ('LINOD', 'LINO-Delicateses', Decimal('10085.6000'), 'Very High'),
 ('LONEP', 'Lonesome Pine Restaurant', Decimal('1709.4000'), 'Medium'),
 ('MAGAA', 'Magazzini Alimentari Riuniti', Decimal('1693.0000'), 'Medium'),
 ('MAISD', 'Maison Dewey', Decimal('5000.2000'), None),
 ('MORGK', 'Morgenstern Gesundkost', Decimal('245.0000'), 'Low'),
 ('NORTS', 'North/South', Decimal('45.0000'), 'Low'),
 ('OCEAN', 'Océano Atlántico Ltda.', Decimal('3031.0000'), 'Medium'),
 ('OLDWO', 'Old World Delicatessen', Decimal('5337.6500'), 'High'),
 ('OTTIK', 'Ottilies Käseladen', Decimal('3012.7000'), 'Medium'),
 ('PERIC', 'Pericles Comidas clásicas', Decimal('1496.0000'), 'Medium'),
 ('PICCO', 'Piccolo und mehr', Decimal('4393.7500'), 'Medium'),
 ('PRINI', 'Princesa Isabel Vinhos', Decimal('2633.9000'), 'Medium'),
 ('QUEDE', 'Que Delícia', Decimal('1353.6000'), 'Medium'),
 ('QUEEN', 'Queen Cozinha', Decimal('7007.6500'), 'High'),
 ('QUICK', 'QUICK-Stop', Decimal('40526.9900'), 'Very High'),
 ('RANCH', 'Rancho grande', Decimal('1694.7000'), 'Medium'),
 ('RATTC', 'Rattlesnake Canyon Grocery', Decimal('21725.6000'), 'Very High'),
 ('REGGC', 'Reggiani Caseifici', Decimal('4263.0000'), 'Medium'),
 ('RICAR', 'Ricardo Adocicados', Decimal('7312.0000'), 'High'),
 ('RICSU', 'Richter Supermarkt', Decimal('5497.9000'), 'High'),
 ('ROMEY', 'Romero y tomillo', Decimal('726.8900'), 'Low'),
 ('SANTG', 'Santé Gourmet', Decimal('3976.7500'), 'Medium'),
 ('SAVEA', 'Save-a-lot Markets', Decimal('42806.2500'), 'Very High'),
 ('SEVES', 'Seven Seas Imports', Decimal('1630.0000'), 'Medium'),
 ('SIMOB', 'Simons bistro', Decimal('244.3000'), 'Low'),
 ('SPECD', 'Spécialités du monde', Decimal('2371.0000'), 'Medium'),
 ('SPLIR', 'Split Rail Beer & Ale', Decimal('1117.0000'), 'Medium'),
 ('SUPRD', 'Suprêmes délices', Decimal('11862.5000'), 'Very High'),
 ('THEBI', 'The Big Cheese', Decimal('69.6000'), 'Low'),
 ('THECR', 'The Cracker Box', Decimal('326.0000'), 'Low'),
 ('TOMSP', 'Toms Spezialitäten', Decimal('910.4000'), 'Low'),
 ('TORTU', 'Tortuga Restaurante', Decimal('1874.5000'), 'Medium'),
 ('TRADH', 'Tradição Hipermercados', Decimal('4401.6200'), 'Medium'),
 ('TRAIH', "Trail's Head Gourmet Provisioners", Decimal('237.9000'), 'Low'),
 ('VAFFE', 'Vaffeljernet', Decimal('4333.5000'), 'Medium'),
 ('VICTE', 'Victuailles en stock', Decimal('3022.0000'), 'Medium'),
 ('WANDK', 'Die Wandernde Kuh', Decimal('1564.0000'), 'Medium'),
 ('WARTH', 'Wartian Herkku', Decimal('300.0000'), 'Low'),
 ('WELLI', 'Wellington Importadora', Decimal('1245.0000'), 'Medium'),
 ('WHITC', 'White Clover Markets', Decimal('15278.9000'), 'Very High'),
 ('WILMK', 'Wilman Kala', Decimal('1987.0000'), 'Medium'),
 ('WOLZA', 'Wolski  Zajazd', Decimal('1865.1000'), 'Medium')]

## M49. Integer binning issue caused by continuous variables
Fix the last script so that there is no None shown in the CustomerGroup field.

In [21]:
%%sql
; WITH Orders2016 AS(
    SELECT Customers.CustomerID, Customers.CompanyName, TotalOrderAmount = SUM(Quantity * UnitPrice)
    FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
    WHERE YEAR(OrderDate) = 2016
    GROUP BY Customers.CustomerID, Customers.CompanyName
)
SELECT CustomerID, CompanyName, TotalOrderAmount, 
    CustomerGroup = 
        CASE
        WHEN TotalOrderAmount >= 0 AND TotalOrderAmount < 1000  THEN 'Low'
        WHEN TotalOrderAmount >= 1000 AND TotalOrderAmount < 5000 THEN 'Medium'
        WHEN TotalOrderAmount >= 5001 AND TotalOrderAmount < 10000 THEN 'High'
        WHEN TotalOrderAmount >= 10000 THEN 'Very High'
        END    
FROM Orders2016
ORDER BY CustomerID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[('ALFKI', 'Alfreds Futterkiste', Decimal('2302.2000'), 'Medium'),
 ('ANATR', 'Ana Trujillo Emparedados y helados', Decimal('514.4000'), 'Low'),
 ('ANTON', 'Antonio Moreno Taquería', Decimal('660.0000'), 'Low'),
 ('AROUT', 'Around the Horn', Decimal('5838.5000'), 'High'),
 ('BERGS', 'Berglunds snabbköp', Decimal('8110.5500'), 'High'),
 ('BLAUS', 'Blauer See Delikatessen', Decimal('2160.0000'), 'Medium'),
 ('BLONP', 'Blondesddsl père et fils', Decimal('730.0000'), 'Low'),
 ('BOLID', 'Bólido Comidas preparadas', Decimal('280.0000'), 'Low'),
 ('BONAP', "Bon app'", Decimal('7185.9000'), 'High'),
 ('BOTTM', 'Bottom-Dollar Markets', Decimal('12227.4000'), 'Very High'),
 ('BSBEV', "B's Beverages", Decimal('2431.0000'), 'Medium'),
 ('CACTU', 'Cactus Comidas para llevar', Decimal('1576.8000'), 'Medium'),
 ('CHOPS', 'Chop-suey Chinese', Decimal('4429.4000'), 'Medium'),
 ('COMMI', 'Comércio Mineiro', Decimal('513.7500'), 'Low'),
 ('CONSH', 'Consolidated Holdings', Decimal('931.5000'), 'Low'),
 ('DRACD', 'Drachenblut Delikatessen', Decimal('2809.6100'), 'Medium'),
 ('DUMON', 'Du monde entier', Decimal('860.1000'), 'Low'),
 ('EASTC', 'Eastern Connection', Decimal('9569.3100'), 'High'),
 ('ERNSH', 'Ernst Handel', Decimal('42598.9000'), 'Very High'),
 ('FOLKO', 'Folk och fä HB', Decimal('15973.8500'), 'Very High'),
 ('FRANK', 'Frankenversand', Decimal('5587.0000'), 'High'),
 ('FRANR', 'France restauration', Decimal('2252.0600'), 'Medium'),
 ('FRANS', 'Franchi S.p.A.', Decimal('1296.0000'), 'Medium'),
 ('FURIB', 'Furia Bacalhau e Frutos do Mar', Decimal('68.0000'), 'Low'),
 ('GALED', 'Galería del gastrónomo', Decimal('207.5000'), 'Low'),
 ('GODOS', 'Godos Cocina Típica', Decimal('7064.0500'), 'High'),
 ('GOURL', 'Gourmet Lanchonetes', Decimal('497.0000'), 'Low'),
 ('GREAL', 'Great Lakes Food Market', Decimal('10562.5800'), 'Very High'),
 ('HANAR', 'Hanari Carnes', Decimal('24238.0500'), 'Very High'),
 ('HILAA', 'HILARION-Abastos', Decimal('6132.3000'), 'High'),
 ('HUNGO', 'Hungry Owl All-Night Grocers', Decimal('22796.3400'), 'Very High'),
 ('ISLAT', 'Island Trading', Decimal('2684.6000'), 'Medium'),
 ('KOENE', 'Königlich Essen', Decimal('20204.9500'), 'Very High'),
 ('LACOR', "La corne d'abondance", Decimal('1992.0500'), 'Medium'),
 ('LAMAI', "La maison d'Asie", Decimal('1549.9500'), 'Medium'),
 ('LAUGB', 'Laughing Bacchus Wine Cellars', Decimal('187.0000'), 'Low'),
 ('LEHMS', 'Lehmanns Marktstand', Decimal('3342.8500'), 'Medium'),
 ('LETSS', "Let's Stop N Shop", Decimal('1450.6000'), 'Medium'),
 ('LILAS', 'LILA-Supermercado', Decimal('5994.0600'), 'High'),
 ('LINOD', 'LINO-Delicateses', Decimal('10085.6000'), 'Very High'),
 ('LONEP', 'Lonesome Pine Restaurant', Decimal('1709.4000'), 'Medium'),
 ('MAGAA', 'Magazzini Alimentari Riuniti', Decimal('1693.0000'), 'Medium'),
 ('MAISD', 'Maison Dewey', Decimal('5000.2000'), None),
 ('MORGK', 'Morgenstern Gesundkost', Decimal('245.0000'), 'Low'),
 ('NORTS', 'North/South', Decimal('45.0000'), 'Low'),
 ('OCEAN', 'Océano Atlántico Ltda.', Decimal('3031.0000'), 'Medium'),
 ('OLDWO', 'Old World Delicatessen', Decimal('5337.6500'), 'High'),
 ('OTTIK', 'Ottilies Käseladen', Decimal('3012.7000'), 'Medium'),
 ('PERIC', 'Pericles Comidas clásicas', Decimal('1496.0000'), 'Medium'),
 ('PICCO', 'Piccolo und mehr', Decimal('4393.7500'), 'Medium'),
 ('PRINI', 'Princesa Isabel Vinhos', Decimal('2633.9000'), 'Medium'),
 ('QUEDE', 'Que Delícia', Decimal('1353.6000'), 'Medium'),
 ('QUEEN', 'Queen Cozinha', Decimal('7007.6500'), 'High'),
 ('QUICK', 'QUICK-Stop', Decimal('40526.9900'), 'Very High'),
 ('RANCH', 'Rancho grande', Decimal('1694.7000'), 'Medium'),
 ('RATTC', 'Rattlesnake Canyon Grocery', Decimal('21725.6000'), 'Very High'),
 ('REGGC', 'Reggiani Caseifici', Decimal('4263.0000'), 'Medium'),
 ('RICAR', 'Ricardo Adocicados', Decimal('7312.0000'), 'High'),
 ('RICSU', 'Richter Supermarkt', Decimal('5497.9000'), 'High'),
 ('ROMEY', 'Romero y tomillo', Decimal('726.8900'), 'Low'),
 ('SANTG', 'Santé Gourmet', Decimal('3976.7500'), 'Medium'),
 ('SAVEA', 'Save-a-lot Markets', Decimal('42806.2500'), 'Very High'),
 ('SEVES', 'Seven Seas Imports', Decimal('1630.0000'), 'Medium'),
 ('SIMOB', 'Simons bistro', Decimal('244.3000'), 'Low'),
 ('SPECD', 'Spécialités du monde', Decimal('2371.0000'), 'Medium'),
 ('SPLIR', 'Split Rail Beer & Ale', Decimal('1117.0000'), 'Medium'),
 ('SUPRD', 'Suprêmes délices', Decimal('11862.5000'), 'Very High'),
 ('THEBI', 'The Big Cheese', Decimal('69.6000'), 'Low'),
 ('THECR', 'The Cracker Box', Decimal('326.0000'), 'Low'),
 ('TOMSP', 'Toms Spezialitäten', Decimal('910.4000'), 'Low'),
 ('TORTU', 'Tortuga Restaurante', Decimal('1874.5000'), 'Medium'),
 ('TRADH', 'Tradição Hipermercados', Decimal('4401.6200'), 'Medium'),
 ('TRAIH', "Trail's Head Gourmet Provisioners", Decimal('237.9000'), 'Low'),
 ('VAFFE', 'Vaffeljernet', Decimal('4333.5000'), 'Medium'),
 ('VICTE', 'Victuailles en stock', Decimal('3022.0000'), 'Medium'),
 ('WANDK', 'Die Wandernde Kuh', Decimal('1564.0000'), 'Medium'),
 ('WARTH', 'Wartian Herkku', Decimal('300.0000'), 'Low'),
 ('WELLI', 'Wellington Importadora', Decimal('1245.0000'), 'Medium'),
 ('WHITC', 'White Clover Markets', Decimal('15278.9000'), 'Very High'),
 ('WILMK', 'Wilman Kala', Decimal('1987.0000'), 'Medium'),
 ('WOLZA', 'Wolski  Zajazd', Decimal('1865.1000'), 'Medium')]

## M50. Integrating M48 with M49 (continued) <<<---

In [26]:
%%sql
; WITH Orders2016 AS(
    SELECT Customers.CustomerID, Customers.CompanyName, TotalOrderAmount = SUM(Quantity * UnitPrice)
    FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
    WHERE YEAR(OrderDate) = 2016
    GROUP BY Customers.CustomerID, Customers.CompanyName
), CustomerGrouping AS(
    SELECT CustomerID, CompanyName, TotalOrderAmount, 
    CustomerGroup = 
        CASE
        WHEN TotalOrderAmount >= 0 AND TotalOrderAmount < 1000  THEN 'Low'
        WHEN TotalOrderAmount >= 1000 AND TotalOrderAmount < 5000 THEN 'Medium'
        WHEN TotalOrderAmount >= 5001 AND TotalOrderAmount < 10000 THEN 'High'
        WHEN TotalOrderAmount >= 10000 THEN 'Very High'
        END    
    FROM Orders2016
    --ORDER BY CustomerID <<< The ORDER BY command is invalid in derived tables.
)
SELECT CustomerGroup, TotalInGroup = COUNT(*), PercentageInGroup = COUNT(*) * 1.0 / (SELECT COUNT(*) FROM CustomerGrouping)
FROM CustomerGrouping
GROUP BY CustomerGroup 
ORDER BY TotalInGroup DESC

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[('Medium', 35, Decimal('0.432098765432')),
 ('Low', 20, Decimal('0.246913580246')),
 ('Very High', 13, Decimal('0.160493827160')),
 ('High', 12, Decimal('0.148148148148')),
 (None, 1, Decimal('0.012345679012'))]

## M51. incomplete

In [28]:
%%sql
; WITH Orders2016 AS(
    SELECT Customers.CustomerID, Customers.CompanyName, TotalOrderAmount = SUM(Quantity * UnitPrice)
    FROM Customers
    JOIN Orders ON Orders.CustomerID = Customers.CustomerID
    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID
    WHERE YEAR(OrderDate) = 2016
    GROUP BY Customers.CustomerID, Customers.CompanyName
)

SELECT CustomerID, CompanyName, TotalOrderAmount, CustomerGroupName
FROM Orders2016
JOIN CustomerGroupThresholds ON Orders2016.TotalOrderAmount BETWEEN CustomerGroupThresholds.RangeBottom AND CustomerGroupThresholds.RangeTop
ORDER BY CustomerID

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
(pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'and'. (4145) (SQLExecDirectW)") [SQL: "WITH Orders2016 AS(\n    SELECT Customers.CustomerID, Customers.CompanyName, TotalOrderAmount = SUM(Quantity * UnitPrice)\n    FROM Customers\n    JOIN Orders ON Orders.CustomerID = Customers.CustomerID\n    JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID\n    WHERE YEAR(OrderDate) = 2016\n    GROUP BY Customers.CustomerID, Customers.CompanyName\n), CustomerGrouping AS(\n    SELECT CustomerID, CompanyName, TotalOrderAmount, \n    CustomerGroup = \n        CASE\n        WHEN TotalOrderAmount >= 0 AND TotalOrderAmount < 1000  THEN 'Low'\n        WHEN TotalOrderAmount >= 1000 AND TotalOrderAmount < 5000 THEN 'Medium'\n        WHEN TotalOrderAmount >= 5001 AND TotalOrderAmount < 10000 THEN 'High'\n        WHEN TotalOrderAmount >= 10000 THEN 'Very High'\n        END    \n    FROM Orders2016\n    --ORDER BY CustomerID <<< The ORDER BY command is invalid in derived tables.\n)\nSELECT CustomerGroup, TotalInGroup = COUNT(*), PercentageInGroup = COUNT(*) * 1.0 / (SELECT COUNT(*) FROM CustomerGrouping)\nFROM Orders2016\n    JOIN CustomerGroupThresholds ON CustomerGroupThresholds.RangeBottom and CustomerGroupThresholds.RangeTop\nORDER BY CustomerID"] (Background on this error at: http://sqlalche.me/e/f405)

## M52. Show unique elements after merge

In [29]:
%%sql
SELECT Country FROM Customers
UNION
SELECT Country FROM Suppliers
ORDER BY Country

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.

[('Argentina',),
 ('Australia',),
 ('Austria',),
 ('Belgium',),
 ('Brazil',),
 ('Canada',),
 ('Denmark',),
 ('Finland',),
 ('France',),
 ('Germany',),
 ('Ireland',),
 ('Italy',),
 ('Japan',),
 ('Mexico',),
 ('Netherlands',),
 ('Norway',),
 ('Poland',),
 ('Portugal',),
 ('Singapore',),
 ('Spain',),
 ('Sweden',),
 ('Switzerland',),
 ('UK',),
 ('USA',),
 ('Venezuela',)]

## M53. Add more details after merge (continued)

In [34]:
%%sql
; WITH SupplierCountries AS(
    SELECT DISTINCT Country FROM Suppliers
), CustomerCountries AS(
    SELECT DISTINCT Country FROM Customers
) 
SELECT SupplierCountry = SupplierCountries.Country, CustomerCountry = CustomerCountries.Country
FROM SupplierCountries
FULL OUTER JOIN CustomerCountries ON CustomerCountries.Country = SupplierCountries.Country

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[(None, 'Argentina'),
 ('Australia', None),
 (None, 'Austria'),
 (None, 'Belgium'),
 ('Brazil', 'Brazil'),
 ('Canada', 'Canada'),
 ('Denmark', 'Denmark'),
 ('Finland', 'Finland'),
 ('France', 'France'),
 ('Germany', 'Germany'),
 (None, 'Ireland'),
 ('Italy', 'Italy'),
 ('Japan', None),
 (None, 'Mexico'),
 ('Netherlands', None),
 ('Norway', 'Norway'),
 (None, 'Poland'),
 (None, 'Portugal'),
 ('Singapore', None),
 ('Spain', 'Spain'),
 ('Sweden', 'Sweden'),
 (None, 'Switzerland'),
 ('UK', 'UK'),
 ('USA', 'USA'),
 (None, 'Venezuela')]

## M54. Count the number of suppliers and customers by country

In [35]:
%%sql
; WITH SupplierCountries AS(
    SELECT Country, Total = COUNT(*) FROM Suppliers GROUP BY Country
), CustomerCountries AS(
    SELECT Country, Total = COUNT(*) FROM Customers GROUP BY Country
) 

SELECT Country = ISNULL(SupplierCountries.Country, CustomerCountries.Country), 
    TotalSuppliers = ISNULL(SupplierCountries.Total, 0), 
    TotalCustomers = ISNULL(CustomerCountries.Total, 0)
FROM SupplierCountries
FULL OUTER JOIN CustomerCountries ON CustomerCountries.Country = SupplierCountries.Country

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[('Argentina', 0, 3),
 ('Australia', 2, 0),
 ('Austria', 0, 2),
 ('Belgium', 0, 2),
 ('Brazil', 1, 9),
 ('Canada', 2, 3),
 ('Denmark', 1, 2),
 ('Finland', 1, 2),
 ('France', 3, 11),
 ('Germany', 3, 11),
 ('Ireland', 0, 1),
 ('Italy', 2, 3),
 ('Japan', 2, 0),
 ('Mexico', 0, 5),
 ('Netherlands', 1, 0),
 ('Norway', 1, 1),
 ('Poland', 0, 1),
 ('Portugal', 0, 2),
 ('Singapore', 1, 0),
 ('Spain', 1, 5),
 ('Sweden', 2, 2),
 ('Switzerland', 0, 2),
 ('UK', 2, 7),
 ('USA', 4, 13),
 ('Venezuela', 0, 4)]

## M55. First order in each country

In [36]:
%%sql
; WITH OrdersByCountry AS(
    SELECT ShipCountry, CustomerID, OrderID, OrderDate = CONVERT(DATE, OrderDate), 
        RowNumberPerCountry = Row_Number() over (Partition by ShipCountry Order by ShipCountry, OrderID)
    FROM Orders
)

SELECT ShipCountry, CustomerID, OrderID, OrderDate
FROM OrdersByCountry
WHERE RowNumberPerCountry = 1 --<<<
ORDER BY ShipCountry

 * mssql+pyodbc://sa:***@DESKTOP-NJ3QO6I:1433/NorthWind2016?driver=ODBC Driver 13 for SQL Server
Done.
Done.

[('Argentina', 'OCEAN', 10409, datetime.date(2015, 1, 9)),
 ('Austria', 'ERNSH', 10258, datetime.date(2014, 7, 17)),
 ('Belgium', 'SUPRD', 10252, datetime.date(2014, 7, 9)),
 ('Brazil', 'HANAR', 10250, datetime.date(2014, 7, 8)),
 ('Canada', 'MEREP', 10332, datetime.date(2014, 10, 17)),
 ('Denmark', 'SIMOB', 10341, datetime.date(2014, 10, 29)),
 ('Finland', 'WARTH', 10266, datetime.date(2014, 7, 26)),
 ('France', 'VINET', 10248, datetime.date(2014, 7, 4)),
 ('Germany', 'TOMSP', 10249, datetime.date(2014, 7, 5)),
 ('Ireland', 'HUNGO', 10298, datetime.date(2014, 9, 5)),
 ('Italy', 'MAGAA', 10275, datetime.date(2014, 8, 7)),
 ('Mexico', 'CENTC', 10259, datetime.date(2014, 7, 18)),
 ('Norway', 'SANTG', 10387, datetime.date(2014, 12, 18)),
 ('Poland', 'WOLZA', 10374, datetime.date(2014, 12, 5)),
 ('Portugal', 'FURIB', 10328, datetime.date(2014, 10, 14)),
 ('Spain', 'ROMEY', 10281, datetime.date(2014, 8, 14)),
 ('Sweden', 'FOLKO', 10264, datetime.date(2014, 7, 24)),
 ('Switzerland', 'CHOPS', 10254, datetime.date(2014, 7, 11)),
 ('UK', 'BSBEV', 10289, datetime.date(2014, 8, 26)),
 ('USA', 'RATTC', 10262, datetime.date(2014, 7, 22)),
 ('Venezuela', 'HILAA', 10257, datetime.date(2014, 7, 16))]

## M56. Show customers who have ever made more than 1 order in a 5-day period.

In [ ]:
%%sql
SELECT InitialOrder.Customer, InitialOrderID = InitialOrder.OrderID, 
    InitialOrderDate = CONVERT(DATE, InitialOrder.OrderDate),
    NextOrderID = NextOrder.OrderID,
    NextOrderDate = CONVERT(DATE, NextOrder.OrderDate),
    DaysBetween = DATEDIFF(DD, InitialOrder.OrderDate, NextOrder.OrderDate)
FROM Orders InitialOrder JOIN Orders NextOrder ON InitialOrder.CustomerID = NextOrder.CustomerID
WHERE InitialOrder.OrderID < NextOrder.OrderID AND Datediff(DD, InitialOrder.OrderDate, NextOrder.OrderDate) <= 5
ORDER BY InitialOrder.CustomerID, InitiallOrder.OrderID

## M57. Aontertive method (continued)

In [ ]:
%%sql
; WITH NextOrderDate AS(
    SELECT CustomerID, OrderDate = CONVERT(DATE, OrderDate),
        NextOrderDate = CONVERT(DATE, LEAD(OrderDate, 1) OVER (PARTITION BY CustomerID ORDER BY CustomerID, OrderDate))
    FROM Orders
)
SELECT CustomerID, OrderDate, NextOrderDate, DaysBetweenOrders = DateDiff(DD, OrderDate, NextOrderDate)
FROM NextOrderDate
WHERE DateDiff(DD, OrderDate, NextOrderDate) <= 5